### ISSUE TITLE
Possible Addition - Centralization

### ISSUE THREAD

**Issue by EmperorRAG** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#1]
Would it be possible to add in centralization decisions for different governments which would provide different bonuses and disabilities. Authoritarian states could have the choice between centralized and decentralized while democratic states only having minor centralization to decentralized.

Bonuses to centralized states could be better tax efficiency, increased assimilation, reduced issue change speed, increased party support due to some form of indoctrination and better factory modifiers.

Disadvantages would be increased unrest, if possible an increase to the number of bureaucrats needed to maintain the state, the extra bureaucrats would lead to higher expenses for the states as well, the corruption modifiers already in the mod could be incorporated into the centralization disadvantages.

Decentralization would provide the reversed effects. The norm for the states would probably be the middle ground providing no effects. These different choices would allow the player to guide their country towards their playing style, except in the cases of communist states where the default would have to be a highly centralized state.

Thanks for reading. :-)

**Comment by settintotrieste** [comment]
Thank you for the idea. That is a very good suggestion! I shall add it to the mod.
