### ISSUE TITLE
Greater Russia decision available to USSR

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#10]
Though the event references reclaiming the former Soviet Union, the USSR can get cores on its minority land with sufficient jingoism.
Possible fix: have potential for the decision exclude the owner of Kiev and Minsk or check for a modifier from a fallen USSR

**Comment by settintotrieste** [comment]
Sure. I will use the check for owner of those 2 provinces as it is simpler conditions wise.

**Comment by ARR8** [comment]
Sure - it should include some check that the province owners aren't Russian puppets, though.

**Comment by settintotrieste** [comment]
Thanks, I will add it to the mod.
