### ISSUE TITLE
Static territorial changes

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#100]
[Amyntas said on the forum thread:](https://forum.paradoxplaza.com/forum/index.php?threads/cold-war-enhancement-mod-a-nwo-submod.987496/page-15#post-22621943)

Hey all, so I love the mod but I want to change it so there are more organic wars being declared.

Normally increasing AI aggression to 30-40 in defines.lua suffices for this in every mod i've played, but in this one it's still painfully static -- I want the world to feel more alive, like what's possible in the base NWO mod. This mod has massively superior flavor and political systems, though, so i'm trying to make it work here.

Any ideas? How do I get nations to start justifying wars again? It would vastly improve my experience. 

----------------------
This is a good point; even nations who claim irredeemed borders will rarely declare for them. This is probably due to only jingoist nations getting any CBs for territorial change. Maybe pro-military governments should be able to get the reclaim cores and annex core country CBs, to solve both issues?

I'm not sure about fabricating such CBs as liberate country and acquire state, but maybe they should be easier to add between nations already at war.

Obviously anything like this will need testing to make sure the world doesn't break too much, but there are definitely some parts of the world that have received less attention in terms of event wars, and even event wars won't happen past the present date.

**Comment by settintotrieste** [comment]
Currently both pro military and jingoist governments can already get CBs for reclaim cores and annex core country. 

The current world situation seems to indicate a trend from interstate conflict to intrastate ones with increasingly fewer wars with complex war goals that are of the scope of whole nation annexation and even liberation of countries. In fact the vast majorities of wars are now just proxy wars using indegenous rebels or very short wars eg. The 6 days war. So making it easier to pile on more damaging war goals should not be realistic under current world circumstances. So the current layout of having all CB options avaliable when Cold War/world tension is high and the current scaling of CB options with more military supportive parties adequate.
