### ISSUE TITLE
Custodianship of my submods

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#1005]
@settintotrieste @ccfox I am no longer able to maintain my GitHub account due to illness; would y'all take care of the submods I've been working on?

**Comment by Outta-my-way-burrocrat** [comment]
Well I am still alive, but not very well. I think I can get back to bugfixing my submods.

**Comment by ccfox** [comment]
I'm sorry to hear, I hope you end up doing better.

Apologies for not replying earlier, I've been somewhat busy. I have a list of changes I want to make to my fork of the mod, once I'm finally able to finish cleaning up the events. I'll probably post them as an issues when I have time, there might be overlap between those and the submods perhaps that would make it easier?
