### ISSUE TITLE
UN Secretary General Enhancement

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#101]
Settintotrieste:

Probably just an extra event that is triggered by the UNSG selection event with a flat percentage of say 5% THIS provides UNSG and 95% a random country gets the event with the event a major to inform all nations.

ARR8:

Great - possibly the chance could be weighted by participation in UN events and international orgs, so you don't get populists taking pride in their UN leadership; but that's an issue for a different commit.

**Comment by ARR8** [comment]
Using new mechanic from #102 TODO:
- Add a decision for populist or Manchurian Candidate nations to leave the UN, which will move the HQ if owned.
- Create an event that will move the HQ if the country is above the infamy limit - integrate into existing over-infamy event if there is one.

**Comment by settintotrieste** [comment]
UN HQ can leave and resettle somewhere else if the country is nuked etc
