### ISSUE TITLE
Union of Eurasian States not add accepted cultures of the new members states in the union

### ISSUE THREAD

**Issue by Santiago2710** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#1015]
i form the Union of Eurasian States as the soviet union and i am anexing countries that have eurasian economic ambitions country flag. the countries are annex, i get cores, but i don´t get accepted cultures.

**Comment by ccfox** [comment]
Intended, in my own fork - once I fix whatever issue I have caused with the current changes I am making - it will have a pan-union culture similar to the other Super-states.
