### ISSUE TITLE
Return to Marxism Spam

### ISSUE THREAD

**Issue by Akibawashu** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#1018]
The latest version as of 2/6/2023 has countries spamming 'Return to Marxism-Leninism' decision resulting in rampage prestige spam.

**Comment by settintotrieste** [comment]
Do you have a copy of your save game?

**Comment by Outta-my-way-burrocrat** [comment]
@Akibawashu which decision exactly?
