### ISSUE TITLE
Market socialsit became less popular even if i promove them

### ISSUE THREAD

**Issue by Santiago2710** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#1041]
Market socialsit became less popular even if i promove them
![Captura de pantalla (673)](https://user-images.githubusercontent.com/98244959/230535537-8a71ef76-b983-402e-a2be-c5cdc843ed66.png)

**Comment by Outta-my-way-burrocrat** [comment]
@Santiago2710  it's better to open issues in ccfox's fork, since settintotrieste won't be doing any development work on CWE vic2 anymore: https://github.com/ccfox/CWE-FoxFork/issues

**Comment by Santiago2710** [comment]
@Outta-my-way-burrocrat Which purpose have the code you have written? Does it help to solve the problem? From which file is it?

**Comment by Outta-my-way-burrocrat** [comment]
It's the ideology support conditions for Market Socialists. They get support if a communist party is fucking up or they are ruling under favorable conditions.

**Comment by settintotrieste** [comment]
Thanks @Santiago2710. The problem is with the code here:

`modifier = {
		factor = 0.1
		country = { ruling_party_ideology = communist_social }
		NOT = {
			militancy = 6
			country = { OR = { government = proletarian_dictatorship government = proletarian_dictatorship1 } }
		}
	}`

It should be this instead:

`modifier = {
		factor = 0.1
		country = { ruling_party_ideology = communist_social OR = { government = proletarian_dictatorship government = proletarian_dictatorship1 government = socialist_democracy } }
		militancy = 6
	}`

So Market Socialist support should drop fast if militancy is high.

**Comment by ccfox** [comment]
The same issue exists for communists too, btw.

**Comment by Outta-my-way-burrocrat** [comment]
>Thanks @Santiago2710. The problem is with the code here:
>
>modifier = { factor = 0.1 country = { ruling_party_ideology = communist_social } NOT = { militancy = 6 country = { OR = { government = proletarian_dictatorship government = proletarian_dictatorship1 } } } }

>It should be this instead:

>modifier = { factor = 0.1 country = { ruling_party_ideology = communist_social OR = { government = proletarian_dictatorship government = proletarian_dictatorship1 government = socialist_democracy } } militancy = 6 }

>So Market Socialist support should drop fast only if militancy is high and not the other way round.

@settintotrieste do yo intend to add your changes to CWEvic2?

**Comment by settintotrieste** [comment]
@Outta-my-way-burrocrat Yes I'll be adding the changes to this repo.

**Comment by Santiago2710** [comment]
Where i can find this code? i want to know becuase i want to modified the file.


> Thanks @Santiago2710. The problem is with the code here:
> 
> `modifier = { factor = 0.1 country = { ruling_party_ideology = communist_social } NOT = { militancy = 6 country = { OR = { government = proletarian_dictatorship government = proletarian_dictatorship1 } } } }`
> 
> It should be this instead:
> 
> `modifier = { factor = 0.1 country = { ruling_party_ideology = communist_social OR = { government = proletarian_dictatorship government = proletarian_dictatorship1 government = socialist_democracy } } militancy = 6 }`
> 
> So Market Socialist support should drop fast only if militancy is high and not the other way round.
