### ISSUE TITLE
Modifier icons + UI rework

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#108]
New icon pictures for organisations/nuclear war etc can be added as country modifier icons to make it easier to differentiate the modifiers and increase aesthetic appeal of the politics screen.

**Comment by ARR8** [comment]
Step-by-step process of how to make the icons as in #107:
1. Expand modifiers.dds by 32 pixels horizontally for every icon to be added.
2. Put the icon centered in its 32x32 block.

If tinting icons red and green:

3. Desaturate based on luminosity.
4. Colorize. Generally, if using HSL, the hue for green is about 98 and the hue for red is about 359, saturation should be unchanged at 50, and brightness adjusted to match neighboring icons if needed.

Whether tinting or not:

5. Edit interface/general_gfx.gfx line 17 to reflect the new number of icons.

When testing, keep in mind [the numbering offset](http://www.victoria2wiki.com/Modifier_effects#Modifier_Icons).

**Comment by ARR8** [comment]
Would a nuclear icon be helpful? ![nuke_icon](https://cloud.githubusercontent.com/assets/8064135/25307175/5a2d26dc-276a-11e7-9a4c-922304c7244b.png)

**Comment by ARR8** [comment]
I think this would also be the issue to discuss the aesthetic of the mod. NWO has obviously departed from the Vic2 aesthetic, which is good. However, I think we can agree it went too far in some respects, such as the photorealistic map changes, which this mod undoes.

Most of the graphics are fine, but there are some which I feel can be improved. Some examples (mod vs vanilla):
- Simplified Muslim icons
  - ![icon_religion](https://cloud.githubusercontent.com/assets/8064135/25307303/c660814e-276c-11e7-9e19-49fc4f64f8a7.png)
  - ![icon_religion 2](https://cloud.githubusercontent.com/assets/8064135/25307304/c7f28836-276c-11e7-995b-15771cf3f1a3.png)
- Influence investment stars
  - ![diplo_priobutton](https://cloud.githubusercontent.com/assets/8064135/25307327/3253d248-276d-11e7-864d-afb1f8e6fb5a.png)
  - ![diplo_priobutton 2](https://cloud.githubusercontent.com/assets/8064135/25307334/52af0d1e-276d-11e7-924c-809646fecc6d.png)
- Grayscale tech boxes
  - ![tech_folder_strip](https://cloud.githubusercontent.com/assets/8064135/25307381/1cdf6a98-276e-11e7-9722-296fcde55b7e.png)
  - ![tech_folder_strip 2](https://cloud.githubusercontent.com/assets/8064135/25307385/2866b5ec-276e-11e7-8b4c-e289180ab812.png)
- Square national values
  - ![politics_nationalvalue](https://cloud.githubusercontent.com/assets/8064135/25307388/30bad7c8-276e-11e7-8499-bd27dfa16b40.png)
  - ![politics_nationalvalue 2](https://cloud.githubusercontent.com/assets/8064135/25307390/34b1591a-276e-11e7-90c5-abed7a4848fe.png)

These are an important part of the overall feel of the mod, and I think it would be better simply to revert them or redo if necessary. Thoughts?

**Comment by settintotrieste** [comment]
The nuclear icon will be very helpful! It can be used to make it more obvious in the politics screen that that the player has achieved nuclear capabilities. It can also make the nuclear strike province modifiers more distinguishable in provinces that have been struck by nuclear bombs.

**Comment by ARR8** [comment]
#131

**Comment by ARR8** [comment]
From #132:
  > For example, the image for "other minerals" and "integrated circuits" is the same, so I built optics factories where there are "other minerals" but didn't get a bonus until I discovered "integrated circuits" factories

**Comment by ARR8** [comment]
The popup window for diplomatic operations on greater powers still uses circular frames with square flags.

**Comment by Uvnam** [comment]
Excuse me for butting in, but how large can the modifier.dds file be? You could add leaders to various countries which give various bonuses by making them an event_modifier and adding an icon for them, but is there a limit for how many you can add?

**Comment by settintotrieste** [comment]
I don't think there is a limit.
