### ISSUE TITLE
Yugolsavia can't join the EU

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#111]
Dragonbreath6434:
So, I have an interesting issue as I continue to play Yugoslavia, when it comes to going down the EU decisions, I come to a crossroads when I have no cores of my own, as to I need an EU core on my capital, which would happen to also be given to wherever I have cores, but since I don't have any cores I have no EU cores. Is there at any point that Yugoslavia gets cores of its own? Especially when shown to be a stable nation like mine is?

settintotrieste:
I did a check and there is no event to add the cores as of yet. What I will do is add the Yugoslav cores in when the player rejects the fragmentation of yugolsavia into the puppets.

**Comment by ARR8** [comment]
There is an event, but it doesn't work very well. It's No. 8224001 in yugoslavia.txt, at the bottom. I'm not sure what it's supposed to do, as it fires only if Yugoslavia is not communist but only before 1963.

Is there any reason why Yugoslavia can't start with all its cores? That seems simpler to me. If needed, they can be removed when the puppets are released.

**Comment by settintotrieste** [comment]
Adding the cores at the start will be the best solution however I don't want to manually add all the cores myself as it I don't have much time at the moment so I need to prioritise it on tweaking and the remaining features for 1.06. If you could help me with this it would be great.
