### ISSUE TITLE
Planned enhancements for Israel

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#113]
#84 primarily had to do with wars and territorial changes. Planned changes for internal Israeli politics, in no particular order:

- Second demographic crisis: if Haredi Jews are the plurality in any province, an event comes giving the option to dismantle the Hasidic lifestyle (remove accepted culture and begin assimilation, very high militancy and support for moralism for the Haredim) or decline and remove the Israeli military genius modifier given at the start of the game, signifying large segments of society not joining the military.
  - For this to be possible, there would need to be a semi-regular event to grow the Haredi population. I think this was planned for NWO, along with the Mennonites, but it was never implemented. (see events 22612 and 22613, set with the yearly pulse)
- Add a modifier, like the military genius one, to boost social reform desire and protectionism. This modifier would also stop the AI from joining several international organizations - reflects the Israeli policy of self-sufficiency after the Holocaust.
- Historical leadership events for each of the PMs. There is one event for the death of a signatory of the declaration of independence from NWO, but this is a relatively minor figure.
- Generic aliyah event - fires every few months, move one random Jewish pop in any other country to a random owned province.
  - This is important, as currently settlement policies on majority-Arab land are not represented, and this would do it.
  - One problem with this is many countries are completely missing minority pops. For example, Benelux, Ethiopia, Scandinavia, and South Europe start with no Jewish pops at all, and there aren't enough in Eastern Europe.
- From #77: there should be some sort of event that makes Circassian and Druze cultures migrate to and become accepted by Israel, considering [this](https://en.wikipedia.org/wiki/Israel_Defense_Forces#Druze_and_Circassians).

Changes for Israeli foreign policy:
- For aligning with great powers: Israel should always align with the GP that has the support Zionism flag (USA), overriding all other logic (e.g. socialist parties).
- Arab states should join Palestine in the Arab-Israeli war.
- If Gaza is released in the second intifada, create a reoccuring event to do with missiles being launched by Hamas, with a chance to reduce pops slightly. There will be a chance to trigger a cut down to size war on Gaza, or even re-annexation for high infamy.
  - After the first such event, potential is unlocked for an Israeli decision to build the Iron Dome with enough money and stop the events, will also grant research points and prestige.

**Comment by settintotrieste** [comment]
Israel had a review in 2020. Some ideas were dropped as it would take too much effort to do.
