### ISSUE TITLE
Turkey addition

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#114]
Hypercharge said:

Can you add 15th of July Coup attempting event to Turkey ? I saw in Millennium Dawn mod made for Hoi4. It would be nice if you add it too. :)

**Comment by ARR8** [comment]
This might be slightly controversial - a significant amount of people are of the opinion that this was encouraged by the government. We could look at how the HoI mod handles this. For the record, similarly controversial events, such as the Chechen apartments bombings, are simply glossed over in the mod currently.

**Comment by settintotrieste** [comment]
I've been thinking about this and I agree with you. So what I will do is to add a simple coup event that fires when a traditionalist party is in power in a democratic turkey post Arab Spring and with the presence of Isis with a random chance of it succeeding or failing with succeeding causing a civil war to break out and failing just causing economic chaos. This should help to sidestep the controversial points of the reason for the coup, the long term consequence of the coup and who was the principal party of the coup.

**Comment by ARR8** [comment]
Good solution, one more thing to consider - the failure of the coup was blamed on the officer purge by the leadership. Maybe the chance for success or failure should be weighted by officers, e.g. having one of the options purge the officers for a higher chance of failure?

**Comment by settintotrieste** [comment]
Sure this is a good idea. I will try to add this feature in by the weekend.
