### ISSUE TITLE
i cant make soldiers of non primary culture in any country

### ISSUE THREAD

**Issue by Santiago2710** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#1175]
non primary culture sodiers are not available in any country.
![image](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/assets/98244959/164d79c2-ccdf-4416-92f1-ca52107390c0)

**Comment by Outta-my-way-burrocrat** [comment]
Blocker for #1153

**Comment by Santiago2710** [comment]
i dont understant

**Comment by settintotrieste** [comment]
It is intentional that some unit types cannot be created from non accepted pops.
