### ISSUE TITLE
Infrastructure bug

### ISSUE THREAD

**Issue by diegoenan** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#1176]
Hello developers, today when I was playing your mod happened a bug with me that made the game close, the situation was as follows I had improved the infrastructure as much as the technology tree allowed me, and when I used the decision to renew the national infrastructure along with the hyper fast trains, and this caused that in some provinces the icon of infrastructure disappeared and in them,   and the tax collection along with the birth rate were negative by a few million, I do not know if you know this bug, but I thought it best to post the about this problem I had, if you want I still have the save of my gameplay today, I translated all the text on google because I am Brazilian and do not know enough of the English language to be able to write text without it.

**Comment by Throwaway-acc-CWEmod** [comment]
The primary developers and contributors have left to start their own forks, but the owner will still accept bugfix PRs.
