### ISSUE TITLE
Arabia takes Salafism even if atheist

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#12]
v1.05, title. May want to set AI will do to 0 if party policy is atheist or secular, and/or if secularism reform is enacted.

It seems that most of the Arabian parties are secular, and I'm not sure about the logic of the reform or the decision which changes it.

**Comment by settintotrieste** [comment]
Thanks, that was a good catch! I will add your fix.
