### ISSUE TITLE
Chilean ruling party faction doesn't exist in 1950

### ISSUE THREAD

**Issue by FixDis** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#1217]
I suggest changing it to "Christian Democratic Party (C)"
https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/blob/ce971bb85e38dc47f26b2a9232a1c45e70910c59/CWE/history/countries/CHL%20-%20Chile.txt#L81

**Comment by FixDis** [comment]
@ccfox

**Comment by ccfox** [comment]
This is the unsupported legacy repo for CWE - this issue doesn't exist in Foxfork. However, I have filed a pull request with the fix regardless.

**Comment by ccfox** [comment]
Nevermind, I have no idea where the pull request I made went. It seems to have pushed itself somewhere else.

**Comment by FixDis** [comment]
@ccfox gotcha. There's a few PRs from v1.16 missing from FoxFork but it looks ready to archive.
