### ISSUE TITLE
More theocracies

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#122]
https://en.wikipedia.org/wiki/Byzantine_commonwealth

For a post-communist right-wing Russia, as a formable theocracy and alternative to Eurasia.

Russian nationalism nowadays, going off Putin, focuses on reclaiming lands of the former USSR, with the Orthodox church as a symbol of national unity. A possible second approach could be centered on the church, with ethnicity secondary. Should probably be a similar difficulty as forming Eurasia, but with less of a priority on economic ties. This could potentially have some interesting flavor with Thrace or other former Byzantine lands (Antioch?)

**Comment by settintotrieste** [comment]
This sounds interesting however just to keep it more realistic, I would suggest that such a route would only be possible under a theocratic Russia as the Byzantine lands idea seems to be more about uniting orthodox people under one flag rather than about uniting national identities like what the current Russian nationalism is like. So I would say that the second approach is better.

**Comment by ARR8** [comment]
Following #165, I'd like to have a theocracy for every religion. Here's some of the options right now:

- Sunni: ISIS
- Shia: Iran
- Ibad: Oman (will have to create event/chain for this)
- Jewish: Israel through an option following the Hasid crisis from #113
- Druze: Druze. Will need flavor events.
- Orthodox: Byzantine Commonwealth (proposed)
- Catholic: Ireland? Maybe an option as part of the end of the monarchy that starts an event chain
- Protestant: Unsure
- Mennonite: Will need a tag
- Buddhist: Tibet
- Hindu: India, will need an event chain
- Sikh: Punjab, unsure of the government form
- Shinto: Japan, should be possible to become an absolute monarchy
- Taoism: unsure, possible Manchukuo-style puppet empire?

**Comment by settintotrieste** [comment]
Sure, I agree that there should be a theocracy for every religion.

Ireland can be turned into catholic theocracy perhaps as part of a IRA chain.

Protestant perhaps something similar to Ireland but for Northern Ireland instead?

A taoist theocracy should be like a Qing empire or Tibet under the Dalai lama

**Comment by ARR8** [comment]
Northern Ireland makes sense. I'll take a look at Ireland events and see where a theocracy could fit and do the mirror for the North.

Tibet, I believe, is already a Buddhist theocracy. Keep in mind for the purposes of sponsoring terror absolute monarchies count as theocracies, so Qing makes perfect sense if there's ever a way to restore it

**Comment by ARR8** [comment]
Another option for a protestant theocracy is a secessionist Deseret in America, at least while Mormons count as Protestant

**Comment by settintotrieste** [comment]
I didn't know that the IRA was secular. Yes then Deseret is a better option. 

I think a way to restore the Qing would be to restore the last emperor or his decendents to the throne as he died in 1967. Perhaps as a result of forming an independent Manchuria after WW2 with the emperor as head of state.
https://en.m.wikipedia.org/wiki/Puyi

**Comment by ARR8** [comment]
That's exactly what I was thinking - maybe adding an event for his repatriation to China, which is historical, but adding a small chance for him to escape. If Manchuria exists, it can get an event to put him on the throne.

But, since Manchuria only exists in ~10% of games, maybe he could also become a faction in the Chinese Civil War. If so, it would have to be an earlier event, since the repatriation happened after the war.

I was thinking, then, that the Soviets send him to destabilize the ROC should it win, and he declare independence for Manchuria, but the Soviets are so hostile to monarchs that I doubt it would happen.

It'll take some planning.

**Comment by settintotrieste** [comment]
I like your ideas. I know that sometimes the USSR does secede Manchuria to the ROC during the Chinese civil war. Perhaps this can tie in with the escape idea such that if it succeeds it forms an independent Manchurian warlord state with the emperor as head of state allied with the ROC in the civil war.

**Comment by settintotrieste** [comment]
@ARR8 I noticed that you've created a branch containing some Manchurian events a few days back, how is it going along?

**Comment by ARR8** [comment]
I've started, but there's a few too many outcomes for me right now. I'll probably save it for 1.07 and make a flowchart or something to make sure every outcome works.

I would recommend working primarily on Islamic theocracies and making sure the ROC can sometimes win the Chinese Civil War for 1.06, and saving minor theocracies for later versions, but feel free to work on it if you'd like. Let me know, I'll clean my notes up and paste them here.

**Comment by settintotrieste** [comment]
Alright

At the moment though, I need the ROC to reliably lose almost all the time for testing purposes.

**Comment by ARR8** [comment]
I hope we can change that for the release. Any specific testing?

**Comment by settintotrieste** [comment]
Not really, just general bug testing. But I need China to be communist to make sure the current cold war event chains and decisions are working fine.

**Comment by ARR8** [comment]
For Ireland: was considering creating event chains to raise traditionalist support eventually culminating in the formation of a theocracy. However, one possibility open to the player could be the ambition toward the creation of a Celtic Union.

**Comment by settintotrieste** [comment]
Idea dropped
