### ISSUE TITLE
Suggestion: Scandinavian expansion

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#15]
Consider a couple of decisions for a formed Scandinavia allowing it to puppet/annex and accept a sphered Scotland or Estonia, based on proposals for such countries to enter the Nordic union. Potentially for any of the Baltic states if populists are in power.

**Comment by settintotrieste** [comment]
That's a good idea, I will add them in.
