### ISSUE TITLE
Potential for superstate decisions

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#152]
There's no reason for European countries to see six Eurasian decisions and five European ones. At most, only the first/next decision in sequence should be visible at one time, and the first should only appear when the technology preceding the one required is unlocked/when continental trade unions were actually proposed.

**Comment by settintotrieste** [comment]
Yes I agree with you. I will fix this by next week.

**Comment by ARR8** [comment]
airpirate:

> The number of decisions is a bit overwhelming. It would be nice if the visibility of the persistent policy changing decisions could be toggled with a different decision.

**Comment by DutchDylan** [comment]
@ARR8 If what you're quoting means what I think it does I'm in favour of it too. 
Currently the decision tab does get clustered up by decisions which 'allow changing of a certain policy' (change centralisation, change baking interests, change espionage policy), a single decision which would hide/show those decisions would be very helpfull. 
Most likely it would be similar to the show/hide vassal decision which hides all the vassals which you can release/unpuppet unless you enable that decision which makes all of them show up, and makes them hidden again by reenacting the decision.

**Comment by ARR8** [comment]
That's feedback we get often, and there's no easy solution. Many of the decisions are designed to be changed every-so-often, and hiding them all will unclutter the list but also hide things that shouldn't be hidden.

At some point, it may be more valuable to do some re-sorting of the decision files to put the flavor and country-unique decisions at the top and "change" decisions at the bottom, and hide all decisions that can't be taken soon, as well as merge some of the things to be changed into other engine features or more general decisions, as well as having associated events.
