### ISSUE TITLE
1992 War History Review

### ISSUE THREAD

**Issue by discretehero** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#166]
When I start as Yugoslavia in 1992 start it is shown that I'm at peace but on the list of current wars I'm shown to be a combatant in the Bosnian and Croatian wars.

**Comment by ARR8** [comment]
Thanks for the bug report. This is a problem with there being two Yugoslavia tags - the communist one and the post-breakup one - and the incorrect one is part of the wars, despite no longer existing. We'll fix this immediately.
