### ISSUE TITLE
Problems with UN Peacekeeping

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#17]
v1.05 - I've noticed a few issues with the UN peacekeeping decisions.
  - The Vietnam war always seems to break because either of the Vietnams calls for it.
- The UK called for peacekeeping when dealing with the Cyprus rebellion - it was granted, and Cyprus became independent.
    - This could have an exception, like for France and Algeria. However, it seems like there are many events that create wars for which this problem could happen, and there are too many to add exceptions to without some kind of modifier on every one.
- Calling certain allies causes them to try to end your war immediately, which is illogical - if they didn't want the war, they simply wouldn't accept the call to arms.
    - It seems that Vic2 mods can't see if a country is the war leader
    - Possible fix - disable if any country at war with the decision taker is also at war with a player country?

For the former two - it looks like it is allowed whenever a country is Pacifist and has less than a quarter home provinces. It seems this should be more restrictive so the AI isn't calling to lose its own wars.

Possibly a comparison in relative military score? Only the militarily weaker nation can call for peacekeeping?

**Comment by settintotrieste** [comment]
Thanks for the feedback! I think It is still important for the countries to seek peace via the UN as it stands but you are right that it is happening too often. So I will adopt your second suggestion and make sure only AIs that are weaker than the countries they are at war with will seek peace.
