### ISSUE TITLE
South Africa Choosing the "Majority Dominance" Decision as a Monarchy.

### ISSUE THREAD

**Issue by BonChoi** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#173]
AI South Africa keeps choosing the "Majority Dominance" decision, making their primary culture Black Anglo and their secondary culture White Anglo, under the "proto-apartheid" government. Would there be any way to prevent this from happening until South Africa becomes a democracy?

**Comment by ARR8** [comment]
We'll prevent that decision while South Africa has a nationalist party in power as well as the existing check for a nationalist government, and add some checks for apartheid. Leaving government checks as-is to allow ending apartheid by communist, populist, etc. revolution.

Thanks for the bug report!

**Comment by BonChoi** [comment]
Great to hear! Sounds like a good solution, thanks for getting back so quick.
