### ISSUE TITLE
Infinite wars of Soviet control over Hungary.

### ISSUE THREAD

**Issue by BonChoi** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#174]
It appears that the Soviet Union will declare war over and over on Hungary. They try to make Hungary a puppet, succeed, and something, either a broken Hungarian uprising event or something else, causes Hungary to break free and join the democratic bloc, causing the USSR to declare war again, which results in the USSR racking up massive amounts of infamy.

**Comment by ARR8** [comment]
May I ask what version you're using? If it's from before three days ago, this should have been fixed in #167. Otherwise, what is Hungary's party ideology?

**Comment by BonChoi** [comment]
Ah, maybe that's it, it's 1.055. Thanks!

**Comment by ARR8** [comment]
Sure - if you want a quick partial fix to stop the wars in new games without updating quite yet, you can add the one-line change from [here](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/commit/14d17fd94a5bd4965db21cba259e46b06c5e4628#diff-b0e82307a101d232f2a0e0f0073e4b21R26). Although, of course, you should update when possible.
