### ISSUE TITLE
Rwanda enhancement

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#175]
Mouzie:

In Rwanda, the Tutsi should be the primary culture with Hutu as non-accepted until 1959 then the Hutu as primary with Tutsi as secondary up until 1993 when the Hutu president and Burundi president is killed when the plane was shot down. This forces the 'Ethic Cleaning' decision as an event for 100 days then ended with the Tutsi now as primary and the Hutu as secondary. However, there will be large immigration pushes of Hutu in the surrounding area if so or leave it as that.

**Comment by ARR8** [comment]
Pre-independence, we can have Black French primary with the other two accepted. Post-independence, testing is needed to see if any problems arise from having Tutsi accepted, but I can't find any evidence as to why it should be. Wiki sounds like there were ethnic conflicts almost immediately after independence.

Post-genocide, it already makes the Tutsis the primary culture, accepting Hutus sounds reasonable enough.

I'm not sure what the last sentence means.

Something I was considering adding was the monarchy referendum, with the choice to keep the monarch adding Tutsi as accepted. The event chains look complicated enough to leave it alone for now, though, although I do like the idea of integrating the existing ethnic cleansing mechanic.

**Comment by settintotrieste** [comment]
I like your ideas but for now I think it is better not to don't touch the genocide chain as I aim to do some changes to it to allow for more types of genocide.
