### ISSUE TITLE
Overall Transports nerf

### ISSUE THREAD

**Issue by nursereno** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#177]
Even after the recent change to the firing range on transport ships, they are grossly overpowered.

If possible can you lower their evasion chance to anything below 100% and disable its damage?

To be honest, they need to take up naval capacity otherwise even after a billion nerfs they can still be used as a pseudo screen for capitals.

**Comment by settintotrieste** [comment]
Thank you for the feedback! I cannot disable damage as it is a means to prevent never ending transport ship only naval battles but what I can do is to reduce damage output by 100 times and decrease evasion by 100 times and fire_range by 5 times. Currently transport ships do take up naval capacity but only by 0.1 each. I will increase it to 0.5 each instead.

**Comment by nursereno** [comment]
Very good, because in a few games me and 4+ other guys have been running naval arms races as to who could build the most transport ships lol. It was fun, but when it came to fighting the game engine literally could not handle giant ship stacks fighting each other.
