### ISSUE TITLE
Nuclear development tech schools

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#179]
From discussion in 64d3300

The mod has regular tech schools, imperial tech schools, and superstate tech schools. This means that the entire period between decolonization and superstate formation uses only the regular tech schools, and most countries have to wait until the latter to get one. Vanilla gives Prussia/NGF/Germany its own school based on its unique historical situation. One possible way to add some flavor to the big players is to give the states which develop nuclear weapons to get a tech school based on this (e.g. Manhattan Project). This would also emulate the increased focus on research brought on by atom bomb development.

**Comment by settintotrieste** [comment]
Good idea, I will add it in.

**Comment by settintotrieste** [comment]
I've decided not to introduce extra tech schools to reduce the difficulty with coding in too many exceptions.
