### ISSUE TITLE
Nuclear attack severity

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#186]
airpirate:

>  More seriously, I think the nuking penalties might be too severe. Obviously being nuked should be bad, but I don't think it should be "reduce Russia to half the size of Ukraine" bad like it is now unless there's a prolonged nuclear war. Russia looks like it's going to be in a state of permanent revolution for the next fifty years which just isn't fun to interact with.

**Comment by settintotrieste** [comment]
With regards to this issue, the scale of damage is scaled to the nuclear attack capability. Low capability has light damage, medium has moderate damage and high capability has heavy damage. In this case, both the us and Russia had high nuclear capability so when they struck each other, the damage was cataclysmic for both. I am certain any nuclear war is not going to be prolonged, it's going to be a quick decisive one. So in this case, it should be like this.
