### ISSUE TITLE
Federation of Indonesia

### ISSUE THREAD

**Issue by balfash** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#190]
I'm sorry if this is not the correct place to ask and I don't know anywhere else to post this.

1. What is the correct way to form Indonesia?
2. When the war of independece start at the start of the game, there's an event to create federated Indonesia as netherlands puppet; if this is the correct way to form Indo, how do I start from here? Because I've waited long enough as a puppet and there's not a event/decision to make Indonesia.
3. At the start of the game, I can research faster when at peace (800 points on the earliest tech) vs when at war (3000 points) and the expensive RP still sticks when I won the war. What caused this? Is it related to defcon level?

That's all I'm still not clear about. Also thanks for making this amazing mod!

edit: and also i'm using the latest github branch.

**Comment by settintotrieste** [comment]
I didn't create the event chain but I will try to answer the questions to the best of my knowledge.

The correct way to form Indonesia to start the Indonesian war of independence and winning it as Indonesia.

A federated Indonesia under the Netherlands was a means to preserve Dutch control over Indonesia so accepting it will make the independence of Indonesia subject to the general conditions for all colonies to become independent which is having a nationalist/populist ruling party and past 1954 or waging another war of independence via the become independent CB.

I'm not sure about the reason why but the Defcon events do not affect research points cost.

**Comment by ARR8** [comment]
And I'd like to add, this absolutely is the correct place to ask questions. We try to respond within a day, if possible. Let us know if you have any more, and thanks for the kind words!

**Comment by balfash** [comment]
Thanks for the answer! I think federated Indonesia should have an event chain to the dissolution of the East Indonesia or East Timor and West Borneo and annex them on 1950 and be replaced as Republic of Indonesia(again), and it shouldn't be as a dutch puppet anymore. Winning _another_  war of Independence against the Dutch in this scenario is impossible because of high warscore and primitive technology.
Source: https://en.wikipedia.org/wiki/Indonesian_National_Revolution, https://en.wikipedia.org/wiki/United_States_of_Indonesia

And for the national party, is there a way to lower the traditional party supports? Because historically Indonesia was dominated by Nationalist and Communist party.
Source: https://en.wikipedia.org/wiki/Indonesian_National_Party

As for the research points modifier, I think puppeted nation gained a significant boost from the overlord's researched technology. I found it on the defines.lua: TECH_FACTOR_VASSAL = 0.25, -- cost reduction factor if overlord has research the tech.

Thanks again!

**Comment by settintotrieste** [comment]
That's a good idea, I will add it in.

I will see what I can do.

Thanks for helping me find out the reason!
