### ISSUE TITLE
Middle Eastern countries prestige spiral

### ISSUE THREAD

**Issue by nursereno** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#199]
Somehow, random middle eastern countries are obtain anywhere between 2k to 5k prestige in the relative beginning of the 1992 start <10 years. Its bumping germany and france out of GP within the very beginning of the game, if you could identify and see whats causing it.

**Comment by settintotrieste** [comment]
Is this from the latest GitHub version of the mod?

**Comment by nursereno** [comment]
Yes, it is an AI scaling thing as I've tried tag switching in a save to see what modifiers are affecting it, but it ceases as soon as I am in control of the country.

Here is a screen. http://i.imgur.com/OgfBgNQ.png

It increases by almost 10 prestige a day.

**Comment by settintotrieste** [comment]
Thanks, I've managed to fix the bug. It was due to a mistype in the Organisation of Ibero-American States decision file.
