### ISSUE TITLE
Crash Fix - Promotion Modifer

### ISSUE THREAD

**Issue by EmperorRAG** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#2]
In the poptypes folder, Labourers.txt and farmers.txt cause crashes due to a promotion modifier when looking in-game at the promotion percentages that both files share which is the export_focus province modifier. Both are found here.

Farmer: https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/blob/03c7d09c74872e1dc818b823bc20c4587951e748/CWE/poptypes/farmers.txt#L234

Labourer: https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/blob/03c7d09c74872e1dc818b823bc20c4587951e748/CWE/poptypes/labourers.txt#L229

You can't use province modifiers in the poptypes files due to them being perceived as pop_scopes by the game engine. What could work is has_country_flag and this would allow for better flexibility when it comes to future coding. All you would need to do is change the decision for the Export Focus to set a country flag.

**Comment by settintotrieste** [comment]
Thanks for helping me out on this. I will make the decision set a country flag in conjunction with the province modifier to make the mechanic work as intended.
