### ISSUE TITLE
Superstate dismantling problem

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#20]
Someone said:

A small bug report I'd like to do while I'm at it. When you use the dismantle nation/empire cb, cultural unions like the European Union or Eurasia (if they have cores) are released. For example as Rusia in the early 2000, I dismantled the UK, the end result was this:
Puu.sh
Scotland, Northen Ireland, and Wales became their own nation, The EU took everything else except for the capital region.

**Comment by settintotrieste** [comment]
Not sure how to fix this. Will close it for now.

**Comment by ARR8** [comment]
I'll take a look at it, though I haven't been able to reproduce in testing as it's a very specific set of circumstances

**Comment by settintotrieste** [comment]
Thanks

**Comment by ARR8** [comment]
An easy fix would be to set every superstate as a cultural union, as the dismantlement events already exclude those. Plus, it makes sense, and I'm a little surprised they aren't already. I'm not sure what else that would affect, though.

**Comment by settintotrieste** [comment]
This is a good fix.
