### ISSUE TITLE
Operation Unthinkable problems

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#201]
Any of the decisions leading to WW3 have a couple of problems as they are currently:

- Foremost, until the Soviets have nukes, DEFCON 1 is never achieved, which makes nuking them impossible, even if the West is badly losing.
- Western allies are prone to declining the call to arms, although I'm not sure what can be done about that.
- If the war occurs before Germany is released, it should thematically be immediately released and divided, disabling all events towards a neutral Germany or Austria, otherwise Germany becomes a very large front in the war.
- Similar issues for Korea. Specifically, a superpower occupying the whole peninsula should have an option to release a united Korea.
- Winning the war quickly and decisively should disable many more events, and at some point event CBs to install communism/democracy should probably be added.

**Comment by settintotrieste** [comment]
I agree with all the point except the first one. Defcon 1 can be achieved even if a country does not have nuclear weapons as it fires when a certain percentage of national provinces are occupied by a foreign power.

**Comment by ARR8** [comment]
For America, this will probably not happen, as a Soviet invasion of the mainland would be very difficult, but they would be very likely to use the nukes if the Soviets invaded the Western bloc and, for example, took over Germany and France. I would suggest adding an exception to DEFCON1 to be set automatically when the cold war goes hot, or adding a line to the logic to check allies' province occupations.

**Comment by settintotrieste** [comment]
I would have to disagree on this as based on the theory of MAD, the purpose of nuclear weapons is to be a weapon of last resort. Using it will have no advantages except as the ultimate revenge for the devastation to their own country. So if we look at this scenario, America will not be incentivised to launch an all out nuclear holocaust on the USSR as it is worth it to completely destroy American lives for the sake of Germany and France? Furthermore, as America has not been invaded yet, it would make more sense to avoid nuclear conflict so that there is still a chance america can reliberate Germany and France.

**Comment by ARR8** [comment]
I would argue that MAD doesn't apply if you are the only country in the world with nukes. Up until there is more than one, America should act like it did in WW2, where it would use the bomb against an enemy who is not willing to surrender. I don't think there would be any risk to American lives, especially since it's such an asymmetrical war.

**Comment by settintotrieste** [comment]
Yes, that's true. So the exception should only apply when there is only 1 nation in the world with nuclear weapons.

**Comment by ARR8** [comment]
#250:
> -If the cold war goes hot before the EU has formed, the Benelux union should form (if none of the three are not aligned with the west or are communist dictatorships) so it could acts one military entity.
