### ISSUE TITLE
Frequency of bailout events for creditors

### ISSUE THREAD

**Issue by nursereno** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#202]
From the 5+ people I play this mod with, the number 1 most annoying thing is the bailout event you get as a great power. I was curious on if you could find a way to avoid these popups. 

Thanks for the work!

**Comment by settintotrieste** [comment]
Thank you for the feedback! At the moment there is no way to prevent it but what I can do is to add a toggling decision called "Refuse to give bailouts" and "willing to give bailouts" to stop a country from receiving bailout requests.

**Comment by ARR8** [comment]
For compilation purposes, this was also mentioned in #109 on April 23rd, where I think we said we'd prioritize preventing countries needing to bailout. Although, I do agree that it should be less of a major decision if it is as frequent as it is now.
