### ISSUE TITLE
Decisions to merge divided nations

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#204]
Like the decision for Korea, it may be desirable to create similar decisions for Vietnam or, for a Turkish or Greek GP, Cyprus (or potentially as an atheist dictatorship, e.g. communist, as religious differences would be ignored). Also possible for Romania/Moldova/Pridnestrovye if the GP is not Russian culture, also Finland and Karelia, etc.

**Comment by ARR8** [comment]
#250:
> -If a great communist power like the Soviet Union or the Chinese People's republic has sphered all the three low countries and all three of them are communist dictatorships already, then there should be the possibility for that great power to unite the three through a decision. This should only be the case for extremist dictatorships and not for democracies and the like.

**Comment by settintotrieste** [comment]
Some decisions were made in the end
