### ISSUE TITLE
Events for discovery of elements

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#206]
It would be good to have more avenues to gain prestige as a minor, feel that prestige actually maps to accomplishments as a great power. Like the botanical expedition and excavation events from vanilla, major elemental discoveries could be added as a period-appropriate way to do so.

**Comment by settintotrieste** [comment]
This is possible. I am also thinking of creating a unesco system as well to allow small nations to gain prestige and increase local factory throughput.

**Comment by settintotrieste** [comment]
UNESCO system has been added.

**Comment by settintotrieste** [comment]
Mod development has stopped and so all outstanding issues will be closed.
