### ISSUE TITLE
Kuril Islands dispute events problems

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#208]
Some of them reference the now-obsolete SUN tag, and other problems - in general, some review is needed.

**Comment by settintotrieste** [comment]
As far as I know this is not game breaking so this will be low priority.

**Comment by settintotrieste** [comment]
Kuril Islands dispute has been converted into a simple decision for Japan to gain cores and a one time event for RUS to decide whether to return the land or keep it.
