### ISSUE TITLE
End cultural diasporas

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#209]
Similar to Israel's aliyah events, some nations with large diaspora populations could similarly begin to call them home if certain conditions are met. I began some very basic work on this in a branch of my fork. Some ideas:

- Israel, but only if is a democracy (generic aliyah as in #113)
- Circassia
- Greater Armenia, including Mount Ararat
- Independent Crimea, but only if Tatarstan does not exist

**Comment by settintotrieste** [comment]
Faced problems with the move_pop command
