### ISSUE TITLE
Province mistakes

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#21]
Someone said:

Some of the regions seem to be a bit off. Tobolsk (in eastern Siberia), for example, is split entirely in two by Upper Yeniseysk. Furthermore, Lower Yeniseysk and North and Middle Siberia have made their way to eastern India.

**Comment by ARR8** [comment]
Furthermore, in my test run, it seems that all of the Indian states are colonial except for the capital state and Hyderabad. More testing needs to be done to see if this happens every time, but the AI does not promote bureaucrats enough to be able to make them states on its own if this happens.

**Comment by settintotrieste** [comment]
Thanks for the feedback however for now it is necessary for most of the Indian states to be colonial because India's economy will grow extremely unrealistically quickly, usually no. 2 by 1992 when they have all provinces as non colonial. A possible fix for this is to specially dramatically reduce promotion to workers for India so that the speed of industrialisation can be slowed down to more realistic levels.

**Comment by ARR8** [comment]
Ah, that makes sense. In that case, maybe Hyderabad should be addressed so that it is set to colonial after it is conquered, so it doesn't get massively industrialized and become a metropolis. I'm not sure how you would do that, maybe setting the Hyderabad tag to uncivilized? But then the war would be too unbalanced between them.

**Comment by EmperorRAG** [comment]
To make it colonial. You release it as a vassal and set it as uncivilized, then annex it.

**Comment by ARR8** [comment]
Thanks for the suggestion, @EmperorRAG

**Comment by settintotrieste** [comment]
I think there may be a problem with making Hyderabad a non colonial state. Currently as the Indian AI is incapable of creating enough bueacracy to promote other colonial states to states, only Delhi and the Kashmir and Hyderabad are states in the whole of India. Making Hyderabad a state may mess with their current economic growth pattern which allows their industrial score to reach at least 12th by 1992. So I will probably not want to put this into the mod as of now..

**Comment by ARR8** [comment]
@settintotrieste, if I understand what you're saying, then you want to keep three Indian states as non-colonial so it gets a reasonable industrial score about when it should. If that is what you mean, that makes sense, and I agree. However, I can see a couple of problems with this method:
1. It keeps India too dependent on keeping Kashmir, as one third of its potential industry. In my games, China goes to war for the whole state relatively often.
2. It creates unusual growth patterns in India, [unlike the actual ones](https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_GDP), which can mess with, for example, the Naxalite rebellion. Notice in the link that Kashmir is one of the weakest economies in India.

Instead, I would suggest looking at which three states are the most industrialized and setting them to civilized by event. Let me know if you agree and I'll have a shot at a basic event to do this. Either way, I would keep this issue open, as India can definitely be improved.

**Comment by settintotrieste** [comment]
Yes that was what I meant. I agree with the problems that you have raised and I like your solution to it, it is a very good solution. Please go ahead. Thank you!

**Comment by settintotrieste** [comment]
I have an idea on how to convert hyderabad into a colony without needing to touch the India-Hyderabad war. After Hyderabad has been annexed, India can have a one off event to create a Hyderabad puppet and then simultaneously in the same event secede_province all HYD provinces to India. This should make all hyderabad provinces colonial.

**Comment by ARR8** [comment]
There are too many problems with an event to make those states civilized. Instead, it would probably be better to set, say, Bombay and Madras/Tamil Nadu to states at the start of the game, as part of British India, and simply use events to make Hyderabad and Kashmir colonies.

**Comment by settintotrieste** [comment]
Someone said:

As well as the middle state of Java is named Upper Okhotsk. Seems strange.
