### ISSUE TITLE
Vatican City for atheist Italy

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#210]
A communist or similar Italy should not gain benefits from having the Vatican within its borders, thematically. Maybe the modifier should be removed, as though Italy reoccupied that land, and re-added should Italy return to a non-atheist form of government.

**Comment by settintotrieste** [comment]
This is difficult to script due to the way the microstate system was coded.

**Comment by settintotrieste** [comment]
I’ve decided to keep the Vatican City regardless of Italy’s situation because it’s a separate sovereign state
