### ISSUE TITLE
Prevent UN membership for certain countries

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#211]
Certain countries' UN membership was blocked for political reasons, such as Taiwan and South Vietnam. This is currently unrepresented. Perhaps countries whose capital is the core of another country, which is already a UN member and in the sphere of a security council member/the member itself, should be blocked?

**Comment by settintotrieste** [comment]
A system was made that applies only during the Cold War. Joining the UNGA is blocked unless relationship with all Security Council members are above a set amount or a Detente is ongoing. Eastern Bloc states were also allowed to join the UNGA.
