### ISSUE TITLE
Soviet-Finnish War Bug

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#22]
Someone said:

The Soviet war against Finland is hilariously broken ever since NWO,there are 2 wargoals which cannot be fulfilled together,so you lose prestige and gain militancy.

**Comment by ARR8** [comment]
This also happens for:
1. Vietnam's war with Laos
2. Soviets in the 1956 Hungarian Revolution
3. Soviets on Lithuania during the autumn of nations
4. Soviets on any lost satellite state on the dissolution of the eastern bloc

While it can make some sense to lose prestige for invading another nation, you already have consequences in the event. I would remove the "install communism" CB from these events and leave just puppet, which creates a proletarian dictatorship already.

**Comment by settintotrieste** [comment]
Sure, thanks.
