### ISSUE TITLE
Add permanent CB for unification

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#234]
I noticed, in one of my games, that North Korea declared war on South Korea over the freedom of a minor nation. North Korea correctly judged the West's weakness and won the war, but took no land for itself. Later on, after East Germany was abandoned by the USSR, Germany invaded for annexation.

In situations where it may not be desirable to add cores over the whole of a divided country, such as divided Korea or Vietnam, etc., and where current wars for unification are handled only by event, it may be a good idea to add an always-on CB for unification, that would add cores after annexation.

**Comment by settintotrieste** [comment]
If I'm not mistaken, there is already one in the mod which is the restore_order CB which becomes active when one does not have a pacifist ruling party government. The problem is that the AI often doesn't add it in existing wars as its war score is very high.
