### ISSUE TITLE
Austria-Hungary or a South German Confederation

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#237]
https://www.reddit.com/r/AskHistorians/comments/3ec82t/what_was_going_on_in_austria_during_the_cold_war/

**Comment by settintotrieste** [comment]
Not sure how to approach this. As far as I know there are cores for Bavaria so a possible unification between Bavaria and Austria is possible and an Austria union with Hungary is possible too. I'm not sure how to script this in. Perhaps just extra 2 options during the end of Austria occupation events to propose either a South German Confederation (On US side) or a Austria-Hungary (Soviet Side).

**Comment by ARR8** [comment]
I think this would be a great idea. I'll put the rewrite of Austrian occupation events on a higher priority, to make it easier to add things like this.

**Comment by settintotrieste** [comment]
Thanks
