### ISSUE TITLE
New Benelux decision does not check for Wallonia and Flanders, superstates

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#24]
Title. Also would consider adding the Benelux core for any core of the nations combining, not just owned, in case some provinces were conquered.
  Finally, it seems the event would allow forming Benelux by any nation if it were the only Benelux nation left. This could happen, for example, in case the other two were absorbed into the European/Eurasian Union, so maybe a check if their provinces are owned by the Union state first?

**Comment by ARR8** [comment]
By the way, I really like the new decisions along the lines of Benelux and Scandinavia. I'll see if I can find out about any other attempts like these in the time frame of the mod, because they add a lot of flavor.

**Comment by settintotrieste** [comment]
Thanks, more unions will be great! 

I will edit the decision such that any_country any_owned with either is_core = BEL or NET or LUX or controlled by BEL or NET or LUX or FLA or WAL will have the Benelux core added. For the second part, I will edit the potential to check if at least another Benelux member exists.
