### ISSUE TITLE
Rebel rewrite

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#244]
The entire rebel system is more-or-less nonsensical. It is a mess, with certain rebellion events simply creating rebel occupation that cannot win (see Libya, Lebanon) and other rebellions being handled by events to attempt to fix this.  
Most rebel types are left over from vanilla, which is not suited to the era at all. For example, the pan-national system is written for the creation of nation-states rather than reunification of divided states, and rebel types are dumb to anything added in the mod, other than things that affect ideology and world tensions making rebels more likely to appear (which is good, but does not go far enough).
Some problems with the rebel system were fixed through other means. Some examples are the reported bug with East Germany getting a Jacobin revolt, prompting West Germany to invade, and the frequent popular rebellion in Iraq to free Mosul never succeeding due to events taking over, even when they should win, yet happening far too often. 

I propose we work on a rewrite of the whole system with a few important things in mind:
- More rebel types. Any major historical rebellion or civil war should have all rebel types disabled but for the historical factions. For example, while India is struggling with the Naxalites, regular communist rebels should be disabled for them, and any rebel on the political right should be folded into one anti-communist group while this is happening. Countries divided should see pan-nationalists get more support from across the political spectrum - Jacobins and populists should not fire for East Germany or similar states, such types being folded into pan-nationalists until the country is united and they can splinter again. There is so much potential here - different rebel types for every ethnic group in the former Yugoslavia can enable a dynamic Balkans, instead of the bland event-based system that leads to the same outcome every game.
- Awareness of Cold War politics. Instigation by a superpower should encourage rebels sympathetic to that superpower, and the effects of superpowers actions should be felt. 
- Proper consequences. When Jacobin rebels rise up in the Islamic state and enforce their demands, ISIS should not become the Islamic republic and join the international community. Instead, the rebel system should have its own rebel type unique to ISIS to represent the resistance, and its success should completely dismantle the State. Additionally, rebels from a certain part of the population should not only desire independence for their part, or the enforcement of a certain government type. It should be possible for Syria to change between Sunni and Shia just by rebellions.
  - From #250 - nationalist rebels should destroy plurinational unions, such as Benelux or Scandinavia.
- Minimization of events. Not that events are bad, but as much as possible should be handled within the rebel system. For example, I wrote an event for the Libyan Civil War, in the event that the Islamists win. That event is completely unnecessary and could be handled as part of the enforcement of demands, possibly by a unique rebel type, or otherwise just as a consequence of that generic rebel type. In accordance with this, existing events handling rebels or rebellions, other than the prelude leading up to them, should be removed as much as possible. Events should set flags that change the logic or occurrence of certain rebellions or their types, but not occupation or militancy itself.
- Fleshed-out occupation logic. Currently, rebels simply go for whichever provinces are the most militant. In the modern era, they should go for those which are economically valuable: oil fields, cities, and industrialized areas. Currently, there are events changing militancy values during the course of rebellions. Ideally, militancy should be handled dynamically as a result of the country's economy rising/falling due to control of assets.
- Long-term effects. Areas under rebel control should devastate an area. Other than immigration from the affected area and country as a whole, rebels should destroy infrastructure and kill immigrants or those they disagree with as they march through the country, making rebellions something to recover from.

I know this is a lot, and a lot of it can possibly be contentious. However, the rebel system is a new avenue for flavor apart from events and decisions, one that's been completely untouched so far. Please let me know what you think regarding the issue as a whole or any of the specific points. If you agree, I propose we make this the main focus of 1.07, as currently a lot of the issues we are working on fixing can fall under this.

**Comment by ARR8** [comment]
Any thoughts?

**Comment by settintotrieste** [comment]
It is a good idea overall though I have a few reservations mainly with how much we can script with the rebel system. 

The first is that I am not certain if there is a way to allow for point 2 as we cannot tag rebel types to countries. The second is that there may not be sufficient commands to allow for such complex occupation logic. The last is that we need to be careful in adding new rebel types such that we don't bloat the game with too many rebel types.

But I don't mind if we push ahead on this as it can really improve the dynamism of the game.

**Comment by ARR8** [comment]
I'd like to point to the HPM rebel implementation - let me know if you need me to gist it - which creates two rebels types just for a minor conflict in Uruguay, which cannot occur outside of it, as well as several for Spain, China, Italy, etc.

**Comment by settintotrieste** [comment]
Please do, that will be great!

**Comment by ARR8** [comment]
[Here it is.](https://gist.github.com/ARR8/3a474e3aabf67d1701b78d7b20473385)

**Comment by settintotrieste** [comment]
Thanks!

**Comment by ARR8** [comment]
I've updated the file to match the newly-released HPM version. There's a minor change regarding more cultures likely supporting nationalists and the removal of the islamic law modifier that was used in a few rebel types.

**Comment by settintotrieste** [comment]
Most of these suggestions were done between 2019 to 2020
