### ISSUE TITLE
Integrating Countries into the EU removes province modifiers.

### ISSUE THREAD

**Issue by KeyboardMonkey95** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#245]
As the title says, integrating Members removes the EU related province modifiers in the provinces of the integrated nation, such as "Single Market", "Currency Union" etc.

I think one way it could be fixed is by having an event trigger when having cores without those modifiers which would add them back, similar to those for climate change or the economy focus.

**Comment by ARR8** [comment]
Thanks for the report.  
If all the modifiers are always present before integration, then an event might not even be necessary - the existing method could just add all the modifiers onto the new provinces.

**Comment by settintotrieste** [comment]
I've decided to leave the modifiers as removed as they relate to international effects of a sovereign state joining a supra-national organisation. Post annexation, those territories are no longer subject to such international benefits hence they should be removed.
