### ISSUE TITLE
Chinese Civil War bugs

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#247]
Mouzie:

Encountered a bug, when winning as the Nationalists in the Chinese Civil War, I formed a democracy instead of keeping the status quo then the Nationalists took over when the whole Chinese Civil War events fired to remove their cores and made China into a presidential dictatorship with a Nationalist government and I was like, "Okay that blows, but fine." Then the same Nationalist group 'retreated back to Taiwan' despite.. well the Nationalists were the head of government. Thus crashed my game as there was no more KMT or PRC to hand over lands to.

**Comment by ARR8** [comment]
This might as well also be the place to discuss making it possible for the AI ROC to win the civil war on its own some of the time, hopefully by the next release.

**Comment by settintotrieste** [comment]
Introduction of the Taiwan tag at the 1946 start should resolve this issue.
