### ISSUE TITLE
Possible for countries to become puppets of Scandinavia and fully join immediately?

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#25]
A possible simple delay between the two could involve lowering relations upon taking the first decision, and requiring maximum relations to take the second, since the AI would generally improve relations with puppets. Otherwise, some kind of modifier could be added.

**Comment by settintotrieste** [comment]
Thanks, the relations requirement is a good idea. I will add it.
