### ISSUE TITLE
Suggestions and improvements for The Netherlands and Benelux

### ISSUE THREAD

**Issue by DutchDylan** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#250]
I was doing a playthrough of the Netherlands in which I went on to form the Benelux, but during my playthrough I came accross various stuff which could potentially be changed for a better experience.

First of all, I noticed the implemented Benelux seems similar to the one discussed over at the [NWO mod page](https://github.com/simsulla/nwomod/issues/473). Which I think is very cool since I had a role in shaping what the Benelux would look like ingame. But during my playthrough of the Netherlands into Benelux I noticed a few things which could be changed to improve this specific part of the CWE mod.

So let's begin, when I played as the Netherlands not every party had a unique name, as well as some parties not having similar policies compared to the parties itself in the Netherlands. I gave a unique party names to every party, but since some ideologies are not as well-present in our political landscape as the others I gave them the name of a Political party which would be closest to them. 
I've done the same for the parties for Benelux union, basing them on existing parties in the Netherlands Belgium, and also Luxembourg.
As a minor thing, the ruling party in both starts should be the big tent one, since it is the one most similar to the party then leading the coalition.

The political reforms at the start also weren't totally accurate, The netherlands uses the D'Hondt for voting, which is called the Jefferson Method ingame, but First Past the Post is selected instead. During election showing up at the polling station was required but voting was not, in 1970 this was scrapped and showing up became voluntarily.
So it would be better if at the 1945 start the Netherlands has the Jefferson Method and the Support Disenfranchised selected, and has the Jefferson Method and Universal selected at the 1992 start.

Then for the map/provinces, province 380 is called 'Flevoland' but should be named 'Breda' instead. I assume this error is in place because the previous 380 was merged with 379 to create a single province and create a new empty prvince for the Flevoland province which would be the drained Zuiderzee. Which was previously implemented in the NWO mod. 
Then for the region which 380 and 379 are in, I propose for it to be named 'Brabant' since that region primarily covers the territory of what would be the province Brabant in real life.
The province of Luxembourg, 397, should be part of the Walloon region. For the country Luxembourg itself it doesn't matter which region it is part of since it's an OPM, but if forming the Benelux you would have a single province to manage for factories and stuff instead of it being part of a region with multiple provinces (that you control) which would be more practical, from a historical perspective it could also be said that Luxembourg would have been administrated as part of the Walloon region during the rule of the Kingdom of the United Netherlands.

Then there's also a somewhat major wrong population makeup of the Netherlands, most of the religious pops are catholic but this is incorrect. The north has always been protestant while the south has always been catholic, this [image](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Nederlandgodsdienst1849.PNG/800px-Nederlandgodsdienst1849.PNG) while 'outdated' shows what the division should be like.

For the Benelux itself I spotted some bugs, after forming it a new decision becomes available to form the Netherlands due to it not existing, this decision should not be available because the AI will just take it day 1. Rather it should be that if the Benelux does not own all its cores, e.g. Wallonia or Luxemburg is not part of the coutnry anymore, an event should fire to disband the Benelux back into its previous nation states (or with Flanders and Wallonia split up instead of a united Belgium). As a minor note, this event should also fire if the national party becomes the ruling party (see the name of the party in question), or perhaps also if over 50% of the population becomes of the nationalist ideology, this to present the people of the Benelux rejecting the union and wanting to revert to the previous situation.

The name of the Benelux after forming also seems to be wrong, I was a constitutional monarchy but was named 'The Benelux Kingdom' if I were an absolute monarchy. I also checked what the name of the absolute monarchy was but that was the normale one instead, so these names should be switched.
Then there's was also the effect of the Benelux getting German as an acepted culture, to prevent Luxembourg from generating crisises. But instead I would propose for Luxembourg the primary culture to be set to Wallonian. In reality the Benelux has Dutch and French as the official administrative langauges, the other minor languages like Frisian, German, and Luxembourgish are recognized but not used on that level of bureaucracy. By setting Wallonian as Luxembourgs primary culture it would simulate more correctly of it falling under the French jurisdiction of the Benelux. Simultaneously it would also prevent the player from gobbling up German land since the pops would not revolt due to them being an accepted culture. If Luxembourg becomes independent it would have an event fire to reset the primary culture.

For if the Benelux forms, it would be nice to have two events fire, preferabbly triggered by enacting the decision to form the Benelux itself. 
One to decide where the capital should be, in Amsterdam, Brussels, or Luxembourg City.
And one to decide what to do with the monarchy, there should be an option to leave the various monarchies out of the Benelux government, thus making it a republic. Or to keep the monarchy, which would fire a second event for the player to decide which monarchy to keep. The first option should have the effect of increasing militancy for certain ideologies (conservative, tradionalist), and lowering of others (progressive, communist). While the other should increase the militancy of the specific culture of which the monarchy was not choosen (choose Dutch Monarch, anger Flemish, Walloon, German/French pops).

Then lastly the minor things.
-The Benelux communist flag was kind of weird and stretched and included text of a sepcific group, so I replaced it with a clean red text-less flag which includes the logo of a communist youth group. Personally I thought it looked cleaner and cooler that way.
-The colours for the government types for the Benelux were changed, I personally disliked how the yellow looked and made it to similar to Spain, I changed the default colour to be orange which is darker than the Netherlands colour, but not too similar to the coutnry colour of Poland.
-The decision for 'Houtribdijk' has no requirements for techs but only money, I propose for it to have the requirement of having researched the second tech in the first row of the naval tech. To be specific, the Artificial Island tech under the Naval Bases and Ballistics row, you could probably guess from the etch thumbnail why I choose that tech. 
Perhaps it should also require the Interstate Highway System tech from the Infrastructure row under industry (4th tech, 4th row, industry), since the Houtribdijk provides the ability of driving accros the former Zuiderzee to the province on the other side of the water, which is infrastucture/highway.
-The Netherlands starts off with no transport ships, if it can't produce any ships due to another country waging a war and consuming the needed supplies first, you're basically fucked. It would probably be better if the Netherlands started off with a couple of transport ships so you would be able to bring troops over to Indonesia to fight and occupy stuff.
-There should be a general superstate formation cooldown, with this I mean after you form a superstate you should get a modifier which disables decisions related to superstate for 5-10 years. I got this idea from a playthrough of South Africa into the new South Afrcia union, because after forming it I could immediatly enact all decisions to form the African Union. 
This would be in a way realistic, because in the Beneluxs case why should this newly formed superstate adopt the Euro so soon after it had adapted its own new currency immediatly, and just after it has created this Beneluxian untiy/culture why woudl it strive for a European one?
-The formation of the Benelux should only be allowed if all three countries have EU ambitions (or trade block ambition), but haven't joined the European single market yet. This is to simulate that the countries are on their path to the Benelux superstate, and not on their path to the EU superstate. And this would also make it impossible to join the Benelux later in the game in which it would be more unrealistic to do so. This since in real life co-operation between the Benelux countries shifted to European level co-operation when the EU catched up with how far the Benelux was in co-operation.
-If the cold war goes hot before the EU has formed, the Benelux union should form (if none of the three are not aligned with the west or are communist dictatorships) so it could acts one military entity.
-If a great communist power like the Soviet Union or the Chinese People's republic has sphered all the three low countries and all three of them are communist dictatorships already, then there should be the possibility for that great power to unite the three through a decision. This should only be the case for extremist dictatorships and not for democracies and the like.
-Make Belgium and the Netherlands start of with higher influence than the avergae GP at the start of the game in Luxembourg, this due to the already establishded basic co-operation between the three countries. The coutnry can remain in the US sphere just fine otherwise,

As stated before here's the political party names for in the 'NWO_parties.csv', but they are implemented in the file included in the file at the end.
Dutch political party names:
party_conservative_0_NET;Christian Union;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;
party_progressive_0_NET;Democrats 66;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;
party_populist_0_NET;PVV;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;
party_socialist_0_NET;PvdA;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;
party_communist_0_NET;Socialist Party;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;
party_traditionalist_0_NET;SGP;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;
party_liberal_0_NET;VVD;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;
party_big_tent_0_NET;Christian Democratic Appeal;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;
party_nationalist_0_NET;Forum for Democracy;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;
party_communist_social_0_NET;Green Left;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;

Benelux political party names:
party_conservative_0_BNL;Christian Conservatives;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;
party_progressive_0_BNL;Democractic Progress Party;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;
party_populist_0_BNL;People's Party for Freedom;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;
party_socialist_0_BNL;The Socialist Alternative;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;
party_communist_0_BNL;Union of Workers;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;
party_traditionalist_0_BNL;Desecularization Movement;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;
party_liberal_0_BNL;Liberal Democratic Party;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;
party_big_tent_0_BNL;Beneluxian Democratic Centrum;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;
party_nationalist_0_BNL;Initiative for Democratic Secession;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;
party_communist_social_0_BNL;Environmental Awareness Party;;;;;;;;;;;;;x;;;;;;;;;;;;;;;;

Here's a [zip with the files](http://puu.sh/wMcMe.zip) which I had already personally modified for my own playthrough which could be used as a basis.

**Comment by ARR8** [comment]
Great suggestions, and thank you for the contribution, it is highly appreciated! I think these are great party names, which I see no reason not to implement with one minor change (removing the word "Beneluxian" from the moderate party).

Thanks for the ruling parties, starting reforms, and localization, and other contributions too!

I think Luxembourg is part of the Rhineland in Vic2 because of the possibility of joining Germany. Since this cannot happen in the mod, and it would far more likely join Benelux, it definitely makes more sense in Wallonia.

The decision should definitely be patched.  
It's not inconceivable that a Benelux which loses many of its cores may seek to reconquer rather than immediately split up, especially if it happened in response to an outside invasion. However, you are right that an event for splitting up the Benelux, especially including Flanders and Wallonia, at some point with reasonable triggers is needed, and thank you for your suggestions.  

Good point about German states - however, I'm not sure how much the primary culture should change, as it is always (technically) possible to form Benelux as Luxembourg.

More flavor events are always nice, however, these would be lower priority as abolishing the monarchy is implemented as a generic decision, and the capital would remain as the capital for the forming nation, much like superstates.
  It may be faster to add these if you can help out in writing the flavor text, if you were so inclined.

Concerning the pops: sadly, most of the pops in the mod are inaccurate, see #133. It's a long-term goal to get them all fixed, but we simply don't know enough about every region and their demographics, not to mention problems caused by the chaos in the aftermath of WW2, as well as the lack of a reliable census for many regions.

Regarding the suggestions for superstates, would you mind putting those in a separate issue? And creating that window for the formation of Benelux also makes sense, account for the possibility of Eurasia rather than the EU.

**Comment by DutchDylan** [comment]
I can agree with that, I used Beneluxian since the (Belgian) party I based it on used humanitarian but I thought it woudl be a better fit, but Democratic Centrum (Party) should be fine.

It isn't fully fixed, the only thing I wasn't able to fix was the voting rights (mandatory voting), so someone should take a look at that.

Yeah makes sense for that to be the case in vanilla vic2, it could still join Germany through the EU but the remaining low countries would most likely also be apart of the EU then.

The cases in which the Benelux splits up could only have three causes:

-If rebels enforce independent demands
Since the Benelux would be built upon a democratic unification (let's assume that this is only triggered if the Benelux is a democratic government), then disbanding of the union is in order. If the benelux was a dictatorship it should just try to reconquer them.

-Hostile nation takes Benelux cores
Probably shouldn't disband the Benelux, but the earlier mentioned outcome could be prevented by checking for lost a war in recent years or something? If over years the Benelux is unable to take its cores, it should disband.

-Higher levels of autonomy in the Benelux
This is for the future, but it could be that regions within the Benelux would like higher autonomy, for example the Walloon region or Luxembourg wanting greater autonomy due to their language being a minority. Then they would become puppets (and perhaps that administrative government type?), and so it should be checked if the Benelux cores are owned through puppets.

Forming the Benelux as Luxembourg is technically possible, but the formation of the Benelux could be easily counter the culture problem. Since a superstate earns their cultures over from their forming country, after teh tag has been switched, it should set Dutch as primary while adding Felmish and Walloon as accepted, and removing Germand and French. Then it adds Wallon as primary culture for Luxembourg.

While the monarchy is flavour, it's also the events that fire for the three low countries that get disabled by forming the Benelux. The monarch flavour decision would be there for the game to know which events should fire for the Benelux, but for now it's definitely low priority. And yeah the capital change is purely flavour with no real game mechanics reasoning behind it.

Ah I see, I just checked my NWO game and the pops seems to be wrong in there too, I don't know any reliable source with popualtion figures, but reverting the northern pops to protestant could just be fine for now. But at the same time maybe it's better to do a mega pop overhaul in which this woudl be included.

And yeah I will do.
I will write some text for the specified events and make them, any prefernece how I should submit the work when its done?

btw I added/edited two minor issues around the time you posted your reply, could you check those too?

**Comment by ARR8** [comment]
I'll leave Beneluxian in if you say it's based on a real party.

Noted, noted, noted. Currently the primary culture is never changed by forming Benelux, so a Luxembourg-formed BNL can theoretically begin eating Germany, but so can great power Luxembourg, so I'm not too worried.

If you know git at all, you can fork the repository on GitHub and submit a pull request. Otherwise, what you did above works fine.

Yes, I've added those.

**Comment by ARR8** [comment]
Also, in addition to the parties you've already added, if you want to add any historical parties, parties changing over time, parties for certain timespans, etc., you're more than welcome to! As long as there is only one party for any ideology at any given time, to avoid the Vic2 election bug.

Thanks a lot, overall! This has been a great help, and is exactly the kind of thing we're looking for contributions for. Please don't hesitate to post any other ideas you get or problems you notice with anything you're familiar with.

**Comment by DutchDylan** [comment]
Is the bug you're talking about that parties get twice the votes if there's two parties representing that ideology? Could that theoretically be fixed by having two for each, to balance it out so to say.

**Comment by ARR8** [comment]
Maybe, but it might be a challenge to come up with, say, two separate market communist parties. In non-communist countries, there's usually only a general communist one. In fact, I'm a little surprised you managed to find some to add.

**Comment by DutchDylan** [comment]
Myeah the names currently used might not be super correct, but at the same time those parties existing back in 1945 isn't either. I picked the one most closest to that ideology (even if they might be far off), it's just for the player to feel more immersed when playing as that country since the parties are not generic and do exist irl.

**Comment by DutchDylan** [comment]
Hey @ARR8, previously you said:
"Also, in addition to the parties you've already added, if you want to add any historical parties, parties changing over time, parties for certain timespans, etc., you're more than welcome to! As long as there is only one party for any ideology at any given time, to avoid the Vic2 election bug." 

If historically no party was representing a specific ideology, should that be reflected in-game for there to be no party available for that ideology, or should there be a party made up (based on older or newer parties which did reflect that ideology)?

Specifically for the Netherlands I was working on implementing historical parties, but for the progressive, populist, and nationalist ideology there lack political parties early on (before the 60's for progressive, and 70's for nationalist/populist). 

On a minor note, is there any way to change starting ideologies of the populace? The left/socialist party seems to get more votes than historically was the case, so I would like to tweak that a bit.

**Comment by ARR8** [comment]
You can extend the first party back or add a "wing" of a party that did exist, but do try to make sure that a party exists for any given ideology.

Not sure about starting ideology.

One more note: in the history files, all countries should start with secularism as the state religion, unless it starts with a moralist party in power; in that care, it should also start with a "desecularized" flag.

**Comment by DutchDylan** [comment]
Ah I see, how do I add a desecularized flag to the Netherlands? 
I changed it to have them start with Protestant since the country was pretty religious until the 60's (de-pillarisation), and checked with other religious countries how such a flag would be implemented but I couldn't find anything. 

Countries like Egypt Saudi Arabia and Iran started with secularized as a state religion while their party in charge has moralism from the start, should I have the Netherlands start with Secularized as well and add the flag "desecularized" somewhere else?

**Comment by ARR8** [comment]
No, that's, right, none of them have it yet, it's a long-term goal. You can leave the religion as long as you add the flag to the country history at 1946. I think some countries in vanilla and HPM have flags set at the start, if you need an example; it's a one-line addition to the history file.
