### ISSUE TITLE
Starting naval changes

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#251]
Many countries, such as the UK, start the game over the naval limit, and some colonial empires, such as France and the Netherlands (see #250) start with no transports.

**Comment by settintotrieste** [comment]
Not having transports at the start is intentional for France and the Netherlands to prevent them from winning the Indochina and Indonesian wars all the time.

**Comment by ARR8** [comment]
Hm, that makes sense, but it should also be possible for a player to win the war.

Maybe give them transports somewhere out in the colonies, but make the war heavily skewed in the colonial nation's favor. For example, occupying any Dutch Indies province for long enough will make it defect to Indonesia, and the war automatically ends if the Netherlands loses enough ports, for example.

**Comment by settintotrieste** [comment]
I don't think it would be necessary to script that as there is a means for the player and AI to acquire transports by mobilising the merchant marine.

**Comment by settintotrieste** [comment]
Starting naval compositions in 1946 and 1950 were redone in mid 2020
