### ISSUE TITLE
Superstate-into-superstate prevention/cooldown

### ISSUE THREAD

**Issue by DutchDylan** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#253]
#250 
When forming a superstate you can immediatly start working on forming the next one, which is not realistic so to say.
For example when forming the Benelux there's no reason to immediatly adopt the Euro and ect after, there should be a cooldown (5-10 years). 
Similarly, when I played South Africa I formed the South African Union but the decisions for forming the African Union were all available to me. 

Perhaps to extend on this, should there be cooldowns on seperate superstate decisions too? So that a country has to wait, let's say a couple of months, before it can enact the next step. This might be overkill but I'm just throwing it out for the others to hear.

**Comment by settintotrieste** [comment]
The cooldown decision would be too difficult to implement as all chains will have to be redone
