### ISSUE TITLE
 Global materialism results in violating conservation of mass

### ISSUE THREAD

**Issue by AceSevenFive** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#255]
So, on my current CWE game as Canada, in the year 2025 it seems that my population demands so much canned food that my government is buying negative millions of it, which is now breaking my economy (and the game, since it's crashing a bit now.)

If needed I can provide my save file in a few hours.

**Comment by settintotrieste** [comment]
I see, please send a copy of your savegame so I can analyse the cause of the problem.

**Comment by AceSevenFive** [comment]
Here you go. https://www.dropbox.com/s/rih493b63ok8yae/Canada2025_09_06.v2?dl=0

**Comment by settintotrieste** [comment]
Thanks

**Comment by settintotrieste** [comment]
Unfortunately I am not able to find the cause of the crash.

**Comment by settintotrieste** [comment]
No more reports of this. Issue closed
