### ISSUE TITLE
Assimilation rate in the EU

### ISSUE THREAD

**Issue by KeyboardMonkey95** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#258]
In my EU campaign, after forming it in 2020 and integrating most of Europe immediately and the rest of it by 2035, i got to 2050 with only ~20% of the population of European culture, with most of them concentrated in a few provinces and in Italy (the Nation i started with).

This caused a couple of problems:

1. Low Administrative Efficiency: Throughout the 30 years as the EU the National Efficiency was at around 20/25% at all times.

2. Few pops to draw from to make high quality troops: Almost all of my soldier pops where of their original culture such as Russian, German, English etc. which didn't allow me to recruit them as the better units, but only simple Infantry. I was only able to recruit ~80 European brigades while having a force limit of ~800.

**Comment by settintotrieste** [comment]
This could be due to the peculiarity of how the assimilation system works which causes non accepted to assimilate into the primary culture if there is the primary culture in the province or they will just assimilate into the accepted culture. This causes the problem you observed.

**Comment by makotech222** [comment]
Is there any way to get assimilation to work even when there are no primary culture people in the province? I have a cheat that takes away all cores from conquered provinces and adds Player's core, which helps quite a bit. Maybe there's a way to get people to migrate to conquered provinces more often?

**Comment by settintotrieste** [comment]
if they are no primary culture pop present in a province, the unaccepted pops will assimilate into any accepted cultures present in the province. If there are no accepted or primary pops then there will be no integration.

Currently there is a mechanic added to allow coring of lands but it takes many decades for the cores to appear.

A recent change made to pop migration mechanics mean that selecting rural focus encourages the migration of primary and accepted pops to rural provinces. This helps to provide the necessary pops for assimilation to occur.

Assimilation boosts have also been added to superstates allowing them to promote accepted culture pops much faster.
