### ISSUE TITLE
Polish cores event at start of game

### ISSUE THREAD

**Issue by DutchDylan** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#261]
Event 822400 gives Poland cores on its historical eastern region, but there's no event/decision renouncing those cores later on. The event fires near the start of the game, but in this [wikipedia article](https://en.wikipedia.org/wiki/Polish%E2%80%93Soviet_border_agreement_of_August_1945) it states that Poland soon after the end of WW2 agreed on its current borders.

It seems relatively useless for that event to fire if the cores should historically be taken away in a year again, any reason why that specific event seems to be lacking (all my games Poland keeps cores on these provicnes), or why these provicnes don't start out with Polishc corres?

Perhaps it would be better if the province files were edited to include polish cores from the start on these provinces (and perhaps the lack of in the western provinces), and the event would instead be the histoircal Polish renouncement of these cores. Wtih perhaps a second option for a player if they wish to not renounce the cores and fight the SU, but that's probably overkill.
Alternatively the initial event could still fire, and the removal of the cores could happen inside the SU decision for the Polish population transfer.

**Comment by settintotrieste** [comment]
This is an event inherited from NWO. 

Putting the cores in from the beginning is too difficult for me to do so as I will need to manually edit each and every affected province file to add the cores so to be time effective, I will create another event that will revert event 822400's effects.

**Comment by DutchDylan** [comment]
Sure, sounds good.
