### ISSUE TITLE
Libyan Civil War

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#265]
I propose to make possible the disintegration of Libya. I think it's necessary to add different groups in Libya - the Council of Deputies, the Government of National Accord, the National Salvation Government, the Shura Councils of Benghazi, Derna and Ajdabiya, the Petroleum Facilities Guard, Tuareg forces.

Or as been added in the latest version of NWO mod cores. (I don't remember names of them)

**Comment by settintotrieste** [comment]
I'm not sure if I should add in cores for Libyan opposition parties as they are not really a nationality. I will probably add cores along cultural lines.

**Comment by settintotrieste** [comment]
https://en.m.wikipedia.org/wiki/File:Map_of_traditional_provinces_of_Libye-en.svg

This will be the proposed break up of Libya.
