### ISSUE TITLE
Italian separatist States political parties

### ISSUE THREAD

**Issue by KeyboardMonkey95** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#267]
I'm looking into giving each Italian Minor their own set of political parties, but i'm having trouble finding enough of them to fill the political spectrum, mostly because a significant part of their politics was occupied by the national parties.

So i was wondering if it would be acceptable to use Italy's parties as a base and add or substitute them (where possible) with the State's own parties.

Otherwise i would have to create generic parties for most ideologies.

**Comment by settintotrieste** [comment]
Yes that will be alright. I would advise against adding the new parties to the current roster of parties for ITA as it will cause an election bug. If you want, you will have to add the parties to the respective separatist country.

**Comment by KeyboardMonkey95** [comment]
Of course, i meant to add the minor's party only to the separatists states, not to Italy. 

At the same time i'm doing a rework on the Italian parties as well to avoid multiple parties of the same ideology existing at the same time, which i assume is the problem you want to avoid?

**Comment by settintotrieste** [comment]
That's good. 

Yes
