### ISSUE TITLE
The Soviet Union and its lack of cores on the Soviet Republics

### ISSUE THREAD

**Issue by DutchDylan** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#268]
In-game the Soviet Union is portrayed as Russia with the Communist dictatorship government form, but it only has cores on the Russian Soviet Republci within. This causes some problems due to the core integration event firing for a couple of regions bordering its cores which increases the countries infamy and in some cases makes it go over the infamy cap.

Besides the ingame problems, [internationally the republics of the Soviet Union were recognized as part of the Soviet Union](https://en.wikipedia.org/wiki/Republics_of_the_Soviet_Union) [excluding the three Baltic States of Estonia, Latvia, Lithuania](http://puu.sh/x5HGc.png).

Wouldn't it be better for the Soviet Union to start out with cores on its recognized Soviet republics, and when the Union collapses/disbands that the cores on non-Russian terroitory be removed? Currently there already seems to be an event giving independence to the republics after a fall of the Union, [but any cores Russia had on them stay](http://puu.sh/x5HTy.jpg) which result in weird reconquest wars.

**Comment by settintotrieste** [comment]
I agree, The USSR should have cores on union territory in the beginning and only removed after the fall of the USSR.
