### ISSUE TITLE
China's bugs

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#270]
Hello. In the game, usually, China somewhere by the late 1990s begins to receive the sphere of influence everywhere - Spain, Bulgaria, Kyrgyzstan, Uzbekistan, Georgia, Romania, etc ...

Also, by 1996, the crisis in Inner Mongolia begins because of what the Third World War begins. (I solved this problem by making the Mongolian an acceptable nation in China)

**Comment by settintotrieste** [comment]
Mongolian added as an accepted culture in China. Chinese sphere expansion is due to the bipolar world mechanic which is a feature and not a bug.
