### ISSUE TITLE
Chemical Weapons Decision Bug

### ISSUE THREAD

**Issue by DutchDylan** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#274]
The chemical weapons decision can be taken (as a player) while not having enough money, resulting in going bankrupt after having taken the decision.

I'm not sure if there's a 0 missing checking for the required money (checking for 50k instead of 500k), or the money requirements is invalid if the country is not an AI.

**Comment by settintotrieste** [comment]
This is intentional. The AI is programmed to never take the decision if there is insufficient money but the player can still do it if they are willing to be bankrupt in exchange. A real life example of this is North Korea which spends itself to bankruptcy on WMDs.

**Comment by DutchDylan** [comment]
Ah I see.
Sorry for the late reaction, but could there perhaps be indication for the player that they will bankrupt when taking the decision? From experience I know I will bankrupt, but if you look over the decision it seems like the money you need is the same as is taking from enacting the decision.

**Comment by settintotrieste** [comment]
I believe that there is no need to as it is quite self explanatory that if the decision costs more money than what the player has then you will default and enter bankruptcy.

**Comment by DutchDylan** [comment]
Yeah that's true, it's just there's only a '0' difference in money, and with a quick glance it would seem like it's the same amount.
