### ISSUE TITLE
The possibility of civil war in Syria

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#279]
I propose to add the possibility of a civil war in Syria. I mean, it would be possible to make a kind of "Syrian Republic" and "Syria" and under certain conditions a civil war begins in which the Syrian Republic and Syria respectively take part.

**Comment by settintotrieste** [comment]
The Syrian civil war is already represented in the game. The events can be found in syrian_civil_war.txt in events.
