### ISSUE TITLE
Possibility of the dissolution of Russia

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#280]
Hello. I propose to add core provinces for the Urals Republic. It existed from July 1, 1993 to November 9, 1993. Also, I propose to add the possibility of separation for other subjects of the Russian Federation. In particular, in Siberia.

I also suggest adding more core provinces for the Far Eastern Republic in the Far East.

Or if you want there, you can also create a Republic's like the Ural Republic.

(There is no wiki about the Far Eastern Republic, But the Russian Far Eastern elites offered to recreate the Far Eastern Republic within the framework of the subject of the Russian Federation in 1996.)

(wiki about Ural Republic - https://en.wikipedia.org/wiki/Ural_Republic)

**Comment by settintotrieste** [comment]
These states were added in an update late 2020
