### ISSUE TITLE
No Bureaucrats?

### ISSUE THREAD

**Issue by ckanbak** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#284]
Hello, while playing Turkey I realized that it starts with 0 bureaucrats (which, if you ask me weird in itself) and more importantly, that unless I'm actively promoting in a state, no new bureaucrats are being promoted. Is this intended, or is there a bug there somewhere?

**Comment by settintotrieste** [comment]
Is this using the latest GitHub version?

**Comment by ckanbak** [comment]
No, it is using the last release.

**Comment by settintotrieste** [comment]
I will investigate this.
