### ISSUE TITLE
Syrian Civil War and Possibilities of the collapse of Syria

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#286]
I propose to add core provinces for the groups Ahrar al-Sham and Hayat-Tahrir Al-Sham in Syria. (As part of the possibility of Collapse of Syria and Civil War.)
In Aleppo and Hama.

For example like Alawite and Druze states.

Links:
Ahrar al-Sham - https://en.wikipedia.org/wiki/Ahrar_al-Sham
Tahrir al-Sham - https://en.wikipedia.org/wiki/Tahrir_al-Sham

**Comment by settintotrieste** [comment]
Alawite and Druze states were added in mid 2017
