### ISSUE TITLE
A fix for nationalists

### ISSUE THREAD

**Issue by peacequiet** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#287]
Some changes to nationalists for post-colonial states.

1. Primary and accepted cultures now have -300% nationalist attraction if the government is not a sectarian regime. It doesn't really make sense for accepted cultures to be nationalistic if they're integrated into the national consciousness, so passing the "Nation of Equals" acts will now make your country noticeably stronger. 

2. Nationalists no longer gain support for having high militancy if they are in power. High militancy means people are angry at the government, this should not help nationalists if they are in power. 

What these changes do is they make it so that postcolonial nations that make an effort to incorporate all of their minorities will have a much easier time than those who reject their minorities (as makes sense.) For the first few years after independence there is high nationalism (simulating people's pride in their country after independence,) but after that honeymoon period nationalism stops being relevant to a nation's politics. I think it makes a good compromise, and it stops countries like Nigeria from collapsing to unending rebel stacks.

Here are the files as I can't figure out how to get the pull requests to work. 

[slaves.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1293932/slaves.txt)
[soldiers.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1293928/soldiers.txt)
[aristocrats.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1293930/aristocrats.txt)
[artisans.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1293931/artisans.txt)
[bureaucrats.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1293933/bureaucrats.txt)
[capitalists.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1293929/capitalists.txt)
[clergymen.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1293935/clergymen.txt)
[clerks.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1293934/clerks.txt)
[craftsmen.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1293937/craftsmen.txt)
[farmers.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1293936/farmers.txt)
[labourers.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1293938/labourers.txt)
[officers.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1293939/officers.txt)

**Comment by settintotrieste** [comment]
Thank you very much! I will add your fix to the mod.

**Comment by DutchDylan** [comment]
Are you sure about your first point? Looking at the Golden Dawn and the National Democratic Party as political parties in Greece and Germancy, it does seem that people of the national culture/identity can be attracted to the national ideology.

**Comment by peacequiet** [comment]
The idea is that populists come and take the role of Nationalists as the game goes on.
