### ISSUE TITLE
Define terrorists as "Freedom Fighters" decision *(Redone)

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#288]
Hello. I want to propose to change this decision.

Define terrorists as "Freedom Fighters". I propose: To make such a decision it will not be necessary to be a Theocratic State. 
To make this decision: You should have a Traditionalist Party in power and be a Secondary or Great Power.
Then not only Iran will be able to make this decision, but Saudi Arabia and Turkey, too.

I also do not quite understand what Defend Terrorists as "Freedom Fighters" is doing. Please explain.

**Comment by settintotrieste** [comment]
Freedom fighters means that the nation supports the action of the terrorists.

**Comment by samwoodzadrot** [comment]
I understand this. I do not understand what this decision is doing. That is if I took this decision then what happens?

**Comment by settintotrieste** [comment]
It decreases the frequency of terrorist attacks.

**Comment by settintotrieste** [comment]
I am thinking of making the freedom fighters decision to prerequisite to allowing GPs and SPs nations to start supporting terrorism.

**Comment by samwoodzadrot** [comment]
It would be great!
