### ISSUE TITLE
Crash when clicking decisions as the UK at the start of the game

### ISSUE THREAD

**Issue by peacequiet** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#290]
Similar to the province crash, no errors besides the normal Windows CTD. I tried trawling through the mod with the Validator tool but nothing stood out to me.

**Comment by settintotrieste** [comment]
Is this using the latest version of the mod?

**Comment by settintotrieste** [comment]
Have you tried deleting the CWE folder in documents? Sometimes it does help to stabilise the mod.

**Comment by peacequiet** [comment]
The deleting whole CWE folder might help? I'll try that when I get the chance. Before I had been clearing the map cache only.

**Comment by settintotrieste** [comment]
I've done some testing and I have not been able to replicate the crash so I will close this issue.
