### ISSUE TITLE
Genocide enhancement

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#292]
Do you plan to ever rework the Ethnic Cleansing decision?

It does way too little for too much infamy, at least in most contexts. Therefore I feel that either the infamy penalty should be lower (but other countries could get a "World Police" event to stop you from doing it) or it should be way more effective.

I realize that game-limitations are the biggest reason for this, as well as the fact that you can't target specific cultures.

But I think that the main problem here is that you only have one real way of getting rid of unwanted minorities, other than the passive assimilation which for immersive purposes might not be a good choice sometimes. It's also hard to actually replace the population of that province, as those pops will grown back again, they'll maybe even have faster growth than the native, meaning that you'd have to use the ethnic cleansing decision many times before achieving you goal.

Therefore I think that genocide/ethnic cleansing should have a submenu of its own where you can choose different kinds of minority removal. I have a few suggestions, but I don't know how possible it is to practically implement them:

1. Genocide all unaccepted pops. Gives a lot of infamy (30?) and is pretty effective all across (60-80% removal)
2. Genocide based on religion. Would also give a lot of infamy, but is even more effective as it has a specific target. You could probably borrow this system from HPM, as it works pretty well.
3. Deport foreigners. It could be used as a more humane way and given to government types that normally can't genocide. It should give less infamy (10-15), but only remove 20-30% of unaccepted pops. It should also move these pops somewhere else, if that's possible within the game's engine.

There's probably more to add there, but it's just a starting idea. Countries could also have specific genocide decision and events for their own context. You maybe already have this in the game, I'm not sure.

Genocide as such is a pretty crazy thing, naturally, but it's also something very real and pretty frequent if we count all kinds of population removal. It therefore needs representation in a game or mod like this.

**Comment by Devin616** [comment]
i also think that a "china method" should be an option too, that is; reeducation camps and prisons to change the way people think and force them to become your culture without killing very many of them.

**Comment by settintotrieste** [comment]
This feature has been redone in 1.10 to follow HPM’s new system.
