### ISSUE TITLE
Idlib province in Syria

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#293]
Hello. I suggest adding the Idlib province to Syria. It will create a more realistic situation in the civil war in Syria.

Links: https://en.wikipedia.org/wiki/Idlib_Governorate https://upload.wikimedia.org/wikipedia/commons/f/f8/Idlib_in_Syria_%28%2BGolan_hatched%29.svg

**Comment by settintotrieste** [comment]
I have no experience in creating new provinces so I will need assistance to implement this.

**Comment by samwoodzadrot** [comment]
Actually I think, I could help.

**Comment by settintotrieste** [comment]
Mod development has stopped and so all outstanding issues will be closed.
