### ISSUE TITLE
The Istrian question

### ISSUE THREAD

**Issue by Teitali** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#296]
The game starts in 1946 and in this year in the provinces of Pola and Rijeka/Fiume the Italians were more than 6% in the first one, and 0% in the latter. Actually, immediately afterwards WWII, the italians were the majority of the population of Pola and a large group in Fiume. This is because the destiny of Istria was undecided until 1947, the year were the Italian exodus occurred. The decision of the Free Territory of Trieste was taken only in the middle of that year, but the possibilities were much more.  This was the solution proposed by the French. The Americans also pressed for an annexation of Pola by Italy. It would be nice if there were more decisions and with these decide the fate of the Italians in the region

**Comment by settintotrieste** [comment]
Mod development has stopped and so all outstanding issues will be closed.
