### ISSUE TITLE
Nwo map

### ISSUE THREAD

**Issue by DullishCrab94** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#297]
Are you going to use the new nwo map and are you going to add the provinces from nwo if you do i would love it

**Comment by settintotrieste** [comment]
I will not be using the NWO map and provinces. They are too flawed.

**Comment by DullishCrab94** [comment]
could you fix Transnistria,Chechnya and Baikonar

**Comment by settintotrieste** [comment]
Yes, eventually when I figure out how to mod borders.
