### ISSUE TITLE
Great Powers Always Losing Money

### ISSUE THREAD

**Issue by DullishCrab94** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#299]
No sorry if i am spamming but in a game i played as the Netherlands and the United Kingdom both in 1946 i noticed i could not get positive money i also saw this with France but not as bad is there a way you maybe fix this for great powers

**Comment by settintotrieste** [comment]
This is common in the early 2-3 years as the economy is not developed yet. After 2-3 years you will start making money much easier.

**Comment by DullishCrab94** [comment]
Do i need to research anything in commerce or will it just fix its self in 2 to 3 years

**Comment by settintotrieste** [comment]
It should fix itself by 1949. But you can research tax efficiency techs first if you wish to have less deficit in the early years.

**Comment by DullishCrab94** [comment]
Ok thank you

**Comment by DullishCrab94** [comment]
oh and will this same thing work for small nations like laos,Bulgaria,Afganistan,Denmark etc
