### ISSUE TITLE
Regime recognition broken for Soviets

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#3]
Playing as the Soviet Union with rank 1, the event demanding recognition for regimes gives you a casus belli to install democracy, which you cannot use. It also fires for communist dictatorships, even your own puppets, which presumably have recognition.
Possible fix: limit the event to the nation with leader of the democratic bloc modifier? Alternatively, give the install communism cb, and prevent it from firing for communists if the Soviets are the first-ranked power.

Also, the scope seems to be wrong, as it gives you the cb on yourself. I am unsure if this would also affect America, but I think so.

Choosing to recognize the regime still lowers relations with them.

Finally, the event doesn't fire for the new proletarian_dictatorship1 government. I don't know if this is intended, but that may be something to fix, as well.

**Comment by settintotrieste** [comment]
May I know if you are using the lastest GitHub version though? I did some fixes to the sphering regime change events a day ago.

**Comment by ARR8** [comment]
No, I should have specified. I'm using the latest release.

**Comment by settintotrieste** [comment]
Thanks, I will take a look at the events again.

**Comment by ARR8** [comment]
Sure. The file I have the events in is cold_war.txt № 19802 and 19803 - I'm not sure if this is related to regime change, since it seems to be a MTTH event.

**Comment by settintotrieste** [comment]
Thank you, I will investigate those events.
