### ISSUE TITLE
File not found?

### ISSUE THREAD

**Issue by william4916** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#300]
File exception:
Exception in: discfile.cpp, line 83. Description: Could not open file:
map/../mod/CWE/map/definition.csv

This is what I get while the game starts to load and then all the it justs say that out of no where.

**Comment by settintotrieste** [comment]
You have to download the GitHub version and completely replace the CWE folder and CWE.mod file in programs with the CWE folder and CWE.mod file from the GitHub download.
