### ISSUE TITLE
Negative tax efficiency

### ISSUE THREAD

**Issue by ZombieFreak115** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#302]
I ended up with negative tax efficiency while I was playing as PRC. After Jacobins overthrew the government and made it a republic, I got negative tax efficiency. I'm not entirely sure of the cause of this, but my guess is modifiers increasing tax efficiency disappearing when the regime changed. but wasn't reapplied. Although straight after the regime change the tax eff. was still low (0.9 percent) but it only got to negative levels a few months after the change.
Here is a screencap:
![20171021213254_1](https://user-images.githubusercontent.com/32988549/31855398-d66e3bda-b6aa-11e7-952f-f59802c00f7d.jpg)

**Comment by settintotrieste** [comment]
You have to research more tax efficiency increasing techs and select decisions that increase tax efficiency.

**Comment by ZombieFreak115** [comment]
I get that, but surely 0 percent tax eff. shoud be minimum, negative tax eff. just doesn't make sense.

**Comment by settintotrieste** [comment]
Yes but due to a game engine design flaw where tax efficiency can decrease below 0% there will be a possiblilty where tax efficiency will be negative when you select too many tax efficiency reducing decisions and researched insufficient tax techs.
