### ISSUE TITLE
A couple of bugs with decisions

### ISSUE THREAD

**Issue by elemento136** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#304]
It appears that there are some mix-ups with the election strategy and multinational corporation decisions.

As it currently stands, AI centrist parties are choosing an equality election strategy while AI leftist parties are choosing a meritocracy election strategy. This can be fixed by swapping around the AI requirements relating to elchigh and elcmedium found in Election Strategy.txt.

The effects for favorable multinational corporation stance and unfavorable stance are mixed up. This can be fixed by swapping the effects mnchigh and mnclow modifiers in event_modifiers.txt.

**Comment by settintotrieste** [comment]
There is no mix up in the MNC policy effects.

**Comment by elemento136** [comment]
Ah, you're right.  I should have taken a closer look into MNC files. The policy effects are consistent with the AI decision-making, but not with the accompanying decision picture and flavor text. Either the policy effects and AI requirements should be switched or the accompanying localization and decision pictures should be instead.

**Comment by settintotrieste** [comment]
Fixed
