### ISSUE TITLE
Installation friendly democratic regime Casus Belli for Turkey

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#305]
Hello. I suggest adding Turkey a CB for installation a friendly democratic regime. I'm sorry if it already possible, I wasn't playing for a long time.

Why?
Because Turkey supported for a revolution in Syria.
Also in 2016, Turkey's Prime Minister Ahmet Davutoglu wanted to introduce Turkish troops to Syria, to help rebels in Aleppo against Bashar Al-Assad forces and to begin the operation to overthrow Bashar al-Assad (but Erdogan was against it...).

**Comment by settintotrieste** [comment]
I've checked and it is possible to do so provided that turkey is a democracy and either has jingoism as war policy, is at war or has medium world tensions.

**Comment by settintotrieste** [comment]
I've checked and it is possible to do so provided that turkey is a democracy and either has jingoism as war policy, is at war or has medium world tensions.
