### ISSUE TITLE
Fix money problems

### ISSUE THREAD

**Issue by DullishCrab94** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#312]
In this mod i noticed that the economy is real wonky its not as bad NWO but i still struggle quite alot as many nations can u make the economy a little more like vic 2 so its more easy again

**Comment by settintotrieste** [comment]
May I know which countries are having difficulty making money?

You do know that the main way to avoid a deficit is to avoid overspending on education or administration?

**Comment by DullishCrab94** [comment]
Mainly the netherlands and small european and asian countries in 1946

**Comment by DullishCrab94** [comment]
Small european countries being the satellite states of the ussr and basicly all asian and african countries in 1946 i tried to cut everything but still struggle to make money as them i tend to go bankrupt as them aswell the 1992 start date is much easier to make money i was thinking keep the base vic 2 money system and just customize certain things the way you want

**Comment by what-am-i-doing** [comment]
You basically stabilize later on as you get better tax/admin/factory efficiency and RGO techs. At which point making money becomes trivially easy.
