### ISSUE TITLE
Nuclear province modifiers bug

### ISSUE THREAD

**Issue by JohnLockers** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#314]
I was playing a game of CWE in which China and India nuked the shit out of one another. After this, Eurasia sphered and integrated the Chinese wasteland. Nuclear modifiers unfortunately were not carried over for these provinces, so the map graphic remains while the province is no longer technically a nuclear wasteland. This seems to be a bug along the vein of issue #245, except it seems to be a much bigger issue in that it voids a major mechanic of the game.

**Comment by settintotrieste** [comment]
I've solved the nuclear wasteland map graphic remaining bug however due to hard coded limitations I'm not able to make the game remember that those provinces were nuked before after annexation by another country.
