### ISSUE TITLE
Naming issues

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#318]
Small error: provid 950 is spelt wrong. It is supposed to be spelt "Uzhgorod" or something similar to this, note that the "r" at the end is gone.

Bug: Culture 'rusyn' needs to be Rusyn.

**Comment by RyongJin** [comment]
Culture "Tuvans" should be renamed to simply "Tuvan" just to reflect consistency in naming.

**Comment by settintotrieste** [comment]
Fixed in commit uploaded on 16/09/18
