### ISSUE TITLE
Governments of the Arabic countries

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#320]
I noticed that in the game in power in Syria, Iraq and Libya there are sectarian regimes, while in the mod files it is indicated that there are a Nationalist Dictatorships.

Can you please fix it?

**Comment by settintotrieste** [comment]
I have no plans to correct it as the code name does not need to correspond to the in game name as long as the in game display is correct. In this case it is correct that those countries have a sectarian dictatorship .
