### ISSUE TITLE
Oman's territory

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#321]
In the mod, The United Arab Emirates own's territory that must be part of Oman.

Map: http://www.lib.utexas.edu/maps/middle_east_and_asia/oman.gif

![image](https://user-images.githubusercontent.com/24807237/34328232-e54b3ee2-e8ea-11e7-94b8-24f115ebda6c.png)

**Comment by settintotrieste** [comment]
I will have to reject this to prevent micro provinces that are difficult for the player to click.
