### ISSUE TITLE
Fall of the USA

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#323]
May I perhaps make a suggestion of making the Mormon state of Deseret have cores? This, of course, would be mostly for those who wish to have a good laugh as a free Mormon state, but as since these areas do have Mormon majority, it wouldn't be too fantastical. I mostly suggest this as I saw you added the Californian Republic cores. Which also brought me to the idea of having New England (Including New York) to have cores, as it seems it'd be interesting to have a more disunited state, kinda like a reverse of what happened in the USSR if the right things occur, or if the US changes to a more authoritarian government, etc. Upload.wikimedia.org

**Comment by Devin616** [comment]
maybe the USSR could try and incite rebels with those cores and people like they did IRL to fuck with the US, in general i was disappointed by the lack of KGB fuckery available to the USSR.

**Comment by settintotrieste** [comment]
This was finally done in late 2020
