### ISSUE TITLE
Proposal for a Superstate overhaul

### ISSUE THREAD

**Issue by KeyboardMonkey95** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#334]
Right now Superstates rarely properly form and expand, because of the rigid requirements in the decision chains, which, although easy to satisfy by a player, are rarely achieved by AI. With the most difficult requirements for AI being the "Free Trade" policy for the "Open Trade Block" decision, and the later technologies for the last decisions. This results in the odd scenario where one Nation could form a political union composed of just itself.

Because of this, i would suggest the implementation of Events which would allow Nations to bypass the decisions if another Nation has already taken them. The Event would only fire for democracies with a MTTH of 5 or 10 years (for example), which could be shortened by being in the SoI of a nation which has taken the decision, and it would have the options to either join the next level of the Superstate or not, with the AI factor being modified by the type of party in power (Socialists and Moderates being more likely to accept than Populists).

I was also thinking of making the event impossible to fire if a nation is in the SoI of a foreign power, where, for example, a European Nation can't get the event if it's in the Chinese SoI, but i'm not sure how it could be implemented.

I know this is all pretty vague and unrefined, but it's just an idea i just had that i felt like sharing, so feel free to criticise.

**Comment by settintotrieste** [comment]
A system was made recently to allow sphere owners to block their sphere members from joining other trade blocks

**Comment by settintotrieste** [comment]
An event was made in 2020 to ask all bloc members to join upon foundation of the Superstate
