### ISSUE TITLE
Iraqi Kurdistan

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#336]
Why is Iraqi Kurdistan a part of Iraq in 1992?
As I know Iraqi Kurdistan became de-facto independent in 1991.

**Comment by RyongJin** [comment]
You are right, Kurdistan should not be completely part of Iraq in 1992. Iraqi Kurdistan established autonomy at the end of 1991, and their government was proclaimed in mid-1992. 

I think it would be fitting if Iraqi Kurdistan started as a satellite state/special administrative region of Iraq in 1992.
