### ISSUE TITLE
Handover of the Panama Canal to the Republic of Panama

### ISSUE THREAD

**Issue by AFP595** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#340]
I'm not sure if I have missed it, but I tried a campaign as Panama in the latest version, and there doesn't seem to be a decision/event for the US to return the Panama Canal to the country of Panama, as [happened historically](https://en.wikipedia.org/wiki/History_of_the_Panama_Canal#Transfer_to_Panama). Is there no handover coded indeed, or did I miss the conditions for it? I have played past year 2000 and nothing has happened yet...

**Comment by settintotrieste** [comment]
An event for this is already in the mod
