### ISSUE TITLE
In mod changes

### ISSUE THREAD

**Issue by naoisemct** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#342]
Hi, I have been making some minor changes to the mod as I play, values, events, etc. just to make things a little bit more accurate (as I see them of course). The problem is that usually the game crashes on a specific date within the first year or so. I have a lot of experience changing the code in vanilla and NWO so I don't think it's my coding, I have done far more advanced things for the other two and has never been a problem (unless it's linked to a specific event firing but I have tried several times doing different things and the problem persists so I don't think it's that either). Is this something specific to this mod i.e. it's too complex to change the code or can you give me any ideas why this my be happening? Thank you.

**Comment by settintotrieste** [comment]
It is probably due to an event you added to the game. You can use documents/CWE/logs/game to see which event is causing the crash.

**Comment by naoisemct** [comment]
There doesn't seem to be a logs file in the mod?
