### ISSUE TITLE
Multiplayer Map Glitch

### ISSUE THREAD

**Issue by KRaw21** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#343]
There is a very big glitch in multiplayer that prevents the game from even starting in a multiplayer match. Any players that join the server after loading a previous save game, can only view a blank map, and cannot select any country, upon joining the server. This problem does not affect the game when starting a fresh multiplayer match with the mod. I am using no other mods, and have cleared the cache, and reinstalled the mod multiple times. Current game version is 3.04, and CWE is on it's latest version.

**Comment by settintotrieste** [comment]
This seems to be an issue in many mods. I haven't heard a solution to the problem yet.
