### ISSUE TITLE
Baghdad Pact in Cold War events

### ISSUE THREAD

**Issue by JohnLockers** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#345]
The Central Treaty Organization aligned with the western powers, involving integration projects such as the CENTO railway from London to Teheran. Could function as a faction for parliamentary, monarchist or conservative systems in the Middle East.

http://www.iranicaonline.org/articles/baghdad-pact
https://en.wikipedia.org/wiki/Baghdad_Pact
https://2001-2009.state.gov/r/pa/ho/time/lw/98683.htm

**Comment by settintotrieste** [comment]
CENTO added as an event.
