### ISSUE TITLE
Game crashes after containing China

### ISSUE THREAD

**Issue by hafizhmakmur** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#346]
I was just in a war with Republic of China (mainland) as Indonesia (ASEAN) and make them give me South East China Islands and contain them. Then inevitably the next month the game will crash. 

[Here is the save file. I don't know what else to give since there is no log file.
](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1827935/ASEAN.victory.over.China.zip)

**Comment by settintotrieste** [comment]
Is this using the latest GitHub versions of the mod?

**Comment by hafizhmakmur** [comment]
Yes, 1.7 right?

**Comment by settintotrieste** [comment]
Yes

**Comment by settintotrieste** [comment]
Problem seems to have disappeared
