### ISSUE TITLE
Proposal: change to migration mechanics

### ISSUE THREAD

**Issue by what-am-i-doing** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#347]
These altered poptype files change the impact of state capital and not state capital. Now, instead of completely disabling migration to non-capital provinces, pops will migrate to non-capital or capital provinces based on Urbanisation and Ruralisation focus decisions, so these focuses will actually be reflected by pop movements. Additionally, nonaccepted pops will gravitate towards cities while accepted pops will gravitate towards rural areas.

This should help recreate the real life phenomenon wherein immigrants move primarily to cities while the local population starts to move out of cities into less diverse suburban and rural communities. (the old versions of the files had it the other way around which made for bizarre provincial pop composition) slaves.txt has not been altered as they do not migrate.

If these changes are accepted the files go into poptypes folder. I do not know how to create a pull request so I'm just posting them here.

[aristocrats.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1836469/aristocrats.txt)
[artisans.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1836470/artisans.txt)
[bureaucrats.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1836471/bureaucrats.txt)
[capitalists.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1836472/capitalists.txt)
[clergymen.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1836473/clergymen.txt)
[clerks.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1836474/clerks.txt)
[craftsmen.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1836475/craftsmen.txt)
[farmers.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1836476/farmers.txt)
[labourers.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1836477/labourers.txt)
[officers.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1836478/officers.txt)
[soldiers.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/1836479/soldiers.txt)

**Comment by settintotrieste** [comment]
This is great, I will add it to the mod. Thank you!
