### ISSUE TITLE
issues with Britain

### ISSUE THREAD

**Issue by ghost** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#351]
played the latest (nightly) version
1946 bookmark

- Britain should have trinket pension as opposed to no pension
https://en.wikipedia.org/wiki/Old-Age_Pensions_Act_1908
- wouldn't it make more sense if Britain was allied with their former dominions
- shouldn't Palestine be a puppet (mandate) instead of being a British territory. It would also make it easier to start the game as either Israel or Palestine without tag swtiching between the two, instead there could be an event to choose between them.

**Comment by settintotrieste** [comment]
Thank you for your feedback!

1. Done

2. Done

3. Due to the way the Arab-Israeli conflict has been coded, it is very difficult to change it to the way you proposed so I am not in favour of this.
