### ISSUE TITLE
Commonwealth of nations 

### ISSUE THREAD

**Issue by domenico267** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#354]
I've experienced a pretty strange bug. As the Commonwealth of nations i've tried to use the "admit Commonwealth member" option, but when i've done it, the only country that i was allowed to annect was Australia. I tried to use the event many times, and every time i've received the notification about the annexation of Australia, although it was already annexed.
I tried to load the same savefile to select Canada and see if there was any option to join the Commonwealth, and i've received a notification about the request of annexation by the Commonwealth, so it seems is only a player's problem. I'm playing at the latest version of CWE.

**Comment by Anonymous1111111** [comment]
I had it too.  Go to decisions\imperial_federation.txt and find IMP_enlarge_union and change limit with this code
limit = { 

exists = yes

OR = {
primary_culture = white_anglo
primary_culture = english
primary_culture = black_anglo
} 

OR = { neighbour = THIS tag = CAN tag = NZL tag = AST }

OR = { has_country_flag = IMP_ambition vassal_of = THIS in_sphere = THIS } 

}
