### ISSUE TITLE
Adding in resource

### ISSUE THREAD

**Issue by triscar455** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#357]
Im trying to add in a new resource but it keeps crashing on start up. When i delete the new resource from Goods the game launches fine. I have edited the pop types(so they consume), production types, and txt,buildings txt. Help? Im trying to add resources to develop a service industry

**Comment by settintotrieste** [comment]
I'm afraid that I do not know how to fix your issue. Perhaps you can refer to this guide on the paradox forums?

https://forum.paradoxplaza.com/forum/index.php?threads/adding-trade-goods.599177/
