### ISSUE TITLE
Omani terrotories in UAE

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#364]
Hello. There are Omani exclave named "Madha" in UAE.
Also and what is more important, there is Omani territory in the strait of Hormuz.

Map:
![default](https://user-images.githubusercontent.com/24807237/42733843-c11f44b8-8841-11e8-8295-62d961ce89b2.png)

https://www.shutterstock.com/image-vector/strait-hormuz-region-political-map-english-694847767

https://www.google.com/maps/place/Khasab,+Oman/@26.0926651,55.9975901,9.5z/data=!4m5!3m4!1s0x3ef6f5d473547935:0xa2b3dac53136066!8m2!3d26.1643745!4d56.2427902

If you can't add the new provinces, then I can suggest that you can take this part of land into Omani province on the border with UAE (I mean in the strait of Hormuz.)

**Comment by settintotrieste** [comment]
I do not intend to add new provinces to the map and tweaking the existing provinces cause pathing issues in the game so I will have to reject this.
