### ISSUE TITLE
Iraq's position in the Middle East

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#365]
Hello. Iraq in 1960s-2003 was a regional power, maybe even more powerful than Iran.
So I think that Iraq should be a secondary power in 1992 scenario.

**Comment by settintotrieste** [comment]
Its difficult to balance Iraq mid-game to increase their power to secondary power as there are many variables at play. I've done some tweaks to increase the soldier population promotion rate for Iraq so hopefully it will allow them to field a larger army.
