### ISSUE TITLE
Turkey in the 2000s

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#366]
In the late 1990s and the early 2000s Turkish economy was booming and Turkey became a Regional Power. So what about some event for Turkey to become a Great Power in the 2000s.
It already had a Sphere of Influence in the Caucasus (Azerbaijan) by the mid 2000s and influenced Iraqi Kurdistan by 2010s.

By the way, about Turkish alliance with Iraqi Kurdistan in the 1990s. I think that they should be allied in the 2000s, but not in the 1990s. But of course it is a subject of discussion.

**Comment by settintotrieste** [comment]
I wouldn't consider Turkey a great power in 2018 as their global influence (soft power + hard power) is still not as much as the current top 8 countries, USA, Russia, China, Japan (3rd largest economy), Germany (via the EU), India (Nukes and pop size), France (UNSC + massive french sphere in West Africa) and the UK (UNSC and the Commonwealth Realms). 

Removed the Turkey's alliance with Kurdistan in 1990.
