### ISSUE TITLE
South Africa starting Primary and Accepted culture

### ISSUE THREAD

**Issue by what-am-i-doing** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#367]
South Africa used to start with White Anglo primary and Afrikaner accepted culture, with the ability to flip those around if it became a Sectarian Regime via referendum vs leaving them as they are if it remained a monarchy. Now it seems to start with Afrikaner primary and White Anglo accepted (in 1946 start). I believe it should go back to having White Anglo primary and Afrikaner accepted in 1946 start.

**Comment by what-am-i-doing** [comment]
Also, this would probably require the Volkstaat event to not fire if primary culture is White Anglo.

**Comment by settintotrieste** [comment]
I've done a check, the current Github version has South Africa starting with White Anglo as primary and Afrikaaner as accepted which swaps upon changing to sectarian regime.

Added your second suggestion
