### ISSUE TITLE
Dhofar Rebellion and Iran-Iraq War

### ISSUE THREAD

**Issue by JohnLockers** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#370]
https://en.wikipedia.org/wiki/Dhofar_Rebellion
https://en.wikipedia.org/wiki/Iran%E2%80%93Iraq_War

These conflicts could make interesting flavor events during the Cold War. In the case of Iraq, they could potentially be given cores on Khuzestan province and maybe the possibility of installing the MEK in control of Iran (as they attempted in Operation Eternal Light).

**Comment by settintotrieste** [comment]
Added in dd06e49
