### ISSUE TITLE
Game crashes when clicking on Vienna after accepting Austrian Reunification as USSR

### ISSUE THREAD

**Issue by SplendidX** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#375]
The game crashes when clicking on Vienna after accepting Austrian Reunification as USSR. Only when clicking on Vienna, any other province doesn't produce the crash. I couldn't find anything in the logs to signal why this happens.

**Comment by settintotrieste** [comment]
This is due to the event reducing communist ideology support. Just let the game run a few days and then you will be able to click on Vienna.
