### ISSUE TITLE
More possible Arab union states

### ISSUE THREAD

**Issue by JohnLockers** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#376]
In addition to the federation of Iraq and Jordan and the UAR, several different unity projects were undertaken by different Arab leaders. Most all of the Arab nationalist governments attempted it at one time, and it could have possibly succeeded if not for political differences. Maybe there should be a system to add more of these union states, which can add flavor to the Cold War scenario.

https://en.wikipedia.org/wiki/Arab_Cold_War

**Comment by settintotrieste** [comment]
Currently the Arab federation has been added together with the Federation of Arab Republics
