### ISSUE TITLE
Economic migration

### ISSUE THREAD

**Issue by JohnLockers** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#377]
There should be an immigration push from poor regions to wealthy ones. Currently it seems most of the drivers for migration are based on reforms, which should have weight but not be the only consideration. For instance, many migrants move to China despite a more arcane political system.

**Comment by settintotrieste** [comment]
Some changes have been done to use unemployment and tax levels to determine immigrant attractiveness.
