### ISSUE TITLE
Superpower system

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#383]
Hello. I wonder, if it is possible to remove 2nd Superpower status only in 1992 scenario? And make it, that Superpower status, can be accompolished by certain moves.
I think it would be historically more accurate, to have only one Superpower in the beginning of the 1992 scenario.

**Comment by settintotrieste** [comment]
It's rather difficult to tweak the superpower system now as it has been throughly integrated into too many areas and the lack of codes to check industrial and military score in proportion to the leading power to properly determine eligibility for superpower status beyond just rank.
