### ISSUE TITLE
Consumption Focus Economy

### ISSUE THREAD

**Issue by naoisemct** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#384]
I think that there should be a third, harder to achieve, option for the economy focus. I think a consumption focus would better reflect America's, possibly Britain's, focus of declining manufacturing with a heavy emphasis on consumption. It would also allow up-and-coming nations to better compete on industrial scores as big Western economies slowly diverge from manufacturing. The idea would be that making it easier to import and loan money would slowly disincentivise manufacturing within a country.

[export-import-consume focus.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/2611728/export-import-consume.focus.txt)

**Comment by what-am-i-doing** [comment]
This is already represented in import substitution focus vs export focus. The former provides a pop growth bonus which due to Victoria 2's hardcoded and, honestly, pretty retarded metric for industrial power (pops employed rather than goods produced) means that developing nations will catch up in industry scores.

**Comment by settintotrieste** [comment]
This is somewhat simulated in game already. As craftsmen working in factories are the only means to calculate industrial score which is used in game to approximate economic power, reducing factories will break the mod. The consumption focus is currently simulated by selecting a service focused economy and greater pop needs fulfilment  increases consumption via the "affluent society" modifier. As what I am doing explained, the rise of developing nations are also simulated through the import substitution decision and other decisions that boost factory output and craftsmen the promotion in non great or secondary powers.

**Comment by settintotrieste** [comment]
Also due to flawed base game mechanics, pops always but from the internal market first regardless of competitiveness so reducing import cost won't lead to local factories closing.
