### ISSUE TITLE
Economic Structures

### ISSUE THREAD

**Issue by naoisemct** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#387]
Okay this is a big one but it's been my baby for the past while.

I always get a bit annoyed because Victoria II in general offers a lot of political decisions and reforms but your control over economic structures is basically limited to moving your tax and tariff sliders around (plus some very welcome CWE decisions). I have written some out a new decision/event path for players to be able to better control the structure of your economy and how it impacts on your politics and population.

This economic structure path would offer 6 choices with different benefits and affects.

Stock-based structure: 

Basically, the structure of most modern-day developed countries. Stock and financial markets play big roles in society. This structure sees a slow redistribution to the rich strata with RGO and commerce tech bonuses, allowing a player to fuel the economic growth of its elites. This would reflect both growing wealth and wealth inequality in some developed countries.

Stake-holder based structure:

The structure of 'responsible capitalism' seen in countries such as Germany today. It pushes even progress in the economy, education and technology and in political/social reforms. The idea is a general, slow, and even progress encompassing the whole of a country.

Collectivised structure:

A structure that allows a fast redistribution of power and wealth to the government. Used to reflect the economies of the communist states in the 20th century. It basically sees increased government income and support, deflation of the populations income and increased industrial tech and output. The idea is to show the sacrifice of living standards for the government's political and industrial power (with later market reform options).

Corrupt structure:

This essentially reflects how corruption causes government and elite power to intertwine in many developing countries. It pushes economic and political power into the hands of the government and the rich and restricts the ability of social and political reformers to achieve gains.

Growth structure:

Essentially to represent developing countries that get it right. Big economic benefits coupled with education and technology boosts, social/political reform desire increases, more support for the ruling party. It is supposed to reflect the ‘tiger economies’ of the world their quick rise to developed status but is hard to achieve and is littered with ups and downs. 

Co-operative structure:

The co-operative structure is designed to show how a growing movement of worker-owned co-operatives would slowly increase in power and push the government to create further opportunities for it. It essentially offers a path in which a co-operative movement slowly takes over the economy, redistributing wealth the middle and lower classes and forcing the rich into irrelevancy.  It sees large increases in middle/lower income, sharp decreases in rich income, increases in local production (artisans/entrepreneurs) and some economic benefits to off-set the through-put losses of the rich classes.

These decision/event paths essentially offer a private ownership responsible (stock)/irresponsible (stake) model, a public/collective ownership responsible (co-op)/irresponsible (collective) model, and a development responsible (growth)/ irresponsible (corruption) model.

The idea is that most Western countries will fall into stock market, more socially progressive developed countries will choose/eventually choose stakeholder, more liberal developing countries will choose growth, most developing countries will choose corruption, communist countries will choose collectivised (with market communists moving on to market reforms) and co-operatisation being an option for the future.

There are a number of options to stop, reverse, switch or end economic models but the idea is that it is hard to do so.

[Economic Structure Events.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/2612726/Economic.Structure.Events.txt)
[Economic Structure Localisation.xlsx](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/2612727/Economic.Structure.Localisation.xlsx)
[Economic Structures Event Modifiers.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/2612728/Economic.Structures.Event.Modifiers.txt)
[Economic Strutures Decisions.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/2612729/Economic.Strutures.Decisions.txt)

**Comment by what-am-i-doing** [comment]
>more socially progressive developed countries will choose/eventually choose stakeholder

This seems unrealistic. Social progressive political ideologies are championed by big businesses who have no interest in the workers' wellbeing. Where social progress rules, the wealthy bring in scabs by the hundreds of thousands, and if the local workers stand up for themselves and call for a halt to mass immigration of scabs - they are silenced by the cry of "racist!"

Social progressive countries should get a fast track to the impoverishment of the working class and enrichment of the wealthy, as they do in real life. My home country of Canada is a good example of this. We are on the path to serfdom.

**Comment by naoisemct** [comment]
Well it's idea is more reflective of say Sweden in the seventies or the American New Deal, i.e. a pre-neoliberal capitalist model vs. the neoliberal countries of today (which are represented by the Stock Market choice). They are two choices for capitalist countries, one named Stock Market because it favours those with wealth, one called Stakeholder because it has a broad base of participation. Parties to the left have historically favoured more balanced forms of capitalism. Its not really a political argument its just more conservative parties will choose a structure that favours wealth and more progressive parties will choose a more balanced structure.

**Comment by naoisemct** [comment]
Socially progress meaning meaning focusing on all of society not just elites a la the Nordic countries in the 60's and 70's. It still gives more of a boost a to rich strata just makes things a bit more level.

**Comment by what-am-i-doing** [comment]
That is not what social progress means. Social progress means embracing deviant behavior and mental illnesses, and enforcing tolerance of such things on the general population. IE homosexuality, miscegenation, transgenderism, etc.

Focusing on all of society rather than the elites is called fascism.

Progressive parties absolutely favour the wealthy as they support maximized immigration which undercuts the working class as the immigrants they bring in are accustomed to lower standards of living and willing to work for less money. Progressive parties, in other words, support the most vile form of life: the scab.

**Comment by what-am-i-doing** [comment]
You are asking for unrealistic changes to be made based on your incorrect political views; this would be detrimental to the mod by reducing realism.

Left parties in the 20th and 21st centuries doing anything other than fight the working class is highly unrealistic.

**Comment by naoisemct** [comment]
Well first yes I agree with you, in a capitalist system the non-revolutionary Left simply is there to sate the working classes drive for change by piece-meal reforms, but as I have told you this is reflected in how the rich still gain from both system.

I fail to see how it is unrealistic when I have completely written out all the code for it......

**Comment by naoisemct** [comment]
Britain - NHS passed by the Labour Party: 64.6 million patients a year
USA - Social Security created by Democratic party under pressure from two socialist and one communist party: keeps 22 million elderly people out of poverty each year
USA - Public Works passed during the Great Depression by Democratic party under pressure from two socialist and one communist party: 15 million people put back to work
Netherlands - Pensions passed by Labour Party: elderly poverty decreased by 65%
France: Welfare reforms passed by the coalition of socialist and communist parties: poverty reduced by 26%
Britain - Family Allowances passed by Labour Party: 20 pounds per a week for every family
Britain - National Industrial Insurance passed by Labour Party: disability benefits for victims and dependants of industrial injuries
Britain - National Insurance passed by Labour Party: poverty reduced by 8%

You can disagree with motives/outcomes but historically Left parties are the drivers behind social and government support for the working classes. Obviously these programs have been failing for decades under the influence of neo-liberal budget cuts and austerity and that the political shift after the 70's and a move to a inflation reduction model rather than a poverty/unemployment reduction model across the political spectrum (Carter/Clinton/Obama in US, New Labour in Britain, the centring of the Socialist Party in in France). But to say that leftist parties are not the drivers of these reforms in capitalist countries (again stipulating that in capitalist societies the wealthy are always ultimately benefited now matter what the policies are - again as reflected in my model), is just historically inaccurate.

You can argue that they don't work etc, etc, but that's just what happened, if you look at what parties are now pushing for a break from or a reform of neo-liberalism through a strengthened combination of government spending and stronger labour rights they are all leftist; Corbyn, Lula, Sanders, Melachon, Podamos, etc. Yes there are pushes from the right to end neo-liberalism, but almost all, except from some of the Front National's policies, are pushing for a realignment on anti-immigration policies, reducing tax, weakening unions i.e. not the governmental approach the code is written to reflect. You can't argue with history or modern political developments, welfare policies have always been pushed for by leftist parties, you can disagree with how they work or why they happen but that's just a historical fact.

I fail to see how you ideas of how black and white should not get married or have children out-weigh decades of political evidence. If you disagree with the policy outcomes fine, if you don't think all my stipulations about how this just reflects one specific structure in one specific system and how this is reflected in the code by still mainly benefiting the rich are relevant fine, but leftist (non-neoliberal) parties in a capitalist system are the drivers for government social policies that redistribute to the working classes, that's just a fact I am sorry.

P.S. if you have problems with how this affects labour rights the code literally requires strong labour laws to be able to implement.

**Comment by what-am-i-doing** [comment]
Thank you for providing several examples of left-wing policies wherein the working class is taxed more and more heavily to pay for nonproductive welfare parasites.

**Comment by JohnLockers** [comment]
These are good contributions you make, very thoughtful and well-reasoned, and I'd like to test them if possible, can't get these to work currently though. Do you envision that countries will be assigned a default system in each scenario, or will the paths be opened as reforms are passed/popular support permits them? It could be interesting to try and turn around a corrupt system to become a positive one.

**Comment by naoisemct** [comment]
Yeah essentially the paths out of each (bar the co-operative which has a more gradual path), is economic downturn plus a change in leadership and I certain amount of popular support i.e. for ending the stock market dominant one its a certain amount of your population have to be of the three left ideologies. Also there is internal ones where you can end or transform into other paths.

With regards to where each country will fall into in the start, they should fall into their historical models. All communist countries will fall into collectivsed. Most developing will choose corruption, the idea is then they can develop into growth. And most capitalist will choose stock market with a few like Scandinavia will choose stake holder.

**Comment by settintotrieste** [comment]
These are interesting ideas, thank you for your contributions. There are however significant overlaps with the existing decisions and mechanics in game. The places where it overlaps are import/export focus, economic specialisation, the corruption mechanic, national policies, banking regulations, tax havens, entrepot trade, affluent society triggered modifiers, collectivisation, Nationalisation vs Privatisation. MNC agency/corruption, MNC favourability policy decisions, Sovereign Wealth Funds, Central Bank Interest Rates, Petroleum company skullduggery, financial centres, base taxation & tariff system and the Nordic style stock redistribution system added recently. Currently the economic structures have been broken down into its various parts by existing events and decisions so I'm not sure how to add in your decision and events..

**Comment by naoisemct** [comment]
Well I think the Co-op section still has some value then. Most of those decisions are very limited to one economic system and there is very little options once you step outside of that.

**Comment by settintotrieste** [comment]
Kept the existing system in the end
