### ISSUE TITLE
Political corruption and end of democracy

### ISSUE THREAD

**Issue by JohnLockers** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#389]
There could be a system (free of the rebel system) for democracies to disintegrate and end in the establishment of new dictatorships when steps are not taken to bring stability to a political system from internal threats. This could add flavor to gameplay, maybe sphere leaders can also further political stability by decision, such as US foreign policy on human rights.

**Comment by naoisemct** [comment]
Could be interesting to have a sphere leader/bloc leader (not strictly the Cold War Blocs i.e. US as post-CW Western bloc leader) have a high-medium-low human rights/democratic values decision path (a lá the Nato or CW bloc leader decisions). If you pick high your sphere/bloc has less chance to pick a decision path to move away from democracy which would be represented by a common (non-GP/bloc leader) decision path to increase ruling party support and roll-back political reforms. I could write out some code to do it if there is interest?

**Comment by naoisemct** [comment]
It actually wouldn't be too hard, either a triggered modifier for great power democracies or a superpower-democracy that gives a "democratic_leader" country flag (might take a little bit of messy code to work out how it affects political influence i.e. spheres but probably just if a democratic superpower has the country flag and you are in a democratic sphere), that would lead to a change-high-medium-low decision path on supporting democratic values which would in-turn give affected non-GPs a event path which leads to three possible decision (depending on the leaders choice) on how democratic they should be (like election emphasis) which will give ruling party support and political reform desire plus/minuses.

**Comment by naoisemct** [comment]
It's not quite what you're asking for but it's the sphere leaders aspect of it. Essentially the leading democracy in the world (basically the US) gets to decide how strong the democratic values they are going to push are going to be, then all the countries that are in their sphere or in a another democracy's sphere get a country modifier reflecting their choice. It could easily be worked into a decision/event path for decaying democracy, as in if the democratic leader isn't pushing strong democratic values you have more of a chance to retreat from democracy.

[Democratic Values Influence.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/2655529/Democratic.Values.Influence.txt)

**Comment by settintotrieste** [comment]
This is an interesting idea. I will try to integrate it into the mod. I would plan to expand its scope to all democratic sphere owners though as multiple western countries do practice such policies.
