### ISSUE TITLE
Crashing upon loading saved game in 2020's

### ISSUE THREAD

**Issue by vegku** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#390]
I am not entirely sure where to report this but here it goes. Im playing as USA and reached 2026 and I logged off. When I logged back in I could only play for 5 days till I crashed. 

I know you need some files so which are the ones you need?

**Comment by settintotrieste** [comment]
Did you update the mod before you continued playing? Some updates break old save games.

**Comment by settintotrieste** [comment]
You can provide me the savegame file from documents/victoria 2/CWE/savegame and I'll take a look at it.

**Comment by vegku** [comment]
I did not update anything before loading this. I played through it on the current update. I just logged off one night and loaded back up and crashed after a few days in game. 

[The_American State2026_05_02.zip](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/2692153/The_American.State2026_05_02.zip)

**Comment by settintotrieste** [comment]
I did a quick run through and it crashed on my end as well however the event logs did not show up anything so I'm afraid I can't do anything at the moment.

**Comment by vegku** [comment]
:(

**Comment by vegku** [comment]
Wait a minute! I saved the game when I was supposed to choose a new leader after my old one died. I believe that event is the one causing a crash? Noy sure if that helps

**Comment by settintotrieste** [comment]
I did a separate run through on my end to 2024 and I did encounter a similar problem. However I did a few tweaks and it mysteriously disappeared just as it appeared. Perhaps you could try a new game with the latest github version?
