### ISSUE TITLE
Disputed states + Union culture mechanics

### ISSUE THREAD

**Issue by JohnLockers** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#391]
Here are a few solutions for minor border readjustments in Germany and Poland. These notably do not effect the possibility of potential German reconquest of these territories, but do clean up border disputes so Poland doesn’t end up taking Berlin in attempting to reclaim Lubusz. A few other places in the world have arguably similar applications for this form of reorganization due to ongoing or historic border disputes or separatism (Denmark-Germany, Poland-Belarus, Slovakia-Ukraine, Romania-Bulgaria, Georgia-Turkey, Gibraltar, Melilla, Malta, Nagorno-Karabakh, Golan, Bosnia, Goa, Kuwait, Gaza, Halaib, Puntland, Tamilish Sri Lanka to name some)

East German reorganization: Gorlitz should be joined to Saxony, Stralsund and Swinemunde should be joined to Mecklenburg-Vorpommern.
Polish/Czechia reorganization: Kustrin should be joined to Schlesien. Czech territory Tesin should be joined to Moravia.

Another idea would be different possible paths to cultural integration of Supernational Unions. There should be an option to keep (and accept major cultures) or absorb them. Keeping these nationalities can provide a positive strength in that the full potential of each culture may be used by the union without waiting for the identity to take hold over a matter of decades through integration. Potential drawback of this approach may come with increased separatism and regionalism, or power disparities, potentially leading to the breakup of the union over time and conflict. Basically, if you keep relative stability and wealth, these negatives aren’t as threatening. If you go to war all over the place and your economy tanks, there’s a greater chance of a collapse.

Integrating cultures into an umbrella culture, on the other hand, will cause initial weaknesses but allow for a more unitary approach after the elimination of separate identities (and core provinces of the nations they were built upon). Superstates should also face more risks during the period of implementation of cultural integration policies, such as higher militancy/consciousness within substituent cultures which face gradual elimination. At the end of this period, cores of substituent nations will be removed and unions will be more or less permanent.

This system seems workable in each case except for the Arab Union due to cultural homogeneity. Maybe a unique path could be created here, as a whole bunch of new cultures would get complicated and annoying to say the least. (Iraqi, Syrian, Egyptian, Libyan, Moroccan, etc.)

**Comment by JohnLockers** [comment]
A third culture path could be similar to the "Europe of Regions" concept. This path essentially would constitute extreme multiculturalism and respect for local cultures. Upon annexing substituent countries, a supernational union will have the option to accept both primary and accepted cultures, rather than only primary. It could also remove substituent nations cores, such as removing Spanish cores from Catalonia. This will allow maximum initial strengths but will further slow down integration to the primary culture. For instance, attempting to annex France with the "Europe of Regions" path will add accepted cultures French, Breton, Occitan, and White French. The simple "acceptance path" will only accept French.

**Comment by settintotrieste** [comment]
Problem with creating a pan superstate culture is that the pan culture must be present in all provinces for other pops to assimilate into it which is too much effort to do. The culture must also not be accepted as there’s a hardcoded limitation blocking such pops from assimilating.
