### ISSUE TITLE
German Austria, devolution, Cornwall, Soviet eastern europe events

### ISSUE THREAD

**Issue by JohnLockers** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#392]
Hello,

Here are a few brief ideas I have had lately. Some friends and I have also been working on some concepts to make decolonization more dynamic, which I'll probably post sometime soon. Settintotrieste, do you have Steam?

1. German Austria: Similar to German reunification events which give cores on former lands of the German Empire, Germany can gain cores on Austria with enough jingoism or the correct party in power.

2. Devolution to puppets by AI can depend on the governing philosophy. A “liberty” or less likely an “equality” or “meritocracy” national value with more liberal ideologies in power will be more inclined to devolve power locally, such as Labour’s policy of devolution to the Scottish Parliament and Welsh Assembly. This can replace some current hard coded events, such as devolution of Mindanao to Bansamoro Republik.

3. A core for Cornwall in Plymoth and Cornish nationality for around 26% of population there (2011 Census, cannot find population statistics for 1946).

4. If the counter for the former Soviet Union “Our power in Eastern Europe has weakened” system still exists, it can be used in a separate way. The Soviet Union will be given an influence points gain boost, a prestige gain modifier, and a small culture tech boost for each variable soviet_control_cee above -1.00.

**Comment by settintotrieste** [comment]
I'm currently contemplating setting up a discord for this mod to centralise communication between the 3 feedback channels at the moment: P'dox forum, Moddb, Github

1 and 2 are done.

May I know if there are any major movements pushing for Cornish independence? 

The counter has been shelved as it has been replaced by a new mechanic to dissolve the USSR and the Warsaw Pact. What criteria do you think would lead to a strengthening of the soviet bloc?

**Comment by JohnLockers** [comment]
Mebyon Kernow is a political party affiliated with Plaid Cyrmu which advocates Cornish independence. The Celtic League also advocates for the Cornish and Manx as celtic nations.

I think the Bloc winning a conflict, expanding or winning in cold war events could constitute a strengthening. But if the counter is removed it seems kind of unnecessary to reimplement it to add this.

**Comment by settintotrieste** [comment]
Devolution has been improved in 1.11 to be more dynamic.

**Comment by settintotrieste** [comment]
I've dropped the Cornwall suggestion as it lacks sufficient support
