### ISSUE TITLE
A roadmap for dynamic decolonization

### ISSUE THREAD

**Issue by JohnLockers** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#393]
So here are two major ideas of how to liven up decolonization a little bit. These would definitely take more legwork to implement, but they would provide a more accurate and entertaining experience of decolonization. This is a fairly succinct guide to implementing these, so I've put it into PDF form for more ease of viewing. These are the ideas, fundamentally:

1. Allowing a colonial nation to take its cores easier, immediately annexing them upon capture. Additionally establishing a liberation war mechanism for nationalist/communist postcolonial nations. Permits alternate history paths for colonizers to hold on to provinces.

2. Introducing dynamic colonial rebellions which begin to foment after the Year of Africa, 1960. Establishing two unique rebel tags for each colonial region, simulating broad coalitions of anti-colonial rebels (communist and nationalist). Dynamically grants provinces to rebels after independence demands events are not resolved, leading to directly granting provinces to these tags and open insurgency. Foreign support and ideology boost events will strengthen different ideologies. After the colonial nation is defeated, these will contend for power, can happen peacefully or through a war. UN resolution of civil wars is possible.

[decolroadmap.pdf](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/2729111/decolroadmap.pdf)

EDIT: Perhaps there can also be events to boost nationalist/communist ideology in overseas colonial provinces, relative to more standard and liberal ideologies. This simulates radicalization of opposition when self-determination is denied.

**Comment by settintotrieste** [comment]
Interesting. I will take some time to see how to implement this as it will change large parts of the existing decolonisation chain.

**Comment by JohnLockers** [comment]
This could be a possible way for a colonizing power to win the colonial war using a divide-and-conquer strategy. Credit to Bismarkingit who collaborated ironing out the details.

Culture disputes
Side with one culture or ignore it
The other gets pissed off
Around the 70s and 80s, the entire colonial empire revolts
The ones you sided with dont, however
If you lose, your empire collapses and a large amount of prestige is lost. The victorious freed colony can decide to act conciliatory towards the defeated cultures or seek to punish them for collaboration.
If you win, the cultures you sided with become accepted cultures, the ones you sided against become extremist and militant, and the ones you ignored remain neutral, and a large amount of prestige is awarded.

**Comment by Bismarckingit** [comment]
The war could be placed anywhere between the 60s and 80s.
