### ISSUE TITLE
SATO, ALBA, Resistance Axes, influence ideas

### ISSUE THREAD

**Issue by JohnLockers** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#398]
1. SATO (South Atlantic Treaty Organization): A hypothetical military alliance similar to NATO but comprising of nations of South America and Africa. In 2009 Gaddafi, Mugabe, Chavez, etc determined to make this alliance a reality as a way of uniting the two continents against Western imperialism.
2. Resistance Axis - Iran, Syria, Hezbollah, Houthis opposing Israel, the West, and the Gulf Cooperation Council. The Middle Eastern Cold War can be represented.
3. ALBA (Bolivarian Alliance for the Peoples of Our America) trade bloc for socialist/social democratic countries in America.
4. A third influence decision to decrease foreign influence in nation, and later a fourth one to align with regional bloc leader. Third is usually taken by Non-aligned movement powers, fourth is highly favored over others when blocs begin to appear if the government type matches with bloc leaders.
5. Resistance Axes between rogue states, allow rogue states (with tanked infamy or not) to ally each other. Joining a resistance axis will clear foreign great power influence back to Hostile and fuel integration with possibly sympathetic great powers.
6. Great Powers can support pet integration projects in which friendly nations will pursue development less hostile to seated interests, such as US policy towards ASEAN or the EU.

**Comment by settintotrieste** [comment]
As of today, 1, 4, 5, 6 have been implement in some way

**Comment by settintotrieste** [comment]
Mod development has stopped and so all outstanding issues will be closed.
