### ISSUE TITLE
Developing communist events + militias

### ISSUE THREAD

**Issue by JohnLockers** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#399]
Hello, here are some small events which could be envisioned for communist countries in the developing world. These could be an answer to keep them from lagging behind. Militias may also help to buff up dictatorships in the case of invasion, and provide some stability to unstable regimes.

1. Literacy (research bonuses, very small boosts to higher education), healthcare and sanitation (population growth), housing initiatives, land reform, infrastructure projects for communist or socialist regimes in the developing world. Increase political support and prestige, provide some bonuses, take money. These may also fail and/or backfire depending on other factors. This seems helpful and may provide some tangible benefits for leaving the Francophonie/Commonwealth.
2. Revolutionary Defense Committees (such as in Cuba or Burkina Faso) for communists, causing hostile military units to take larger attrition when on owned or occupied land. Additionally providing political support boosts. Pro-state militias can be used by any dictatorship. These can create issues with the population, with corruption and thuggery possible.

**Comment by naoisemct** [comment]
[Literacy Campaign.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/3664338/Literacy.Campaign.txt)

**Comment by settintotrieste** [comment]
A decision was made to allow socialist dictatorships to immediately enact all social reforms which gives them quite a leg up in literacy growth.

Considered making a partisan system like that in HPM but decided against it in the end for reasons elaborated in another issue post.
