### ISSUE TITLE
Spheres of influence issue

### ISSUE THREAD

**Issue by samwoodzadrot** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#406]
Hello. I noticed, that the U.S (at least in 1992 scenario*), is losing its spheres. For example, it loses Poland and Turkey, also sometimes it loses Saudi Arabia, and some other countries*.
I don't know why is it happening, but it (at least for me*) ruins the gameplay.

(I have to add the note: I always make Russia instead of China, the second Superpower in the 1992 scenario, so I don't know whether that's the case with China, but when I'm playing, Russia sometimes gets countries like Lithuania into its Sphere, which also ruins the process a little bit. *edit: Even if I'm playing as Russia. It gets them through the Superpower decisions*.)

**Comment by settintotrieste** [comment]
I currently have no plans to revise the sphere setup of the 1992 scenario

**Comment by settintotrieste** [comment]
Starting GP and SP positions have been tweaked in 1.11
