### ISSUE TITLE
Multiple ways to end Brezhnev Stagnation

### ISSUE THREAD

**Issue by Devin616** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#407]
personally i feel that being railroaded into Market Communism is kindof terrible. being slapped with crippling stagnation modifiers with the only way out being switching to market communism isn't enjoyable, especially when there are other things available which look like solutions available that aren't. i propose a few solutions to the brezhnev stagnation:

Glasnost without perestroika: 
  - political reforms allow more freedom and fight corruption in the bureaucracy, allowing the economy to move forward without the ball and chain of cronyism and political bias holding it back, but the planned economy remains untouched.

Digitization: 
 - the options of digital economic planning and the internet take the planning away from the corrupt bureaucracy, thus allowing the economy to grow again as computers can't be bribed or biased. this actually makes the digital planning good instead of just giving you modifiers.

the normal path:
 - the regular in-game path to ending the brezhnev stagnation.

Decentralisation:
 - switching to a [Decentralized planned economy](https://en.wikipedia.org/wiki/Decentralized_planning_(economics)) cuts down on the corruption and the economy is able to grow again with the cost of less government power and the removal of the 5 year plan decision.

The Purge:
 - [Call in the military to march on moscow and brutally murder most of the bureaucracy and leadership and replace it with a Military Junta](https://youtu.be/-calvsGLRfs?t=25). this will cause a civil war between the "War Communists"( policies of protectionism fully-planned economy residency secularized) and the "Bureaucratic Communists"(policies of protectionism semi-planned economy full citizenship atheist) (both should be communist parties)

other factions such as the reformists and democratic capitalists would also split off as landless armies of rebels that have a very small chance of wining the war if they occupy Moscow.

most of the army should join the player side as the Military Junta but some will split off and Join the Bureaucracy and the Bureaucracy should also get the more urban areas of the USSR and the Junta will get the countryside, thus allowing the bureaucracy to mobilise a larger army eventually.

if the Bureaucracy wins the ruling party's name will change back to 'Communist party'. this is definitely the most insane and probably most fun option. when the Junta wins the Modifier "War Communism" will happen increasing RGO production and increasing factory output at the cost of tax efficiency, militancy increasing over time,  increased life needs of all classes, and reduced income of the rich and middle classes.

also, this will kill all of the bureaucrat and landowner pops in Moscow and 70% of the bureaucrat and landowner pops in the rest of the country.

**Comment by naoisemct** [comment]
This was part of the reason I tried to introduce a co-operative economic structure in the game; I felt that Communists countries had very limited paths and flavor in terms of economic reform. The Socialist Democracy government type was really interesting but it lacked  economic progression to go with it. I think the idea is more how can the game offer any Communist country a path that isn't just a Soviet model, Market Communism or dissolution. Really the only way of playing as a Communist country other than is to either use the Soviet system or make massive concessions in the political and economic sphere away from Communism.

The decision/event path I wrote was one in which Communist or Socialist government could transfer either private or public ownership of the economy into decentralised work-ownership, thus allowing you to preserve a Communist model while to having to maintain the brittle Soviet model. The idea was that a country would slowly transfer to a co-operative model through staggered decisions and events.

This would of allowed the Soviet Union to avoid either collapse or the concessions of Market Communism by democratising their economy and still keeping a Communist model.

I still think the co-operative economy path would bring a huge amount of flavor to an area where it is missing.

**Comment by Bismarckingit** [comment]
So, economic collapse is not inevitable as the Soviets in the game.

You just need to be able to advance technologically faster than the modifiers can stack up.

I've managed to keep a healthy income of several thousand while curbing all of the corruption, and all spending sliders at maximum, with little to no tariffs without going market communist.

You just need to be careful and smart with how you go about the economy, and the modifiers won't be that bad of a problem.

**Comment by settintotrieste** [comment]
domper59’s events have dealt with these suggestions.
