### ISSUE TITLE
Education completely destroys my population

### ISSUE THREAD

**Issue by Devin616** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#408]
so, i'm playing as the soviet union, and right around the 1980's my education level hit 90%. and then my population growth went down to -20k for the next decade and is still around that level. i have every social reform and 8 national focuses which i am all of to increase immigration. still at -14k pop growth. i have 9 levels of educated society modifers and 4 levels of affluent society modifers, so my natural growth is negative. how do i fix this?? i have lost 30 million pop already, i went from 275m total to 249m total. nobody is leaving the country and the iron curtain was lifted in the 50's, i get about 2000 immigration and have managed to be the top destination for most of europe to immigrate to, but i'm still massively in decline. is there any way you can make sure natural growth can't go negative or add decisions like propaganda or something to increase pop growth? i can see the natalism decision but can't use it because i'm communist. i'm considering annexing china to keep my country from completely depopulating in 3 decades since they can't even supply their massive armies and i could probably roll right over them....

**Comment by 1infoteste** [comment]
You can enact Import Substitution Industrialization policy which gives a significant pop growth boost.

That said, demographic transition events have to be reworked. Countries in-game almost always end up with around half the population compared to their IRL counterparts by 2019. Affluent/Literacy pop growth debuffs are way too high. Also, post-industrialization boom events don't fire correctly.

**Comment by settintotrieste** [comment]
I've edited the Natalism decision to help address the issue.

**Comment by mpristave** [comment]
I never felt like I needed to have a education level higher than 50 or 60% and the population reductions seemed realistic ti me. 

Remember this is higher education level right? So 90% of the soviet population by 1980 would be holding BA/BS degrees? Sounds like that is really what would need to be nerfed.

I had the same problem as them. Just kept my higher education at a lower level and basically still was ahead in research because all the AIs were still lower.

**Comment by settintotrieste** [comment]
It is what it is
