### ISSUE TITLE
Middle East Civil War fixes and enhancements

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#41]
If ISIS wins the Algerian civil war (event 8000318, algeria.txt), there is no event to make it a theocracy. This results in strange consequences, especially if Algeria's government form has changed along the way.
![v2_1](https://cloud.githubusercontent.com/assets/8064135/24087869/87b0f85c-0cfa-11e7-9dd2-9a6dcac7e817.png)
  It is able to join numerous international communities, including the UN, and holds elections for the caliph.

As a more general problem, if ISIS exists at the beginning of the Syrian civil war (event 8014730, syria.txt), and Syria wins, the annex war goal leads to things like this happening:
![v2_2](https://cloud.githubusercontent.com/assets/8064135/24087902/dec4211e-0cfa-11e7-88d9-950ac9a3bc7b.png)
  I doubt even the pan-Arab republic would be happy with this one.

It should be a simple fix, just changing the war goal for Syria. It can either be acquire all cores, which will leave ISIS with whatever land they had, or something along the lines of a dismantle, as it makes sense that a surrender from ISIS would involve leaving all occupied land.

On that note, it is currently impossible for a great power to intervene against ISIS due to it being a Civil War war goal. If we want to keep it that way, we could add "call_ally" disabled in the war. Although, I'm not sure it makes sense to prevent a GP from intervening, given all the intervening they're currently doing.
  It could also be considered to simply give the GPs CBs against ISIS so they'll declare their own wars. This makes sense, as our modern great powers aren't exactly cooperating in Syria.

**Comment by settintotrieste** [comment]
Thanks for the bug report! This will need to be fixed. Ideally for now I prefer to keep to using the restore_order CB against ISIS. The problem with using a special CB for GPs is that they may end up stuck in perpetual wars when they declare war against a land locked ISIS in a nation that did not grant the GP military access. This can cause performance issues and perpetual mobilisation in those GPs. 

A compromise solution would be to give states in spheres of GPs and are neighbouring ISIS the intervention CB which is probably more realistic as well as currently the Syrian intervention is still mostly a proxy one.

**Comment by settintotrieste** [comment]
Syrian Civil War has been changed, Yemeni & Iraqi Civil War added as of 3cf26b0. Testing needs to be conducted on those events though.

**Comment by ARR8** [comment]
In addition to testing, the following the planned enhancements, copied from #80:

-  Houthi rebellion before the Yemeni civil war proper
- War outcome events only fire if intervention actually happened
  - Regional powers given the option to intervene still get notified of their intervention's success or failure even if they chose not to intervene. This would normally be fixed by relocalizing to remove mentions of intervention, but these events also have effects, so that is not so simple.
- More dynamic relation changes, like I did a little for Persian intervention (relations down with all the African Arab states instead of individually Egypt, Morocco, etc.)
  - Unfortunately, North Africa is in the Middle East rather than Africa, so this doesn't work. In general, the method of changing relations by listing every Arab country and doing them individually is not a good one. Possible solutions are to use neighbors, cultures, capital ownership, etc.
-  High immigrant push, simulate the refugee crisis
-  Similar changes and fixes as in #80 for the Syrian Civil War. There are still a lot of hardcoded elements that don't account for variability that I'd like to see become dynamic. The war itself is more complicated, so this will probably take longer.

Additionally, Saudi intervention in the Yemenese CW may end it almost immediately. It may be necessary to put a barrier between Arabia and Yemen such as the one that exists at the Himalayas.

**Comment by arandomperson5000** [comment]
If you want I could help you with this issue as I created both the Yemeni and Syrian civil war event chains for NWO. Also my username at the paradox forums is The Sneaky Top Hat.

**Comment by settintotrieste** [comment]
Sure, please lend your hand! I will greatly appreciate your help! Thank you very much

**Comment by ARR8** [comment]
@arandomperson5000 - That would be great! Keep in mind we changed the Yemeni civil war in #80, so give that at least a cursory glance. Let me know if you have any questions about it, and thanks!

@settintotrieste - I'm not working on this at the moment, so maybe it would be best to take my assignment off this in the mean time?

**Comment by settintotrieste** [comment]
@ARR8 Sure

**Comment by arandomperson5000** [comment]
Given the dynamic nature of CWE, this sets up a lot of interesting ideas for civil wars in the Middle East, for example lets just say in Egypt the Arab Spring gets a much harsher crackdown by Mubarak than in real life prompting a Egyptian civil war or in Bahrain where in an alternate timeline it suffers a small civil war between its Sunni ruling elite and its Shiite majority population. If the Shiites win Bahraini civil war it could install a Iranian friendly government in Bahrain dramatically raising tensions between Iran and Saudi Arabia with the possibility of provoking an international crisis or in a worse case scenario full blown war between Iran and Saudi Arabia.

**Comment by settintotrieste** [comment]
This is an excellent idea, it will be a great addition to the mod if you could get them into the mod! I will give you a free hand over the Middle East Civil Wars to improve it.

**Comment by ARR8** [comment]
It would definitely be good to use the Arab Spring more. Something to maybe take a look at: the factionalism mechanic, in event nos. 1412074-1214079 in Essential Events 4.txt, as a generic mechanic to end dictatorships and raise militancy within them.

**Comment by ARR8** [comment]
Important: to prevent the bug with ISIS joining international orgs, nations with above 25 infamy should have all such decisions hidden.

**Comment by ARR8** [comment]
Another problem I noticed, which I think is related to the generic civil war events: Sunni Arab patriots rose up in Iraq, which was Shia culture. Although they occupied most of the country, rather than attaining independence for Mosul as should have happened, they changed the government type and Shia Arab remained the primary culture.
