### ISSUE TITLE
Population of New York is wrong

### ISSUE THREAD

**Issue by toocool1** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#419]
NYC is the largest city in the US, and has always been. Why is LA larger than NYC? That's totally incorrect. It shouldn't even be bigger than Chicago. 

This proves this with sources to the US Census. If the population is multiplied by 4. LA has a population of 7 million in the US. LA has nowhere near that amount even today. It hasn't even passed 5 million. 

https://en.wikipedia.org/wiki/List_of_most_populous_cities_in_the_United_States_by_decade

**Comment by settintotrieste** [comment]
This has been solved
