### ISSUE TITLE
World Bank

### ISSUE THREAD

**Issue by echasovikov** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#42]
Can you help me, please? I was looking at world bank and similar financial institutions (dev_bank, imf) and found out that while once there was a way to move them between countries, it is currently broken. All the decisions to move them require special_drawing_rights country modifier, but there is no way to obtain that modifier aside from event 15606, and that event is triggered only and not referenced by any other decision or event. Is it just inactive legacy code from NWO or was the system disabled unintentionally?

**Comment by settintotrieste** [comment]
Those were NWO features that were disabled by me because they made no sense and did not function correctly. They have been superseded by the current rotating instituitons in CWE.
