### ISSUE TITLE
United Arab Republic without Egypt problem

### ISSUE THREAD

**Issue by elemento136** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#420]
Libya formed the United Arab Republic while I was playing as Egypt. I got an event asking if I wanted to join the UAR; I chose to stay independent. Some time later the UAR dissolution event triggers, but the event assumes that Egypt had formed UAR since it changes UAR into Egypt. This results in the ai UAR taking control of Egyptian territory while remaining as UAR. The Egyptian player gets moved to former UAR (Libyan) territory.

**Comment by settintotrieste** [comment]
Fixed in the latest Github patch (13/4/19)
