### ISSUE TITLE
Finally here with the General modifications

### ISSUE THREAD

**Issue by Bismarckingit** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#424]
I've finished the modifications for in game generals, as Vic2 cannot actually manage general traits that are decimal points.

[traits.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/3189129/traits.txt)

**Comment by settintotrieste** [comment]
Thanks, did you add any extra traits?

**Comment by Bismarckingit** [comment]
I didn't add any extra traits, considering that there were already so many.

These may need more work, though, as the bonuses can climb as high as +7 or +8 for generals.

**Comment by settintotrieste** [comment]
Added in latest Github commit on 17/5/19
