### ISSUE TITLE
Reorganize Syrian Provinces

### ISSUE THREAD

**Issue by me2189** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#426]
In the mod Syria contains 4 regions by default. I suggest to make it just two; Syria and Aleppo. I did it by editing region.txt file in map folder. You can see the file in attachment.

![Image](https://user-images.githubusercontent.com/50967433/58283700-9f7d8e80-7db1-11e9-8f4c-b30b31e4d75e.png)
[region.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/3214009/region.txt)

**Comment by semiimes** [comment]
False  : Trabizond
True  :  Trabzon

**Comment by settintotrieste** [comment]
Decided against reducing Syria’s state count to 2 as that will affect industry
