### ISSUE TITLE
It's me again, finally back with German additions.

### ISSUE THREAD

**Issue by Bismarckingit** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#427]
This isn't 100% finished, and honestly rather barebones, but this is a good start towards making the Germans a more fun country in the early game.

later additions to this will most likely expand the coup into what I originally intended for it, as well as adding unique revanchist decisions for the Kaiserreich.
[event_modifiers.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/3214353/event_modifiers.txt)
[germany.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/3214354/germany.txt)
[occupation_of_germany.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/3214355/occupation_of_germany.txt)
![Wilhelm III](https://user-images.githubusercontent.com/50720330/58290428-ae4f4b80-7d87-11e9-8472-a54c11f8f439.jpg)

**Comment by Bismarckingit** [comment]
(the image is for the events revolving around Wilhelm)

**Comment by settintotrieste** [comment]
Thanks, I add this into the mod
