### ISSUE TITLE
Rework brazilian states, events, decisions and terrain

### ISSUE THREAD

**Issue by Arthur2011o** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#428]
1-This image below shows the brazilian states and territories from 1941 to today
![image](https://user-images.githubusercontent.com/52299089/60301384-9bd8ac80-9907-11e9-99c2-66a87d404c71.png) (this one i've already done my self)
2-Add more Brazilian important cities tarrain like
Belo Horizonte
![image](https://user-images.githubusercontent.com/52299089/60301853-be1efa00-9908-11e9-9b4f-fca162f63f66.png)
Salvador
![image](https://user-images.githubusercontent.com/52299089/60301906-ddb62280-9908-11e9-8369-ba274e475b3b.png)
Brasilia 
![image](https://user-images.githubusercontent.com/52299089/60301992-16ee9280-9909-11e9-99f9-dc81bfb9b8b3.png)
3-Add events like
"I live the life to enter in history" about the suicide of Getúlio Vargas
"50 years in five" From Juscelino Kubitschek
"Plano de metas" From Juscelino Kubitschek
"Jânio Quadros give the biggest Brazilian honor to Ernesto "Che" Guevara"
"The renounce of Quadros" when Jânio Quadros renouced the presidence
"Goulart in China" The president João Goulart in a visit of PRC
"Goulart's Social Justice" The president's plan to reform the big land properties and nationalize the oil refiniries
"March of Family  with God for Freedom" the people's reaction Goulart's Social Justice
"Institutional Act n 2" The stablished indirect elections for the president of the republic and the bi-partidarism between ARENA and MDB
"Institutional Act n 4" The new constitution the constitution of 1967
"Institutional Act n 5" That gave unlimeted power to the president of the republic
"Pharaonic buildings and the economic miracle " The military government took money from BIRD and IMF to build huge structures like Itaipu dam, Tucuruí dam, Trans_Amazonic highway, Rio-Niterói bridge and the Nuclear Reactors Angra 1, Angra 2 and Angra 3
"Diretas já and the lost dacade" The economy was very bad and the people was claiming for the end of the dictatorship
"Tancredo Neves elected" The indirect election of Tancredo Neves ending the dictatorship
"Tancredo died" Tancredo Neves died before assuming the presidence so José Sarney assume his place
"The citizen Constitution" The new constitution of 1988
"Plan Collor and the painted Faces" The economy was so bad that people began to Riot aggaisnt the president's economic actions, and a corruption scandal of the Collor Family ending with the renounce of Fernando Collor
"Vote for the king" In 1993 happened a plebiscite for the return of the monarchy or maintainnig the republic
"Plan Real" The economic restructuring of Brazil with a new currency and the end of Hyperinflation
"Mensalão Scandal" The beginning of the corruption scandals
"2013 protests" Protest that began for the high prices of public transportation tickets
"Petroladrões" The beginning of operation car wash with the prision of Alberto Yussef
"2015-2016 impeachment riots" Riots pro Dilma Roussef and Counter Dilma ending with her impeachment 
"Molusco na Cadeia" ex president Lula is  Arrested for active corruption and money laudring
3-Decisions
put the Build Brasilia decision earlier, it was planned since 1822
Add the decisions to build the Furnas dam
Add the decision for Carajá's Mine
Add the decision for niobium exploration in Uberaba
Add the decision for Belo Monte dam
4-Terrain
Add the Cruls's square as a province and buid Brasilia there

**Comment by settintotrieste** [comment]
Mod development has stopped and so all outstanding issues will be closed.
