### ISSUE TITLE
State religions and other stuff

### ISSUE THREAD

**Issue by arandomperson5000** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#430]
Currently all countries in CWE have atheism/secularism as their default religion regardless of their government type, whether it be a democratic republic, a theocracy or a communist state. I kinda guess why this is the case is to simulate the world becoming more irreligious as time goes on. However it would be more accurate to give some state religions considering that states such as Saudi Arabia are very hostile to religious minorities while in others such as the Estado Novo and Francoist regimes of Portugal and Spain, the main religion in this case Catholicism was very heavily intertwined with the ideology of the state, largely as a backlash against secularisation policies pursued by their predecessors. 

To make it dynamic, any country can establish a state religion but only if Traditionalists have an absolute majority in the upper house whereas to largely secularise* their government the opposite must occur (Conditions for this could be different for Islamic countries in Asia and Africa). If possible, perhaps the religious conversion system can be tweaked to allow a country's population to become more irreligious over time despite its government having a state rleigion.

*Secularising your government in this case does not mean that the state religion is automatically abolished take for example both Denmark and Iceland have state religions but are in fact highly secular with most, if not almost all areas of the state more or less fully separate from any religion and both of their populations enjoy a very high level of religious freedom.

**Comment by settintotrieste** [comment]
There is already a desecularisation mechanic in the mod. If your religious policy is moralism then it will trigger the desecularisation event. The event checks for the religion of the primary culture in the capital and then sets the state religion to that.

**Comment by arandomperson5000** [comment]
Thanks for letting me know, I've only started to use this mod relatively recently so I wouldn't exactly be very familiar with many of the features. Currently I'm working to update the religious demographics of some countries and various orders of battles although for the latter I did notice that during the 1946 bookmark, some units such as artillery and mechanised infantry are only able to be recruited much later than it would historically would have been.

Also as a suggestion, perhaps two more unit types can be added in, cavalry and battleships. Despite being largely obsolete by the end of the Second World War, both of them continued to used for several decades after. It wasn't until 1955 that the last Soviet horse cavalry division, the 4th Guards Cavalry Division was finally disbanded and mounted infantry units were used in combat as late as the 1970s during the Portuguese Colonial and Rhodesian Bush wars. As for Battleships, there were around 42 of them still in service worldwide at the beginning of 1946 and most of them were retired during the late 1950s and 1960s, though there was somewhat of a brief revival in the US during the 80s with all 4 Iowa-class being reactivated and modernised as a part of the Reagan administrations's 600-ship navy plan.

In terms of how these units might work, a Cavalry unit might be useful as a relatively cheap mobile unit that's effective at fighting irregulars on difficult terrain while it wouldn't last long against a conventional force. Battleships on the other hand would be mostly able to beat smaller vessels relatively easily  at the start of a campaign, thanks to its strong hull and firepower. However the advent of guided missile ships in the 1950s will allow smaller ships like destroyers and cruisers to eliminate battleships from outside the range of its guns, thus making it mostly obsolete.

**Comment by settintotrieste** [comment]
It is an interesting idea however I prefer not to add in units that would become obsolete in the game because the AI won't know how to stop using them.

**Comment by arandomperson5000** [comment]
Yeah I definitely think that would be a bit of a problem, it would be extremely odd seeing an entire army just comprised of horse cavalry units if someone is playing very late into the twenty first century. There are two possible solutions to this problem that I could think of.

The first one is essentially substituting them with existing units considering that light infantry can pretty much fulfil the same function as cavalry while battlecruisers are quite similar to battleships in terms of uses and that the main reason why the Iowa class battleships were brought back into service and modernised was to provide an answer to the Soviet Kirov-class battlecruisers. Another possible solution is to simply force the AI to stop building them by somehow making them unrecruitable once a certain tech is researched although I'm unsure whether a command for that even exists at all.

As of right now, I'm currently working on updating the racial, religious and ethnic demographics of the U.S in both bookmarks to what they were historically, however I'm a bit confused on how large certain ethnic groups may be. Take for example Irish Americans, more than ten million people in the U.S self identify as being of Irish ancestry, yet much of this community have been assimilated into mainstream American culture for many, many decades now. Would it be best to represent this community as Irish culturally or instead as Anglo-American, leaving the label to exclusively refer to foreign born Irish immigrants.

**Comment by settintotrieste** [comment]
It is not possible to stop the AI from building a certain unit after a certain time. There is a way around the battleship limitation by using a decision to spawn Battlecruisers before the tech unlock date. So the US will start off with 4 Battlecruisers to represent the completed Iowa class ships and the USSR will get 4 by decision.

You can represent them as Irish or Irish-American in game.

**Comment by arandomperson5000** [comment]
Apologies for the lack of updates on my work on revising the demographics of the U.S, it has been quite difficult to find and analyse the necessary census and survey records. So far, I've mostly completed the pops for Hawaii, Guam, the Virgin Islands, Connecticut, Massachusetts, the Northern Mariana islands and American Samoa for both the 1946 and 1992 bookmarks and tried to make them as accurate as possible.

I'm also a tadbit confused on how there's now two Arabic culture groups, is this meant to represent two ways of creating a Pan-Arab state or are they just being tested on which group is better suited to the mod.

**Comment by settintotrieste** [comment]
No problem. Yes, the 2 groups are to simulate the 2 ways to form a pan Arab state.

**Comment by arandomperson5000** [comment]
I wished I had known earlier that there was a few pop generators for Vic 2 so at least I probably won't spending months just manually editing the pops anymore. It also allows me to edit the workforce demographics of a province or a region very quickly and easily, so what do you think of the idea of editing them to be more historically accurate like for example in the 1946 bookmark, around 73.46% of New Jersey's workforce are farmers or more generally employed in primary industries while in the 1950 U.S census, only about 1.65% of the state's employed workforce had occupations in the primary sector. Do you think a change would be beneficial or would it gravely affect the balance of the game.

**Comment by settintotrieste** [comment]
This is a good direction for the mod to take. Industry scores are wholly dependent on the employed craftsmen population size so if the cities are swamped with craftsmen then it would affect balance. Perhaps what can be done is to split the craftsmen into Clerks and artisans such that there aren’t too many of them (within a 10-30% range), or to adjust the populations of other major industrialised powers to keep everyone balanced?

**Comment by arandomperson5000** [comment]
Splitting up the craftsmen pops might not be necessary for the U.S at least as the census details for the workforce of states that I had looked at appear to be fairly diverse with New Jersey for example, around a fifth of it's workforce in 1950 were employed in manufacturing but I forget whether the base game makes craftsmen tend to cluster in regional capitals. 

As for the second option, it sounds like a good idea and I will try and find data on the workforce demographics of other industrialised countries.

**Comment by settintotrieste** [comment]
That’ll be great! Craftsmen are not state_capital_only so they won’t cluster.

**Comment by arandomperson5000** [comment]
So far, I've mostly planned out my approach on editing the demographics of the workforce at least in regards to the U.S. However, there are a few issues that I've noticed which may need to be rectified

- A few poptypes may need to have their ingame names changed as I feel like some of them are a 
  bit too restrictive or vague. Take for example, "Blue Collar Workers" which ingame exclusively 
  refers to low-skilled factory employees (aka Craftsmen), however the actual term refers to people 
  employed in a wide variety of jobs that require manual labour such as farming, commercial fishing 
  etc.

- In order to prevent massive unemployment among clerks and craftsmen in industrialised countries    
  ingame as they increase as a proportion of the workforce, the starting levels of factories on 
  startdates or the maximum number of workers a factory can employ may need to be increased.

**Comment by settintotrieste** [comment]
1. I agree, I will change the name to factory workers instead.

2. I prefer not to pre add factories at the game’s start because it tends to cause bankruptcies and to identify the correct factories to add is virtually impossible. The unemployment issue can however be resolved easily in game. Factories only, take 30 days to build and upgrade so the unemployment can be eliminated within 5 years. Each state can handle 80,000 unemployed workers a month and 960,000 a year.

**Comment by Outta-my-way-burrocrat** [comment]
@arandomperson5000 do you still have updated pop files for the US?

**Comment by arandomperson5000** [comment]
@Outta-my-way-burrocrat
Still here, I can't remember where I had put the files or whether I've deleted them by accident so I'll keep looking. Anyways I've a bit busy with college for the past few months and have been losing interest in this population overhaul so for the neat future, I think I might focus more on side projects rather than massive overhauls that require a lot of time and research.

**Comment by Outta-my-way-burrocrat** [comment]
@arandomperson5000 sorry, the letter commits made me think your account was pwned.

Do you think any of the pop and tech tweaks you committed to the NWO mod would fit the CWE mod?

**Comment by settintotrieste** [comment]
In the end factory size was increased to 20K and craftsmen were renamed to factory workers

**Comment by Outta-my-way-burrocrat** [comment]
@arandomperson5000 may I merge in your Chad pop tweaks and other unported stuff from NWO? https://github.com/simsulla/nwomod/commit/3f5bcb6f9c6954e9f76cd4c511960b81e536fafe#diff-9ea102cdeb575c03f0b6db40f369aef216c43a6edd21a112e6cace66ed348341
