### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ClaudezAlex** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#433]
Fresh install of Vic2 v3.04
-crashes at processing flags/flags since one week updates including 1.10
-old versions of 1.09 working

**Comment by settintotrieste** [comment]
You'll need to delete your flag cache in documents/Victoria 2/CWE

**Comment by settintotrieste** [comment]
If it doesn't work, try deleting the map cache

**Comment by ClaudezAlex** [comment]
Reinstalled Vic2 v3.04, deleted the whole cache folder my documents (including flags and map cache), when opening after deleting the cache folder goes in a loop between processing flags and loading flags for like 3 times and crashes

**Comment by settintotrieste** [comment]
You must somehow have a missing flag in your downloaded mod file. You can try downloading the mod from github again. If it doesn’t work, I’m afraid I don’t know how to help you further.

**Comment by ClaudezAlex** [comment]
I will try something. I didn't have this problem until some recent updates, maybe you can check the maps if they are on the current release altogether. Thank you so much for the patience!

**Comment by ClaudezAlex** [comment]
Maybe some others have the same problem

**Comment by settintotrieste** [comment]
I've found the cause. One flag was wrongly named nationalism instead of nationalist. I've updated the mod to fix it.

**Comment by ClaudezAlex** [comment]
Marvelous, thank you <3
