### ISSUE TITLE
New Revanchist contribution

### ISSUE THREAD

**Issue by Bismarckingit** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#435]
Here's a new decision for a second Japanese Empire that gives it claims on Korea. You may want to look at the file and make sure the coding for the cores being added is done properly (it was coded so that all Korean cores become Japanese ones, so it may have been done improperly) 

you may also feel free to change the infamy gained from taking the decision. i set it to 24.99 so that anyone who doesn't have any infamy doesn't immediately get dragged into containment wars should they invade Korea, but you can change that if you feel that is too unrealistic.
[Japanese militarism.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/3694550/Japanese.militarism.txt)

**Comment by settintotrieste** [comment]
Thanks for your contribution, I’ll add it in the next github release with an extra decision to claim Taiwan

**Comment by Bismarckingit** [comment]
I'll be adding many more revanchist decisions hopefully. I'm hoping for
revanchism to actually become a reasonable alternative to forming
superstates.
