### ISSUE TITLE
Wars, warscore and crises

### ISSUE THREAD

**Issue by torn1147** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#436]
Hi, I recently played a couple games and I noted a few things which really diminished the otherwise enjoyable experience of this amazing mod. 

Despite 4-5 runs through the game with different countries, I never saw the AI ever trigger a nuclear war when in control of a great power. Part of the reason for this is the warscore system - for battles, it accumulates far too quickly for relatively small battles so for example in cases like a major war between powers such as China and India, a few early battles quickly result in a peace settlement between them. This combined with the other issue of rare crises in Cwe leads to the very serious problem of great wars almost never happening. I don't know why, but flashpoint tension never crept up anywhere in the world aside from Tabriz and Bangladesh and that was it.

In the vanilla game, that widespread flashpoint tension and the resulting crises generate the world wars that make the game interesting from my point of view. And in the one great war I did see occur(over the flashpoint in Tabriz), the same warscore system resulted in a disappointingly quick end. I also noted that unlike the vanilla game, it was possible for me to build flashpoint tension regardless of my cores using the national focii system; I thought perhaps this mechanic was added as a way for players to generate world wars, but it rarely worked - the tension would usually go to 50.0 and back to 0.0 without explanation and on the rare occasion it did work, it didn't result in the usual independance crises, rather me(as the country) trying to acquire that state(which also didn't quite work).

Lastly, I would like to add that I would like to see countries with jingoistic parties in charge justify annexation casus belli against neighboring countries. Outside of railroaded events, there is very little conflict in Cwe, and this issue is the only thing holding me back from playing this further. 

I think this could be fixed by adjusting the flashpoint tension generation mechanics, the warscore system(particularly for great wars) and war justification for jingoistic parties. Thank you for this great mod. I hope to see it become even better in the future.

**Comment by settintotrieste** [comment]
crisis are blocked during the Cold War to avoid strange situations hence the flashpoint reduction upon 50. I replaced it with a special Cold War crisis system that works via event. I also edited the war goal criteria over the last few months to make wars more likely. In 1.11, there are a lot more small wars than in 1.09 or 1.10.
