### ISSUE TITLE
nuclear fire terra nullius?

### ISSUE THREAD

**Issue by Bismarckingit** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#440]
if you can help me make heads or tails of what exactly these events from Apocalypse mod say to make provinces disappear i might be able to make this applicable to nuclear wars in CWE
[TerraNullius.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/3747894/TerraNullius.txt)

**Comment by settintotrieste** [comment]
What it does is to transfer the provinces to a fake country tag which then annexes itself causing the lands to become empty

**Comment by Bismarckingit** [comment]
Ok. I'll try and make that into something useful

**Comment by settintotrieste** [comment]
Suggestion was converted into events that transfer control of provinces to rebels to keep the nuke damage modifiers
