### ISSUE TITLE
Suggestions for some historically correct party names in the 1946 start date

### ISSUE THREAD

**Issue by strategygamer2** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#443]
Hi,

as you know in the 1946 start date, quite a few parties use their modern, current names instead of their historically correct ones. I have some suggestions for historically correct party names in the 1946 scenario; I would suggest to use the official english name for the full party name and in brackets I would use the official abbreviation as written in the respective local language.

Finland:
Left Alliance should be called Finnish People´s Democratic League (SKDL)

Denmark:
Socialist´s people party should be called Communist Party of Denmark (DKP)
Liberals should be called Venstre (V)

Norway:
Socialist left party should be Communist Party of Norway (NKP)
Traditionalist party should be called Christian Democratic Party (KrF)

Ireland:
Socialist party should be called Irish Workers´ League

Switzerland:
Christian Democrats should be called Conservative People´s Party (KVP)
Communist party should be called Swiss Party of Labour (PdA)
FDP.The Liberals I would perhaps only call FDP since it was for before the merger for most of the time the bigger of the two parties

Belgium (there was no Walloon/Flemish split yet, so I would only have one national party for each ideology):
Christian Democratic & Flemish should be Christian Social Party (PSC-CVP)
Socialist party differently instead I would only have te Belgian Socialist party (PSB-BSP)
PvdA Communist Party of Belgium (PCB-KPB)
Flemish Liberal party should be called Liberal Party (PL-LP)

Also I have a few ideas regarding political Parties in Europe which concern more than one country:

1.  Political Green parties, which mostly form the progressive ideology in this mod, only started to come to existence in 1968 and the years after that. So until then, you could disable them and then have an event in the bigger western european countries which triggers around 1968 on the conditions that they are a democracy and have a certain amount of provinces which have the modifier highly developed. This event could be centered around the student movement and unlock progressive parties.

2. Nationalist parties did not start to have any electoral success or any other sort of relevance in european democracies at least until the 1970s.
Exceptions from this rule would be:
Italy with the Italian SocialMovement (MSI)
Austria with the Federation of Independents/FPÖ
Germany perhaps to a certain degree with the Socialist Reich Party (SRP), which had some electoral success in some regional elections but was banned before it participated in a federal election.

Even though you could argue that the last party was rather fascist than nationalist and the other two ones were mostly fascist at least in the beginning.

So if it is possible to mod that, I would suggest to disable all Nationalist parties with the exception of those mentioned above until the 1970s. 

3. 
Also there are a few cases of Christian parties such as in Belgium, which in the mod are considered as centrist instead of conservative. In case it would be technically possible to mod that, you could create an event which has a chance to trigger after the fall of the soviet union which leads to the former christian conservative parties shifting to the center.

Depending on how interested you would be with regards to parties i also would have a few other ideas for the future.

**Comment by settintotrieste** [comment]
Hi, thank you for your feedback. I will incorporate the name changes.

I am not able to do the other changes because of the limited ability to mod parties. In game, there are only 2 ways to make parties unavailable, not creating a party entry for that time period which affect all government types or disabling the ideology entirely. Both are unfortunately not good solutions because it will block players who want to go down the alt history route when there is no party for it and disabling the ideology would also have unintended effects as quite a lot of events and decisions reference those ideologies.

**Comment by strategygamer2** [comment]
Hi,

thank you very much. 

I understand your reluctance to change the current setup with regards to the nationalist parties. 

But would it be possible to let the progressive green parties come into existence only in around 1968 ?

As far as I can tell (my knwoledge regarding this might be insufficient though. because I mostly play the USSR or USA when using this mod, where green parties do not really play a role), there are not many fleshed out events or event paths regarding the progressive green parties anyways. 

Also, by only enabling the green progressive parties in 1968, there would still be enough time for players who are interested in alternative history regarding this ideology to play with this party for the second half of the cold war; after all a, green party winning an election and becoming part of a government in the early 1970s should be still early enough and enough of a deviation from history for people who are interested in this alt history path.

So I think enabling green progressive parties only in around 1968 would be a good compromise between histroical and ahistorical pathways,

**Comment by settintotrieste** [comment]
I feel that it’s best not to fix ideologies around any starting date. Progressivism as an ideology was around before WW2 but only exploded in popularity from the 60s due to the specific politics of the time like the Vietnam war and the economic slowdown etc. These events may or may not happen in game so it’s best to leave the ideology free floating.
