### ISSUE TITLE
Ivory Coast's captial issue

### ISSUE THREAD

**Issue by HKKNNT** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#463]
Currently is Bouake (1895).
Ivory Coast's captial from 1933 to 1983 is Abidjan(1892).
So need to change the province name of 1892 from Grand Lahou to Abidjan and move capital there.
https://en.wikipedia.org/wiki/Abidjan

**Comment by settintotrieste** [comment]
Added in commit 8e0b5a5
