### ISSUE TITLE
About event description

### ISSUE THREAD

**Issue by HKKNNT** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#471]
CWE's events have very detail event description.
I am working to mod the GUI so the event window can show it all without display error.
Like: [https://i.imgur.com/Po3Dxwy.jpg](https://i.imgur.com/Po3Dxwy.jpg)
The main problem is that it seems that the event description field only can display 2047 characters without display error. (The game could even CTD before start if you have 23XX~27XX+chars in eventdesc)
Display error example: [https://i.imgur.com/PYQoTXM.jpg](https://i.imgur.com/PYQoTXM.jpg)

Please shorten all event description which more than 2047 characters(include space)
eg: EVTDESC1400018, EVTDESC1400025

And I found that some event have ; within event description, so it won't display all after ; in game.
eg: EVTDESC1400018, EVTDESC1400026

**Comment by settintotrieste** [comment]
I prefer not to modify the existing event box UI because it’s of the right size. If it was any larger, it will look strange. It would be better to shorten those event descriptions instead to fit the current event box.

**Comment by HKKNNT** [comment]
CWE's event descriptions are valuable. It's not worth to shorten them too much.
(2047<is for stability)

How about this? [https://i.imgur.com/fG8Mkin.jpg](https://i.imgur.com/fG8Mkin.jpg)
I just change the height to a A4 standard scale. Didn't touch the width.
It can show the longest text with space for 5 option.

Current CWE with longest event desc: [https://i.imgur.com/3V5Okyu.jpg](https://i.imgur.com/3V5Okyu.jpg)
Yesterday's try: [https://i.imgur.com/rBRYmbo.jpg](https://i.imgur.com/rBRYmbo.jpg)

**Comment by settintotrieste** [comment]
I feel that it’s still too long. It might lead to clipping for players with smaller screens.

**Comment by settintotrieste** [comment]
I think what would benefit most from a larger box would be the major events, they are currently too small to fit anything meaningful in them. It would be better if it was of vanilla size.

**Comment by HKKNNT** [comment]
update:
1280x720 friendly version: [https://i.imgur.com/3fI6COg.jpg](https://i.imgur.com/3fI6COg.jpg)
1280x800 friendly version: [https://i.imgur.com/RQxoU2R.jpg](https://i.imgur.com/RQxoU2R.jpg)
both have space for 4 options.
And 720 version just 10% longer/wider than the original one.

I'll take a look to the major events box.

**Comment by settintotrieste** [comment]
Thanks. Maybe I’m too used to the vanilla size but the proportions don’t look too good, everything seems cramped up. I think the existing layout is optimal.

**Comment by HKKNNT** [comment]
For country event:
[https://i.imgur.com/sSdVFO8.jpg](https://i.imgur.com/sSdVFO8.jpg)
The most radical one, I believe everyone needs time to adapt it.
But I think it is the best: short, even didn't change the texture; can show all text till the game crash; button move higher to the screen center, no just easier to click but also can show more modifiers; a lot of space for options, more spacing between options, harder to click the wrong one.

For major(just the vanilla one with some spacing edit):
[https://i.imgur.com/oiFjjrL.jpg](https://i.imgur.com/oiFjjrL.jpg)

For Result screen:
Before: [https://i.imgur.com/4YDy9je.jpg](https://i.imgur.com/4YDy9je.jpg)
After: [https://i.imgur.com/f8tz9mP.jpg](https://i.imgur.com/f8tz9mP.jpg)

**Comment by settintotrieste** [comment]
I like the work on the results screen and the major event. Would it be possible to use the current major event design but just expand it to fit the vanilla size?

I'm afraid I have to reject the country event design because it would look too odd, especially when the event text is only one or two sentences long which there are many in the mod.

**Comment by HKKNNT** [comment]
ok, then country is for me.

Major retake:
[https://i.imgur.com/XYP6X9A.jpg](https://i.imgur.com/XYP6X9A.jpg)

**Comment by HKKNNT** [comment]
update
[https://i.imgur.com/ti5WtYV.jpg](https://i.imgur.com/ti5WtYV.jpg)

**Comment by settintotrieste** [comment]
That looks great, would be possible if the title text can be in the centre of the upper box?

**Comment by settintotrieste** [comment]
That’s great, I’ll add it to the mod, thanks
