### ISSUE TITLE
More interface update

### ISSUE THREAD

**Issue by HKKNNT** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#474]
Result 2.0:
[https://i.imgur.com/x2jgz5m.jpg](https://i.imgur.com/x2jgz5m.jpg)

Buliding:
Before: [https://i.imgur.com/suEEepm.jpg](https://i.imgur.com/suEEepm.jpg)
After: [https://i.imgur.com/dOE6ju5.jpg](https://i.imgur.com/dOE6ju5.jpg)

Budget and Topbar(not yet done):
Before: [https://i.imgur.com/OY37qSp.jpg](https://i.imgur.com/OY37qSp.jpg)
After: [https://i.imgur.com/jw2xr5V.jpg](https://i.imgur.com/jw2xr5V.jpg)

**Comment by HKKNNT** [comment]
Please feel free to leave any comments here.

**Comment by settintotrieste** [comment]
It’s great, thanks

**Comment by settintotrieste** [comment]
For the results screen, I prefer the flags to not have the faded effect.

**Comment by HKKNNT** [comment]
This?
[https://i.imgur.com/Duc8ksT.jpg](https://i.imgur.com/Duc8ksT.jpg)

**Comment by settintotrieste** [comment]
Yes, that’s good
