### ISSUE TITLE
Localisation suggestion for former German eastern territories

### ISSUE THREAD

**Issue by coldwarfan** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#476]
Hi,

the decision to rename Königsberg to kaliningrad should also include a name change of "Memel" to "Klaipeda" and "Gumbinnen" to "Gussew"".

Also I do not know whether it is a bug or whether it has not been implemented yet, but I have never seen the names of the former german territories in poland change to their polish names.

In case it has not been implemented yet, i would suggest:

Danzig = Gdansk

Köslin = Koszalin

Deutsch Krone = Walcz

Elbing = Elblag

Kolberg = Kolobrzeg

Allenstein =Olsztyn

Tuchel =Tuchola

Bromberg = Bydgoscz

Stettin = Szczecin

Posen = Poznan

Küstrin = would rather choose Landsberg which is also in this region and much bigger  (polish name Gorzow Wielkopolski)

Breslau = Wroclaw

Liegnitz = Legnica

Oppeln = Opole

Kattowitz = Katowice

Last but not least, after the fall of the Soviet Union, there should be an option for Russia to offer the return of Königsberg and Gumbinnen to Germany (historically the former soviet union showed intent to also include their part of former eastern prussia during the negotiations regarding the Two plus Four Agreement leading to german reunification, but germany rejected any talks regarding former eastern prussia).

Condition for such an event to fire should be that Germany is a democracy. Then there could be two options for germany to accept; the first one could be that they pay a large amount of money and have all their alliances cancelled (russia did not want any nato troops in nowadays eastern germany, so it would make sense that they would make even stricter demands in that regard if they were to return königsberg); the second option for Germany could be that they pay even more money but get to keep their alliances (after all russia certainly needed any money it could get after the collpase of the soviet union, so a certain amount of money might convince them  to act against their strategic interests and accept a nato presence in former eastern prussia).

**Comment by settintotrieste** [comment]
Thanks, I will add the name changes. There is already an event for the return of Königsberg.

**Comment by coldwarfan** [comment]
Ok great.

Also the starting name of „Dorpat“ in Estonia should be „Tartu“.

Ösel should be rather „Saarema“ ( Name of the island) or „Kingissepain“ (Name of Kuressaare, which is the biggest town on the island, during the Soviet period from 1952 onwards).

Swinemünde was given to Poland after ww2, so this province of eastern Germany should be rather named „Greifswald“ which is the largest town in this region.

Instead of „Prenzlau“ I would perhaps suggest „Frankfurt an der Oder“, which is the largest german city in the polish border region and should still be in the game province of current Prenzlau.

„Pritzwalk“ could be either „Potsdam“ or „Ost Berlin“ ( which could then when the reunification happens be renamed to „Potsdam“ by event).

**Comment by coldwarfan** [comment]
„Karlsbad“ in Czechoslovakia should be called „Karlovy Vary“. 

„Aussig“ should be called „Usti nad  Labem“; alternatively you could also choose „Liberec“ ( in German „Reichenberg“) which is in the same region but is and always was slightly larger.

„Troppau“ should be called „Opava“. Alternatively you could also have „Ostrava“ ( „Ostrau“ in German) also in the same region and a much larger city. However, despite their geographical proximity I think Ostrava, despite having historically some German inhabitants, was I think never considered a part of the Sudetenland unlike Opava/Troppau; so in case there are any events with regards to this then Opava is probably the best choice.

Then, with regards to the starting population of „Eisenstadt“ in Austria about 30% are Croatian. This area also historically has a sizeable Hungarian minority, which I think should also be represented in the game, because till ww1 this area belonged to the Hungarian part of Austria-Hungary. I do not know the exact demographics in 1946, but at least nowadays I think the Croatian minority there is much bigger than the Hungarian one. 
So perhaps as a setup in 1946 I would perhaps suggest 5% Hungarians and then you can either have 25% Croatians or 65% Germans.

**Comment by settintotrieste** [comment]
Thanks, I’ll implement some of these with a roll back function so the names will correspond to the occupying country.
