### ISSUE TITLE
Interface update: Pop screen

### ISSUE THREAD

**Issue by HKKNNT** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#482]
Seems the color of states/provinces POP number is fixed, so I change the button colors instead.
Please feel free to leave any comments.

Before
![before](https://user-images.githubusercontent.com/42631200/71663437-2fe07080-2d90-11ea-83bc-d315dffd8cc4.jpg)

After
![after](https://user-images.githubusercontent.com/42631200/71663439-31119d80-2d90-11ea-9b18-b880decb59f2.jpg)

**Comment by settintotrieste** [comment]
I find that the colour is too reflective. a flat grey would be better.

**Comment by HKKNNT** [comment]
This?
![v2_1](https://user-images.githubusercontent.com/42631200/71667490-47bff080-2da0-11ea-8cc1-b6d5ee38249c.jpg)

**Comment by settintotrieste** [comment]
I prefer if there’s no reflective effect

**Comment by HKKNNT** [comment]
retake
![v2_2](https://user-images.githubusercontent.com/42631200/71672195-426aa200-2db0-11ea-8e1a-a9326a587bbe.jpg)

**Comment by settintotrieste** [comment]
Looks good.
