### ISSUE TITLE
Map update

### ISSUE THREAD

**Issue by HKKNNT** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#484]
for Sichuan & Xikang, China

[provinces.zip](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/4015888/provinces.zip)

![v2_1](https://user-images.githubusercontent.com/42631200/71667975-2d871200-2da2-11ea-8291-6f9931f05b3c.jpg)

**Comment by settintotrieste** [comment]
Great, I approve of the changes. Thanks

**Comment by settintotrieste** [comment]
I just noticed that there is a odd shaped section in the Inner Mongolia state. If possible I think it will be best to separate it into the Shanxi state.

**Comment by HKKNNT** [comment]
They are already separate, but just have (nearly) same color.
Please help to update the map with above zip file since web version can't upload more than 25MB.

**Comment by settintotrieste** [comment]
Great, thanks
