### ISSUE TITLE
American politics dominated by moderates for early game

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#49]
[/u/EmperorPeriwinkle said:](https://www.reddit.com/r/paradoxplaza/comments/60hsio/a_few_things_about_the_cold_war_enhancement/)

I find the replacement of NWO's big tent ideology with centrist moderates interesting, but it means that the Usa is dominated by the Republican-Democratic coalition until the 21st century, when another issue finally takes hold of the USA. I'd like if Conservatism could be allowed in Usa again, as while in NWO big tent was supposed to replace it, if centrist moderates are supposed represent, well, centrism, conservatism needs to return to liven up elections.

**Comment by settintotrieste** [comment]
Thanks, I have done some tweaks to allow greater conservative support in America and the UK but more testing and tweaking needs to be done.

**Comment by ARR8** [comment]
Is that 4fad671?

**Comment by settintotrieste** [comment]
Yes

**Comment by settintotrieste** [comment]
I did a test game and now there is greater electoral diversity with moderates and liberals wining every now and then.

**Comment by ARR8** [comment]
From my test games, I think it would be good to tweak the rich strata pops to prefer conservatism over moderates, because moderates still dominate in countries without full voting rights reforms.

**Comment by settintotrieste** [comment]
Sure, I will apply the changes.
