### ISSUE TITLE
map with 1 new province

### ISSUE THREAD

**Issue by HKKNNT** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#490]
[provinces.zip](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/4048884/provinces.zip)

for Toyota War
https://en.wikipedia.org/wiki/Toyota_War

![v2_1](https://user-images.githubusercontent.com/42631200/72197598-01345b00-345e-11ea-9cda-4f41980de250.jpg)

**Comment by settintotrieste** [comment]
Thanks, I like it. Could you help me make a province for Anguilla?

**Comment by HKKNNT** [comment]
Ok, but wait few days, updating Mongolia now.
With splitted Saint Martin, perhaps.

**Comment by HKKNNT** [comment]
planing:
Ilemi Triangle
Sint Maarten
Penghu/Pescadores Islands 
Kinmen/Quemoy & Matsu Islands 
+
Anguilla

**Comment by settintotrieste** [comment]
Sure, no problem.
