### ISSUE TITLE
Socialism too popular in Europe and late-game

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#50]
[/u/EmperorPeriwinkle said:](https://www.reddit.com/r/paradoxplaza/comments/60hsio/a_few_things_about_the_cold_war_enhancement/)

Speaking of livening up elections, I'm at 2020, UK has been lead by the Labour party for all but a couple years in the 50s. France has being ruled non stop by the socialist party. The CDU has only beaten the SPD once and that's because of the Spiegel Affair event tanking them with a ruling party scandal modifier. Ironically the modifier stayed after the election and the event chain got to the point an election was triggered 2 years into CDU rule and the SPD won with a straight up PR majority. From that point the SPD may have lost 2 more elections, max, were it for my use of espionage. Once Die Linke became a party SPD has started alternating leadership with them, but non socialists aint ever winning in Germany. Socialists are straight OP the western world. You know how the centrist moderate monopoly in USA died? The Socialists winning every time between 2000 and 2020. I'm sure this is happening because blue collar worker Pops are massively socialist and the way industrialization works, it means socialists only get stronger as the game goes on. Also meeting needs is super easy for western countries, which increases the ideology support of the ruling party.

-----------

I will be submitting a few pull requests to do with this and #18 to make pops more right-wing in the face of terror attacks on the country as a partial solution.

**Comment by settintotrieste** [comment]
That's a good idea to have the terrorism events shift the pops to the right.

I have done some tweaks to reduce socialist support among craftsmen so as to allow other parties to have a greater chance of winning the elections. More testing still needs to be done though.

**Comment by settintotrieste** [comment]
More dynamic ideological alignment attempts to fix this.  aef0e33
