### ISSUE TITLE
Party ideologies and supported issues + political movements do not make sense

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#51]
[/u/EmperorPeriwinkle said:](https://www.reddit.com/r/paradoxplaza/comments/60hsio/a_few_things_about_the_cold_war_enhancement/)

Socialist ideology and parties are weird. I get why some are free trade and others protectionists, especially in europe where the divide is Pro-EU or anti-EU. But why is the SPD Lassize faire? why is the Labour party state capitalist the entire game? Especially when interventionism lets you build? Also in Original vicky 2 socialists didn't support political reforms by default as a balance decision, but it's patently ridiculous in this time frame. My Germany has gender laws stuck at role based and minorities at oppression in 2020. (/pol/ would be so hard) All movements have done is call for a shift from no state religion to secularism the entire game, with some armed revolts, but never enough militancy to allow me to move policy. 2020 and I think almost everyone is at role based and only USA and like one other country is at equal rights.

**Comment by settintotrieste** [comment]
As for socialist parties maintaining the same policy till the end of the game, it can only be handled via the addition of new parties to replace them at a specific time in the game. This will be quite laborious so I might not want to tackle that now.

What I can do is to allow socialists greater ability to pass political reforms at lower militancy.
