### ISSUE TITLE
Austria-Hungary Yugoslavian War

### ISSUE THREAD

**Issue by Bismarckingit** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#513]
I styled this particular war after the French wars in HFM for places like Quebec where there were multiple optional peace deals. I reused the KUK formation picture for simplicity. This may require a small amount of playtesting to ensure that
A. it works
and
B. the treaties give the territory you would actually expect them to give, like Status Quo Ante Bellum giving the pre-WW1 borders.

otherwise, i wouldn't suggest changing the war, as it will factor into later parts of a KUK campaign.
[protect czechs.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/4172405/protect.czechs.txt)

(yes, I reused the Czechoslovakia decision file for this. sorry if that's an inconvenience.)

**Comment by settintotrieste** [comment]
I added this in however as a simple irredentalist chain. This is because the scripting for sequential wars was too difficult. In this simplified chain, the KUK can gain cores on CZH and the Balkan territories which the AI can then choose to declare war for as per normal.
