### ISSUE TITLE
Import substitution rebalancing

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#52]
[/u/EmperorPeriwinkle said:](https://www.reddit.com/r/paradoxplaza/comments/60hsio/a_few_things_about_the_cold_war_enhancement/)

Import substitution is OP. My Germany is at above 40 million pops (which is 160+ million population) in 2020 with no reason to switch export focus. I should be taking penalties for doing this in a developed country with near 100% higher education

**Comment by settintotrieste** [comment]
This may be from an older version of CWE. In the current version there are overpopulation, higher education mechanics to reduce population growth. The import substitution growth has also been halved.

**Comment by ARR8** [comment]
> slower rate of promotion to craftsmen

Thanks, I didn't know about that. I think the reddit user didn't either, as that is a benefit as good as population growth, so I doubt that import substitution is OP.

The only thing I might change is edit the description for export substitution to point out that it greatly increases craftsman promotion, since the tooltip doesn't say. Unless it already says it somewhere?

**Comment by settintotrieste** [comment]
Sure, you may edit it but just a line referencing this at the top or bottom of the current description and if possible in yellow ideally.
