### ISSUE TITLE
Next map update preview

### ISSUE THREAD

**Issue by HKKNNT** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#520]
![v2_2](https://user-images.githubusercontent.com/42631200/74324748-74fdb680-4dc2-11ea-88eb-3397b8db8415.jpg)

**Comment by settintotrieste** [comment]
Great, I like it!

**Comment by HKKNNT** [comment]
[provinces.zip](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/4209465/provinces.zip)

Some minor border display problem happened in Hamburg, West Austria and West Bank

**Comment by settintotrieste** [comment]
I see
