### ISSUE TITLE
Culture bug, instead of french there is "noculture"

### ISSUE THREAD

**Issue by Camilli93** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#522]
As it in title.

**Comment by settintotrieste** [comment]
May I have a screenshot of the problem?

**Comment by Radical-Rust** [comment]
It may be a corruption in the localisation files, it happened to me as well.
Try copying everything from text.csv in a new text file, name and save it as text.csv, and replace the old file with the new one.

**Comment by Camilli93** [comment]
https://imgur.com/gallery/jhyvUdn

First of all : tried reinstalling Vicky(then update to 3.04), redownloading mod, reinstaling, cleared map cachce/all of documents folder. Also, text.csv works fine. Tried to change french localisation to something new, no effect. 

It must be something with common/cultures. I "fixed" it. with duplicating french line like this:

european_french = {
	leader = european
	unit = FrenchGC
	french = { # tag = FRA
		 #!religion = { catholic }
		 color = { 20 20 100 }
		 first_names = { Achille Adolphe Adrien Aimable Alphonse Amédée Antoine Armand August Augustin Charles Daniel Denis Édouard Elie Emmanuel Éttiene Eugène Félicien Félix Fernand François Frédéric Georges Guillaume Gustave Henri Hubert Hugo Jacques Jean Joseph Jules Julien Lazare Léopold Leroy Louis Lucien Matthieu Michel Napoléon Nicolas Patrice Paul Philippe Pierre Robert Thibaut Thierry Thomas }
		 last_names = { Anthoine "Baraguey d'Hilliers" Bazaine Billot Bonaparte Bosquet "Boué de Lapeyrère" Bouët-Willaumez Boulanger Bourbaki Bugeaud Caillard Canrobert Courbet Cousin-Mountauban Davout "de Bourbon" "de Castellane" "de Castelnau" "de Gaulle" "de Langle de Cary" "de MacMahon" "de Montaignac" "de Saint Arnaud" d'Orleans Dubail Dubois Duchêne Dupetit-Thouars Exelmans Foch Forey "Franchet d'Espèrey" Gallieni Gouraud Guillaumat Hamelin Harispe Hoche Hollande Humbert Jaurès Joffre "Le Pen" Lebouef Lyautey Macron Murat "Ney d'Elchingen" Nivelle Péllissier Petain Vaillant }
    }
    french = { 
		 #!religion = { catholic }
		 color = { 20 20 100 }
		 first_names = { Achille Adolphe Adrien Aimable Alphonse Amédée Antoine Armand August Augustin Charles Daniel Denis Édouard Elie Emmanuel Éttiene Eugène Félicien }
		 last_names = { Anthoine "Baraguey d'Hilliers" Bazaine Billot Bonaparte Bosquet "Boué de Lapeyrère" Bouët-Willaumez Boulanger Bourbaki Bugeaud Caillard }
    }
	wallonian = {
		 #!religion = { catholic }
		 color = { 190 90 20 }
		 first_names = { Albert Alexandre Alexis Alphonse André Antoine Auguste Barthélémy Baudouin Blaise Camille Clément Charles Constant Damien David Désiré Didier Edmond Édouard Emmanuel Émile Etienne Eugène Félix Fernand Feullien Florent François Frédéric Georges Gérard Gilles Guillaume Gustave Henri Hercule Hubert Ignace Isidore Jacques Jean Jean-Baptiste Jean-François Jean-Louis Jean-Jacques Joseph Jules Lambert Laurent Léon Léonard Léopold Louis Lucien Mathieu Maxime Maximilien Nicolas Olivier Pascal Patrice Paul Philippe Philippe-Joseph Pierre Pierre-Guillaume Sébastien Sylvain Théophile Victor Vincent Werner }
		 last_names = { Allard Barbanson Barthélémy Baugniet Beaucarne Berger Berthels Beyts Biver Blargnies Brialmont Bredart Cauvin Collet Cols Claus Clerix Coquilhat d'Arenberg d'Huart d'Omalius d'Oreye d'Oultremont David Davignon "de Baillet" "de Beaufort" "de Behr" "de Bocarmé" "de Bousies" "de Brouckère" "de Broqueville" "de Burlet" "de Celles" "de Chasteler" "de Coppin de Falaen" "de Croÿ" "de Decker" "de Dixmude" "de Gerlache" "de Grez" "de Hemptinne" "de Labbeville" "de Lannoy" "de Ligne" "de Leuze" "de Melin" "de Mérode" "de Pelichy" "de Quarre" "de Riquet" "de Robaulx" "de Rouille" "de Sauvage" "de Sécus" "de Selys Longchamps" "de Stassart" "de Stockem" "de Theux de Meylandt" "de Trazegnies" "de Trooz" "de Viron" "de Waha" Defacqz Deguise Delacroix "Desmanet de Biesme" Destriveaux Dethier Devaux Deville Dewandre Dhanis Dreze "du Bois" "du Bus" "du Pont" "du Val de Beaulieu" Dumont Fallon Fendius Figeys Fleury-Dubay Fleussu Forgeur Frison Fuchs Gendebien Goffint Henry "Huysman d'Annecroix" Jacques Joos Jottrand Lahure Lardinois "le Cocq" "le Hon" Lebeau Leclercq Lefebvre Leman Malou Marcq Marlet Masbourg Nagelmackers Nalinne Nothomb Orban Pétillon Picquet Pirmez Pirson Raikem Roeser Rogier Rouen Rouppe Seron Thonus Thorn "van Snick" Wahis Wangermée Wyvekens Zoude }
	}
	breton = {
		 #!religion = { catholic }
		 color = { 100 110 100 }
		 first_names = { Yann Yannic Pierre Jakez Elouan Frasez Jaoua Paol Segal Alain Henri Hoel Michel Theodore }
		 last_names = { "de Cornouaille" Karter Gallo Kergoulay Bellec "le Goff" Treguier Riou Morvan Peron Jezeguel Salaun "le Bihan" }
	}
	white_french = {
		 #!religion = { catholic }
		 color = { 168 195 255 }
		 first_names = { Narcisse René Èdouard Luc Letellier Théodore Louis Francois Auguste Joseph Pierre Luis-Phillippe Jean Gaspard Eugéne Èssioff Huguel Jean-Pierre Gilles }
		 last_names = { Belleau Caron "de St.-Just" Robitaille Masson Angers Chapleau Jotte Pantaléon Langelier Damasne LeBlanc Brodeur Perodeau }
	}
	occitans = { #culture doesn't exist
		 #!religion = { catholic }
		 color = { 110 110 50 }
		 first_names = { Narcisse René Èdouard Luc Letellier Théodore Louis Francois Auguste Joseph Pierre Luis-Phillippe Jean Gaspard Eugéne Èssioff Huguel Jean-Pierre Gilles }
		 last_names = { Belleau Caron "de St.-Just" Robitaille Masson Angers Chapleau Jotte Pantaléon Langelier Damasne LeBlanc Brodeur Perodeau }
	}
	union = FRA
}

Now I thought maybe it's some kind of sign/keyboard layout that windows from different countries can't read. I had a similar problem when I was making a mod for EU4 and tried to use something like "Ērānšahr". I quickly changed names/last names to "Test", but the problem still exists.

**Comment by Camilli93** [comment]
Solved! Thanks to Radical-Rust. Problem was not in the localisation files, but I decided to try your way with the cultures file. Open in notepad+, copied all to new file, saved, swap with original (file grew by 2 kb ) and everything works!
