### ISSUE TITLE
[BUG] Invalid population growth modifiers

### ISSUE THREAD

**Issue by cecillia-liebkne** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#528]
The below modifiers use 'population_growth', a local modifier, despite the modifiers being applied to tags in-game. In order to properly apply the effects, they should be replaced with their tag-scope counterpart, 'global_population_growth'.

>eec
>communist_bloc_leader
>democratic_bloc_leader
>communist_bloc
>democratic_bloc
>independent_bloc

A bit of a side note, I'm not sure what indentation style this mod is working with, but it is absolutely awful.

**Comment by settintotrieste** [comment]
Thanks. There’s no indentation style for the mod. I format it in a way that is easiest for me to read and edit in wordpad.
