### ISSUE TITLE
[BUG] Issues with modifiers

### ISSUE THREAD

**Issue by cecillia-liebkne** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#529]
I.
>Currently, a considerable number of event modifiers attempt to use 'unit_start_experience', an invalid modifier that has no effect. It should be replaced with 'land_unit_start_experience' and 'naval_unit_start_experience'.

II.
>'unit_start_experience'/'land_unit_start_experience' scale from 0-100, not 0-1, yet there are many instances of their use in which the modifier is a decimal number like 0.1, which provides a negligible effect, and is assumedly due to a misunderstanding of how the modifiers work. It is recommended that such values be recalibrated.

III.
>'communist_bloc_leader', 'democratic_bloc_leader', 'communist_bloc', 'independent_bloc', 'wahhabism', 'military_reform', 'interpol', 'un_resolution_veto', and etc. are applied at tag-scope but uses 'pop_consciousness_modifier' and/or 'pop_militancy_modifier', local scope modifiers that currently have no effect. They should be replaced with tag-scope counterparts such as 'global_pop_consciousness_modifier' or 'core_pop_consciousness_modifier', etc..

IV.
>'israeli_military_genius' is applied at tag-scope but currently uses 'population_growth', a local scope modifier. It should either be changed to a global counterpart or outright removed, as the idea of doubling a tag's population every month is extremely silly.

Also, I highly recommend the usage of a proper text editor, like notepad++ or something. Wordpad and the such are meant for documents, not plaintext files. It also has multiple breaks with convention for other text editors, such as its 8-space tabs. I won't push this any further if that is truly what you prefer, however.

**Comment by settintotrieste** [comment]
Thanks, I've corrected the errors listed in this issue. I take your point and will use notepad ++ from now on.
