### ISSUE TITLE
More varied ideologies, esp. for communism

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#53]
[/u/EmperorPeriwinkle said:](https://www.reddit.com/r/paradoxplaza/comments/60hsio/a_few_things_about_the_cold_war_enhancement/)

I like the Market Communism/Communism split, Every country, especially the USSR should get a market communist party.
  I'd like ideologies activated over time, actually. I'd like if every major era had a set of ideologies unlocked. Market Communism should unlock in the 1980s, for example.

[/u/bfmv24 said:](https://www.reddit.com/r/paradoxplaza/comments/60hsio/a_few_things_about_the_cold_war_enhancement/df6sels/)

Relating to this, I think it should be included from the beginning because this was a huge sticking point between Tito in Yugoslavia and Stalin in the USSR.

**Comment by settintotrieste** [comment]
Adding a market communism party will be difficult as I have to manually add the parties to every country file so I will just add the party to the Soviet satellite states for now. I will leave market communism avaliable from the beginning.

**Comment by ARR8** [comment]
Concerning the second point, here is a map of all the ideologies currently in the mod:

| | A<br />Always support political reforms | B<br />Support political reforms with militancy | C<br />Support political reforms but revoke with militancy | D<br />Support or revoke political reforms| E<br />Revoke political reforms but support with militancy | F<br />Revoke political reforms with militancy | G<br />Always revoke political reforms | H<br />No political change
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| **1 Always support social reforms** | Progressive | Socialist | | | | | Communist<br /><br />Market communist
| **2 Support social reforms with militancy** | Liberal | | | | Populist
| **3 Support social reforms but revoke with militancy** |
| **4 Support or revoke social reforms** | | | | Moderates w/ militancy | | | | Nationalists if in power
| **5 Revoke social reforms but support with militancy** | | Conservative
| **6 Revoke social reforms with militancy** | |
| **7 Always revoke social reforms** | | | | | | | Traditionalist
| **8 No social change** |

To keep it symmetrical, there is room for ideologies in A6 and D8 to counter communists and nationalists, respectively. Some possible ideologies that are not strictly represented are pirate parties (possibly considered progressive), libertarians (possibly liberal), anarchists (relevance debatable), or single-issue parties (difficult to implement).

Personally, I think this and the other political issues should be milestoned for 1.07, since there are already major features planned for 1.06 and these will require a lot of rewriting and testing.

**Comment by settintotrieste** [comment]
Thanks however I am not sure if I want to add more ideologies because I prefer to avoid huge changes that can involve editing all the masses of country files to add new parties with the possibility of destabilising what was already done up to this point such as review multitudes of decisions and events to consider the new ideologies. I think the current spread of parties is adequate to not need more.

**Comment by ARR8** [comment]
Got it, and I agree. Although, there is something to be said about the part of vanilla vic2 that would unlock parties every couple of decades, and I think that's what the user who posted that comment was referring to.

**Comment by ARR8** [comment]
Addressing the original point:
How would you feel about a new mechanic for communist states where the "party leaders" meet and determine the direction for the nation? i.e. between status quo communism, market communism, and democratic socialism, chosen automatically based on the support for each among the upper strata of the population.
  Each would give new options: e.g. a vassal or sphereling of a communist GP that chooses to change the status quo will create a Tito-Stalin-esque split/a rebellion like the 1956 Hungarian Revolution and be excluded from the bloc/forced back militarily, or a GP choosing a new ideology will split from another communist GP, dividing the eastern bloc (think Sino-Soviet). Otherwise, without any diplomatic factors, it is a way to take the country in a new direction.

Event would push support for ideologies toward one or the other, especially in countries where this happened historically, such as Yugoslavia leaning toward Market Communism if Tito is allowed to push his reforms, (partial for #55) but also with generic events that fire for all communist dictatorships.
  The congress/plebiscite itself would be fired automatically on historical events or generically at a certain point in the game like the Socialism with Characteristics decision currently present. This point would be a very trying time for the eastern bloc.

This would address the points the users posted in the original issue, and create ideological splits that add flavor to the eastern bloc. One of the key improvements is there would be a reason, as the communist bloc leader, to be more selective with who you let in to the bloc, and keep social democracies at a distance, as the USSR did. Currently, it is a little strange that you get a couple of revolutions in your closest vassals as the USSR but your farthest spherelings remain loyal communists forever.

This would create ideological tension among the communists of the world such as that which existed in the cold war but is not really represented. Additionally, it would give players an advantage to communism other than the planned economy, as the events would likely offer a benefit in addition to an opinion shift, and open a political layer to gameplay, such as that which exists for democracies in the form of elections.

I'm open to any feedback. There is a downside to this, and that is that it would no longer be possible to appoint parties as a proletarian dictatorship, but, as this is a sort of replacement, it probably makes sense to disable.

**Comment by settintotrieste** [comment]
This is an excellent idea! I love it. Please do go ahead with this.
