### ISSUE TITLE
[BUG?] Potential issue with 'local_factory_x' modifiers

### ISSUE THREAD

**Issue by cecillia-liebkne** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#530]
I would like confirmation on this, but it seems that 'local_factory_x' modifiers, including throughput, output, and etc. do not actually work. They show up on the province-view interface, but in the actual production interface, hovering over the factories' outputs make no mention of said modifiers at all, and do not seemed to be influenced by them either. There is the sole exception of infrastructure/railroads, but I would not be surprised if they were specifically hard-coded to do so.

This could potentially mean that a huge swath of event modifiers in the mod are not working properly, such as the 'exportfocus' modifier, or ones related to development. If confirmed, it could potentially impact a lot of other mods as well, as even NNM and vanilla uses them.

---

Misc.

>'sterling_area' and 'franc_area' uses 'administrative_efficiency', which is a tech-scope specific; they should be changed to 'administrative_efficiency_modifier'.

>Province 16 (Gyeonggi, formerly Glenora) has not been properly updated for its re-designation from Canada to the Korean peninsula. It should be removed from 'inhospitable_climate' from map/climate.txt and the terrain in its history file be changed to something more appropriate.

**Comment by settintotrieste** [comment]
I see, this is a big problem if true. Could it be that the actual effect is divided by the number of provinces in the region?

**Comment by cecillia-liebkne** [comment]
No. The problem seems to be that factories run on a different scope entirely, and province level modifiers dont' seem to be able to interact with it. Even infrastructure isn't being directly applied; it seems to be hardcoded to simply take the values and then apply them from elsewhere in the code.

**Comment by Mitusonator** [comment]
@settintotrieste
If I may write something without making another thread; strata income modifier also doesn't work, oh and be carefull when applying goods demand or needs modifiers on province cos they actualy apply on the whole country and can stack if multiple provinces are affected.

**Comment by settintotrieste** [comment]
Strata income modifiers do work. I’ve tested them myself a few years back and I did see a change in income.

**Comment by settintotrieste** [comment]
There are too many modifiers to edit so it shall remain
