### ISSUE TITLE
Arab-Israeli war resolution

### ISSUE THREAD

**Issue by devinity1337** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#532]
After I won the Arab-Israeli war (Israelis won) Jordan controls most of Israel including Nazareth, Beersheba, Auja, and Ashkelon. 

I was unable to add these areas as a war goal because I was forced to take "status quo".

**Comment by settintotrieste** [comment]
The first Arab Israeli war only allows status quo because that was what the Israelis were aiming for. It was a war to avoid annexation by the arabs. In 1.11, I applied a fix to create historical borders if Israel wins.

**Comment by devinity1337** [comment]
Ah I have 1.05. I will try 1.1
