### ISSUE TITLE
Arab Israeli War Issue (version 1.11)

### ISSUE THREAD

**Issue by devinity1337** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#533]
I played two games, once as Saudi Arabia observer and the other as UK.

In the first game, Israel and Palestine get released by UK and are puppet states. No war occurs.

In the second game, Palestine gets automatically released in 1948 and no war occurs either. I did not push the white paper and allowed unrestricted Jewish immigration.

Is there a particular decision tree that determines these outcomes or is it a bug?

**Comment by settintotrieste** [comment]
The UK’s decision in the independence chain determines the outcome. In the historical choice, the war does not start immediately to allow PAL and ISR to organise themselves for war. It would usually fire after 1 month.

**Comment by devinity1337** [comment]
Thanks, testing

**Comment by devinity1337** [comment]
Still bugged. Finally got Israel to form but after the war it is missing cores in many areas and they go to Jordan.
![image](https://user-images.githubusercontent.com/7354486/75809156-faa4ce80-5d90-11ea-94c3-fcb65ae7acae.png)
