### ISSUE TITLE
tank sprites

### ISSUE THREAD

**Issue by Nemesis5002** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#545]
I don't know if I'm the only one having this, but the HOI 3 tank sprites included in the mod didn't show up for me and I continued to see the WW1 sprites from standard Vicky 2. I went looking around and found that in the base game tanks are stored in a separate "Tanks.gfx" file in the interface folder, when taking the Tank sprites out of the "avatars.gfx" file and putting them in their own "tanks" file, the sprites did show up correctly, so perhaps this can be implemented if anyone else has this problem too. 

(and just a thumbs up for all the work put in this great mod ;) )

**Comment by settintotrieste** [comment]
Thanks, could you help me do a fix for this via pull request?

**Comment by Nemesis5002** [comment]
I was able to do it in two pull requests separately, couldn't figure out how to make it work in one, first time editing on GitHub. I hope that's alright?

**Comment by settintotrieste** [comment]
Yep that’s fine
