### ISSUE TITLE
EU getting infinite prestige

### ISSUE THREAD

**Issue by mpristave** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#549]
In this recent game of mine Russia became the EU and they are constantly passing "Europeon Union a Community of Equal Nations" getting insane prestige.

**Comment by mpristave** [comment]
They might be passing other things as well as their daily prestige is going higher than what that single decisions would give.

**Comment by settintotrieste** [comment]
Could I have a copy of that savegame?

**Comment by mpristave** [comment]
www.pvpchamps.com/Indochina2033_06_13.rar
