### ISSUE TITLE
My having the SDI prevents nukes from functioning at all. 

### ISSUE THREAD

**Issue by mpristave** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#550]
I developed the SDI and went to war with china. Had a save before and after SDI development. 

Nuking before it functions correctly if I wait a month for it to develop if I use it after the chinese gets hit exactly 0 times.

**Comment by mpristave** [comment]
It's definately seeing the ling

NOT = { OR = { has_country_modifier = abmlow has_country_modifier = abmmedium has_country_modifier = abmhigh }

as applying to china.

**Comment by settintotrieste** [comment]
Does China have low nuclear capability and you have high ABM?

**Comment by settintotrieste** [comment]
I see the problem, the condition was put in the from instead of this bracket
