### ISSUE TITLE
New music for China and Japan

### ISSUE THREAD

**Issue by TemporaryAccs** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#552]
### Japan Song ###

song = {
	name = "Japan.mp3"

	chance = {
		modifier = {
			factor = -1
			NOT = { tag = JAP }
                }
	}

}

### China Songs ###

song = {
	name = "China 1.mp3"

	chance = {
		modifier = {
			factor = -1
			NOT = { tag = CHI }
                }
		modifier = {
			factor = -1
			NOT = { tag = KMT }
                }
	}

}

song = {
	name = "China 2.mp3"

	chance = {
		modifier = {
			factor = -1
			NOT = { tag = CHI }
                }
		modifier = {
			factor = -1
			NOT = { tag = KMT }
                }
	}

}

[Music.zip](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/4464145/Music.zip)

**Comment by settintotrieste** [comment]
Added in separate git repository
