### ISSUE TITLE
straight GP flags

### ISSUE THREAD

**Issue by Nemesis5002** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#555]
I don't know whether this was a choice by the developers but in CWE, most circular flags were replaced by a rectangular variant, the GP screen was an exception though. Since I preferred rectangular flags to round ones, I decided to change the ones on the GP screen as well for my own copy, thought I'd share it here, if you want, I can upload the files I edited for it to look like this? :)

![screenshot](https://user-images.githubusercontent.com/23165197/79336585-49af5900-7f24-11ea-9be4-de0f8e39cce8.png)

**Comment by settintotrieste** [comment]
I chose to keep the circular one for the GP screen since it seemed to fit the UI better. I prefer to stick to the circular one though
