### ISSUE TITLE
Crash at "Creating textures for Quad 1894"

### ISSUE THREAD

**Issue by BayLeafGuy** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#562]
The game crashes at "creating textures for quad 1894". Already cleaned cache.

**Comment by settintotrieste** [comment]
Have you tried deleting the cwe folder in documents? If that doesn’t work, I’m afraid I can’t fix the problem.

**Comment by BayLeafGuy** [comment]
I deleted the folder, and the game now shows a pop up saying: The exception unkown software exception (0x40000015) ocourred in the application in the local 0x0000000000E6AB2E.

**Comment by settintotrieste** [comment]
Do you still have the cwe file in programs?

**Comment by BayLeafGuy** [comment]
Yep.

**Comment by settintotrieste** [comment]
I did a test on my end earlier today and I could not replicate your issue so so it seems there is some problem in your files that I’m unable to fix unfortunately. You can try asking on the CWE discord to see if anyone there has experienced the same thing and managed to fix it.
