### ISSUE TITLE
Post independence election

### ISSUE THREAD

**Issue by TK3600** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#568]
When request independence decision fired, absolute monarchy gets election event fired, which is a problem. Monarchy should not have elections. I ended getting stucked on election forever.

**Comment by settintotrieste** [comment]
The code does not call for an election. Do you happen to have a screen shot of the problem?

**Comment by TK3600** [comment]
I was not in an election techincally, but I am getting violent election modifier and it wont go away.

**Comment by settintotrieste** [comment]
The modifier’s conditions stipulate the need for election = yes so it should disappear after the election. One thing to note is that as it is a triggered modifier, it only disappears or applies at the end of each month.
