### ISSUE TITLE
Adding DaQing oil field in China.

### ISSUE THREAD

**Issue by TK3600** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#575]
Currently DaQing is merged with qiqihar in the state heilongjiang of china. DaQing has the 4th largest oil field in the world and the biggest in China. I believe based on the critical strategic value of the province it deserves to be added.

**Comment by settintotrieste** [comment]
I prefer not to add new provinces due to the complexity of doing so. I’ll change the current province RGO to oil.
