### ISSUE TITLE
Map error in virgin island?

### ISSUE THREAD

**Issue by TK3600** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#585]
It seems to be in venezuelan coast on the map but ship move as if it is on eastern Carribean.

**Comment by Outta-my-way-burrocrat** [comment]
Someone else has confirmed that this is a bug @settintotrieste do you still need help fixing it?

**Comment by settintotrieste** [comment]
Yes, I still need help for this bug.

**Comment by Outta-my-way-burrocrat** [comment]
I think someone has already patched this bug but I cannot remember who. The province is incorrectly colored 14,202,252, the same as Venezualan Gulf in definition.csv. There is an unused province definition for Lesser Antilles.

**Comment by Outta-my-way-burrocrat** [comment]
The province can be fixed by painting the province RGB 18;202;252 using a program like Paint.net. I've patched it in my game and can PR the fix if nobody else wants to.

**Comment by settintotrieste** [comment]
@Outta-my-way-burrocrat yes please, thanks!

**Comment by Outta-my-way-burrocrat** [comment]
@TK3600
