### ISSUE TITLE
Communist South Africa does not end apartheid

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#6]
On 1.05, AI South Africa consistently takes a decision to make Black Anglo the dominant culture (majority rule, cpc_SAF) upon regime change yet keeps the apartheid modifier and the Bantustans.
Will submit possible fix.

Additionally, black anglo does not seem to be very common in South Africa, maybe "Coloured" should be added as accepted?

**Comment by settintotrieste** [comment]
Thanks for the help! I will add it to the mod.

**Comment by ARR8** [comment]
No problem!
On second thought, looking at the names and category for the Coloured culture, it seems like a stand-in for a generic non-tribal South African, so I would personally leave them to be assimilated. Your call, of course.

**Comment by settintotrieste** [comment]
Thanks, for now I will leave coloured to be assimilated.
