### ISSUE TITLE
Right-wing bias in the Total Fertility Rate event text

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#611]
" EVT_22602_DESC;The total fertility rate (TFR) of a population is the average number of children that would be born to a woman over her lifetime. Replacement fertility is the total fertility rate at which women give birth to enough babies to sustain population levels 2.0. Literacy and a secular lifestyle reduces growth. Sex education has had a great impact on birthrate. **Feminism has won its fight, as far as the birth rate is concerned, as well as the great battle in Western politics in enabling kids to listen to the message of feminism and understand modern medicine. Now, our population has commenced the low march into the silent night of death and extinction. Eventually, we must encourage immigration to keep our population size**.;;;;;;;;;x
 "

Does the anti-feminist white genocide-y fluff represent the intended narrative of the CWE mod?

**Comment by settintotrieste** [comment]
This is definitely not the view of CWE. This event was Imported from nwo which has a lot of weird shit. Thanks for pointing this out to me, I’ll remove the inappropriate paragraph.
