### ISSUE TITLE
2019-2020 Corona Virus events?

### ISSUE THREAD

**Issue by lucas4114** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#612]
Could there be an event that happens around 2019 (+- a few years for randomness) that triggers the Corona Virus and gives a large debuff to economic growth to all countries? Maybe it starts in Wuhan (or a random Chinese province) and it begins to spread to other nations randomly. There could also be a decision to close borders and the faster it's done the less severe the virus becomes if it hasn't yet spread to your nation. It would mainly effect politics and economics, the effect on pop growth should be very small if at all. Border policy also will also have an option to be changed back to normal after the virus, but can also stay in place after the virus (for any potential authoritarian countries.. Though this is just projection into the future.)

**Comment by settintotrieste** [comment]
This is already in the mod under the revamped viral pandemics system, including the coronavirus.
