### ISSUE TITLE
Social reforms in Brazil

### ISSUE THREAD

**Issue by Otto-Fon** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#615]
![reformas](https://user-images.githubusercontent.com/68921125/88704511-8cb4c700-d0e4-11ea-8dd4-ae3be9a635e4.png)

Social reforms in Brazil at the beginning of the game are very wrong. Although Brazil under Vargas created labor legislation, it is conservative and "populist" in this period of Brazilian industrialization and can be better represented in another way in the game.

The most underrepresented retirement for sure is 6 hours of work in the "Wage and Work" tab. It should have been 8 hours, since the previous one is "Unregulated" and during Vargas' reforms the working hours were set on May 4, 1932 to 8 hours.

The "Pensions" tab is also very wrong. "Good Pensions" represents pensions as high as possible, something far from the reality of Brazil in the post-war period. I believe that the most correct should be "Trinket Pensios" because the reach of people was very limited and included only civil servants.

Another misguided tab is "Security". "Exellente Security" represents a complete civil protection, police and other apparatus and Brazil was far from it, any country at that time, in fact. "Basic Security" is much more suitable.

In "Health Care", although Brazil has some health institutions, the overwhelming majority of them were private, religious or philanthropic organizations. So it should be "Primary Health Care" or even "Private Health Care".

In "Regulations" using the same argument about working hours and labor reform in the Vargas era, I believe it is better for reform to be "Some Regulations" because this part of labor legislation is largely neglected.

The "Unemployment" tab should also be fixed because subsidies were only added to unemployed people under the guarantee fund system in 1966 in the country. Therefore, the best reform to represent this would be "No Subsidies".

Finally, there may be a debate on the "Social Service" and "Education" tab, but the ones mentioned above by me are very urgent and I believe that anyone who has already done a campaign in Brazil found them very strange.
I hope my analysis helped.

**Comment by settintotrieste** [comment]
Thanks, I have done the changes. Could help me with the 1992 or 1950 reforms for Brazil too?

**Comment by Otto-Fon** [comment]
Of course it will be a pleasure.
