### ISSUE TITLE
Suggestion: cyber warfare beyond neighboring states

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#62]
I really like the new cyber warfare changes, especially the policy being determined by war policy. However, I'm not sure how useful it is limited to neighbors, especially for America. Much of the cyber warfare that we have seen in real life involves great powers against other great powers, such as Russia against the USA recently or many past instances of China against the USA. Possibly the most famous cyber attack was Stuxnet, the joint American-Israeli virus deployed against Iran's nuclear program.

The attack decisions could possibly include an extra clause for other great powers and target those, maybe in addition to neighbors. Also possibly, an extra CW focus could be added for nuclear GPs, checking for relations with any state currently developing nuclear weapons to sabotage their efforts. I'm not sure how CW partnerships could be implemented; perhaps, while preparing for an attack, a random ally gets an event to offer assistance and shorten the preparation time.

**Comment by settintotrieste** [comment]
Thanks, this is a good idea. I will add another scope to target great powers as well. The cyber attack on states developing nuclear weapons is also a good idea, I will add another CW option for that. The partnerships would be a bit difficult to implement by reducing preparation time as it is via a country modifier. What could be done instead is to allow such partnerships to allow the free targeting of another country but with the same amount of preparation time.

**Comment by ARR8** [comment]
A subsequent minor suggestion: economic attacks should destroy some levels of infrastructure in random states, to signify needed repairs to network systems.
