### ISSUE TITLE
Mahabad is misplaced and its provinces stretch too far East

### ISSUE THREAD

**Issue by Mouseasel** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#620]
I noticed that the nation of Mahabad may be misplaced, and maps I've seen seem to confirm my suspicions. I will post them here to show what I mean and point out the suspected error.

Below is an image of the Mahabad and Azerbaijan as they were IRL, as well as an image of Kurdish inhabited areas.
![Republic_of_mahabad_and_iranian_azerbaijan_1945_1946](https://user-images.githubusercontent.com/68358654/89357810-94014500-d68f-11ea-82bb-26d878a62a94.png)
![Mahabad](https://user-images.githubusercontent.com/68358654/89357899-c612a700-d68f-11ea-9eea-65c8928f29e7.jpg)

Notice that while both of these maps point to Mahabad  _owning the province of Mahabad_ in game, they do not as demonstrated here in this image of a fresh game. Additionally, they do not have a core on the province of Mahabad.
![42960_20200804201334_1](https://user-images.githubusercontent.com/68358654/89358068-551fbf00-d690-11ea-90c1-1388cd7905eb.png)

I would suggest giving Mahabad the province of Mahabad to fix this and making it their capital (if it was).
Also I would like to suggest **BOTH** the provinces of Mahabad and Khvoy be cut in half, as they seem to expand much to far eastward.
Lastly, it seems Khvoy wasn't controlled by Mahabad but rather Azerbaijan, so maybe a new province should be created in the north for Mahabad as well?

Not suggesting they need to be made exact ofc, I think it would be preferable if Mahabad still controlled one side of the lake and Azerbaijan the other.

**Comment by Outta-my-way-burrocrat** [comment]
I'm partway through tweaking these provinces. Does anybody have info on the resources produced in the Kivoy-Tabriz region covered by the default provinces?

**Comment by settintotrieste** [comment]
Thanks. You can refer to this 1993 industry and mineral map for Iran. 

![](https://en.wikipedia.org/wiki/Mining_in_Iran#/media/File:Iran_econ.jpg)

**Comment by Outta-my-way-burrocrat** [comment]
@settintotrieste Sorry, problems with my internet connection are blocking map file uploads. I've loosely modeled the Khvoy/Khoy and Mahabad provinces after the modern borders of West Azerbaijan province. Would you mind if I split Tabriz into copper coal and cotton provinces?

**Comment by settintotrieste** [comment]
Thanks, I like your work! 

Sure, you can do the split. 

There’s a 25MB cap for pull request commits so you might need to upload the state map .bmp file here instead like what a previous contributor did.

https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/issues/484

**Comment by Mouseasel** [comment]
I'm glad you both brought up resources, because that brings up another issue: the resources of that whole region. East Azerbaijan and Mahabad seem to be covered with wool (aka goats). But the Soviet's weren't interested in wool, they were interested in the mineral resources of the region. They pulled out hoping to make an agreement with Iran for access to said mineral resources, mainly the oil if I am not mistaken, as gaining access to these was seen as the primary objective.

With that being said, petroleum should probably be added as a resource in the region.

Here is a natural resource map showing the general placement of things. Would be really nice to diversify Mahabad & East Azerbaijan's small economy and resources beyond goats. I high lighted the legend to show the relevant symbols. Note I added a question mark next to "copper" because I am not sure if that is the right symbol as per the map, given it's different color on the legend, but it could be a simple mistake on the creators part where they intended it to be purple.

![map 1](https://user-images.githubusercontent.com/68358654/89606808-f8aed200-d83e-11ea-83e6-076a1db679f8.PNG)
![map 2](https://user-images.githubusercontent.com/68358654/89606803-f77da500-d83e-11ea-89a6-548a2426677b.PNG)

**Comment by Outta-my-way-burrocrat** [comment]
Here's the provinces.bmp file for the West Azerbaijan province changes: [map.zip](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/5046614/map.zip) I need to edit the positions file for Mahabad and Khvoy next.

Mouseasel Thank you for that. I'll be adding petroleum with the East Azerbaijan province changes. There is a notable copper mine in Varzaqan county, East Azerbaijan.

settintotrieste labourers won't work event-created iron RGOs in this mod. I can't add an event for the Sungun copper mine.

**Comment by settintotrieste** [comment]
If the province RGO was originally for farmers, you need to script the event to convert Farmers to labourers. 

any_pop = { limit = { type = farmers} pop_type = labourers }

**Comment by settintotrieste** [comment]
I think this issue has gone stale
