### ISSUE TITLE
cwe crash when choosing country

### ISSUE THREAD

**Issue by cudeburr** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#633]
hi, i have a problem, the mod crash when I choose a country to play, for example Brazil, why does this happen?
crash when carrying "history"

**Comment by settintotrieste** [comment]
You’re probably missing some files in your mod

**Comment by cudeburr** [comment]
but I download both in the "github" version and I also downloaded in the "Modd" version, several times, is there any other alternative?

**Comment by settintotrieste** [comment]
Are you trying to load an old save game?

**Comment by cudeburr** [comment]
no, i just try to start a new game for the first time
I saw old tips that tell you to delete the cache from the map and I've done it several times, not every time I tried

**Comment by settintotrieste** [comment]
Have you tried deleting the CWE folder in documents? It does help some people who experience this problem. Another is to lower the graphics setting to the lowest.
