### ISSUE TITLE
"Soviet Thaw", working as intended?

### ISSUE THREAD

**Issue by mpristave** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#635]
The way Socialist Democracy seems to be presented is that it shouldn't turn into a republic if you have reforms, shouldn't decisions cause you to go to a republic instead as this form of government? Or a non-socialist party being elected? 

The event that fired is 60050.

NOT = { OR = { ruling_party_ideology = communist 
ruling_party_ideology = communist_social } }

Seems like this is intended to prevent this but it doesn't seem to be working.

**Comment by mpristave** [comment]
I rewrote the "not" with more normal formating and this seemed to fix it

		NOT = { 
			OR = { 
					ruling_party_ideology = communist 
					ruling_party_ideology = communist_social 
					} 
				}

**Comment by mpristave** [comment]
Looks like socialist_democracy isn't part of that trigger anyways, weird

**Comment by settintotrieste** [comment]
The event is 60051 which shares the same localisation. Socialist democracies should become a proper republic if all democratic reforms are taken as it would mean that there are no longer any socialist bias in the selection of members of parliament.
