### ISSUE TITLE
RGO issue

### ISSUE THREAD

**Issue by Turkbud** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#648]
When i change the RGO of provinces through decisions (like gaining credit money in capital) the province stops producing anything. 
![42960_screenshots_20200917022456_1](https://user-images.githubusercontent.com/33606441/93402314-15eaad80-f88d-11ea-8076-c7ebaf30bd8f.jpg)

I got natural gas in limassol and dodecanese through a decision and both provinces have 0 employment even though there are labourers there, similar thing happens with credit money.

**Comment by settintotrieste** [comment]
This is probably because of over supply of particular RGOs such that they are not being hired
