### ISSUE TITLE
Militant Trade Union Event Problem

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#66]
TakeThatVonHabsburgs said:

The militant trade unions event is terrible. It adds the modifier to each province in my state, which then applies to every pop in my country, meaning my militancy rises to 10 every few months for a period of 10 years.

**Comment by ARR8** [comment]
Off the top of my head, I think that's similar to how it works in vanilla or HPM. Not that it shouldn't be changed, but it's definitely not an original problem.

**Comment by settintotrieste** [comment]
If it's similar to the base game function then I think there's not much need to change it so I will close this issue.
