### ISSUE TITLE
Suggestion: Bio weapons, give vaccine to allies when completed

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#68]
When the vaccine development chain is completed, I think it makes sense for an option to give the vaccine to war allies. Possibly also an option to publicize the vaccine to the whole world or GPs. This could boost relations with the opposite bloc, if it exists, possibly tying in to #19.

**Comment by settintotrieste** [comment]
That is an interesting suggestion but I think for gameplay reasons I will have to stick to the current layout as I want to make it difficult for biological weapons effects to be removed from a nation as a cost of using it. So being able to give the vaccine to others allows the other nations to get off the hook too easily and too fast. At the moment creation of the vaccine stops the spread of biological weapons so in a way it helps allies as well.
