### ISSUE TITLE
crash on aug 5 1966 as soviet union

### ISSUE THREAD

**Issue by hihiiiiii** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#694]
It happens no matter how often I reload including from the previous autosaves. Everything was fine before this besides the occasional crash upon clicking a province. The Apollo 11 and Soviet (fake) equivalent fired a few months before the crash happened, but besides that idk what could be causing this

**Comment by settintotrieste** [comment]
Are you using an old save game on an updated version of the mod?

**Comment by hihiiiiii** [comment]
Was a game started from the version downloaded on github yesterday

**Comment by settintotrieste** [comment]
I’ve no idea what is causing the crash unfortunately
