### ISSUE TITLE
Extreme Islamic regimes sponsor terrorism

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#70]
Islamic nations with populist, traditionalist or nationalist ruling parties start choosing whether to sponsor terror when ISIS or 9/11 or afghan war occurs with the trade offs and benefits along the lines of militancy reduction, ruling party support, prestige, etc. with the enforcement of liberal democracy or communism needing to stop the promotion. The superpowers will then have the option to force the cessation of such activity via sphering or puppeting the sponsors. This would simulate the role of bipolarity in keeping a lid over local problems.

**Comment by ARR8** [comment]
Small update from #160, Algerian Civil War - Islamist revolutions trigger terrorism events in the republic they're rebelling against and Western powers

**Comment by settintotrieste** [comment]
Great
