### ISSUE TITLE
AI infamy issue?

### ISSUE THREAD

**Issue by TK3600** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#731]
AI seem to break infamy limit frequently despite not fighting much war. I suspect it has to do with certain decision. 

Countries that seem to break it frequently: PRC, north korea, south korea

**Comment by settintotrieste** [comment]
For the PRC, it was caused by them clicking on the claim greater China decision. I made it such that the AI won’t click it unless they have very low infamy. For Korea, it could be to do with the UN armistice event firing.

**Comment by settintotrieste** [comment]
It looks like the infamy issue came from the diplomatic mission under siege event which fires quite often. The current version should more or less fix this.

**Comment by settintotrieste** [comment]
Fixed the North Korean infamy issue in the current github version. Also tweaked the Hungarian and Czechoslovakian revolutions to avoid massive infamy gain for Russia.
