### ISSUE TITLE
Japan Monarchy Suggestion

### ISSUE THREAD

**Issue by yuridreis** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#742]
- As a democracy, Japan can't fire the decision to give the emperor more power or even bring the empire back. My suggestion is if Japan has a major pop nationalist or tradicionalist and the goverment is nationalist or tradicionalist to be able to create a constitucional monarchy. Maybe could give some debuffs and high militancy to most non accepting pops.

It's an interesting idea because if you somehow became a democracy you basically can't follow this route anymore.

**Comment by settintotrieste** [comment]
There shouldn’t be an easy way to return the king once his gone. Anyway, there’s a generic system in place to return the king via letting royalist rebels rise up and seize control.
