### ISSUE TITLE
List of TK3600's easily solvable minor nitpick

### ISSUE THREAD

**Issue by TK3600** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#749]
This is a list of small things to work on if anyone got time.

1. image for main battle tank tech is a Leo 2A6. We should replace it with a T-54 (most iconic) or a Centurion (first MBT). 

2. Naval tech have "artificial island" as one of the early tech for naval construction, I thought it was a modern thing. Best to swap its position with another tech, I am thinking marine radar.

3. The late game tech related to green agriculture give you boost in coal production??? It should reduce coal output and its related factory, while boost certain green industry. 

4. The naval ship tech invention is always 1 tier behind. research frigate gives corvette tech and etc.

5. Some of the naval tech dont seem to relate the invention it gives altogether.

**Comment by Outta-my-way-burrocrat** [comment]
None of the California Republic parties are localized.

**Comment by settintotrieste** [comment]
Techs have been reviewed so the problems here have been addressed. Point 4 is intentional. The techs only immediately increase the stats of ships that are available prior to the tech or else there would never be a ‘base’ version of the ship.
