### ISSUE TITLE
Something wrong with the fertility events?

### ISSUE THREAD

**Issue by Sillken** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#763]
From the few games I've played to the 2000s in the past few months I've noticed that the population number gets really sketchy for the majority of tags, which isn't really a problem in itself but a lot of said numbers seem to be somewhat consistent. For example: India, Ethiopia, Brazil, Argentina, Iran, Australia, New Zealand, the Philippines, Thailand and Vietnam seem to consistently have half (or even less) the pops they should have, meanwhile China, Japan and the major powers in Western Europe seem to greatly exceed their expected numbers without receiving any relevant immigration.
I recall CWE following population trends more realistically in the past and something seems broken now to say the least.

**Comment by settintotrieste** [comment]
It is really difficult to ensure that the population numbers match RL. A lot of this is due to the AI's excessive willingness to take child care reforms that give a big boost to population growth.

**Comment by Sillken** [comment]
Thank you for the fast response, I'm looking foward to testing these new changes soon

**Comment by Sillken** [comment]
So I started up a test game today and for the first 12 years population growth has been virtually nonexistent.
![v2_10](https://user-images.githubusercontent.com/76022889/102568804-057fe400-40c3-11eb-94ee-4b3f2f255009.png)
Also while looking up Cold War era populations I've noticed Vietnam start off with roughly half the population they had historically, in-game North Vietnam + French Vietnam have around 3.1m pops (12.5m people) while their real life 1950 population was around 25m people (6.25m pops).

**Comment by settintotrieste** [comment]
I’ve done slightly more tweaks, hopefully that would make the poorer nations’ population more historical
