### ISSUE TITLE
World economies completely collapse by the 1950s

### ISSUE THREAD

**Issue by mpristave** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#766]
Seems like I cannot get any machine tools to build any factories at all. Occasionally there will be a burst where stuff will build but rarely.

Everyones economy collapsed. World War 3 started as well after this happened. 

Save file if needed http://ftp.pvpchamps.com/The_United Kingdom1959_08_10.v2

**Comment by settintotrieste** [comment]
This has been fixed as of the recent github update
