### ISSUE TITLE
Translation of events into Spanish - Traduccion de eventos al español

### ISSUE THREAD

**Issue by crlso** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#769]
I did the translation into Spanish of all the CWE events, although unfortunately it doesn't work for me and I don't know how to solve this problem, I started doing 600 lines of translation of the document and the game worked perfectly, however now that I did all the translation of the document simply does not open the game I leave the download link with the faith that maybe someone will work or fix this problem. Victoria\mod\CWE\localization file location.
Hice la traduccion al español de todo los eventos de CWE, aunque por mala suerte no me funciona y no se como solucionar este problema, empece haciendo 600 lineas de traduccion del documento y el juego funciono perfectamente, sin embargo ahora que hice toda la traduccion del documento simplemente no abre el juego dejo el link de descarga con la fe de que a lo mejor alguien le funcione o pueda arreglar este problema. Ubicacion del archivo victoria\mod\CWE\localisation

https://drive.google.com/file/d/1kwCIN54HktPiLyDD30R27ZLJi8EKLDtB/view?usp=sharing

**Comment by robofiz** [comment]
podrias hacer una vercion mas reciente y completa por fa

**Comment by crlso** [comment]
> podrias hacer una vercion mas reciente y completa por fa

No creo ya hacerlo, trabaje solo para esto y consume mucho tiempo traducir y que compacte ademas que con las nuevas actulizaciones seguro seran mas cosas, a lo mejor si un dia consigo a alguien lo haga de nuevo y completo, y si te funciono me re alegro
