### ISSUE TITLE
Yom Kippur & Six day wars do not function correctly - Assigned to ARR8

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#77]
From feedback:

The wars almost never breakout and Israel ends up stuck with 1948 territories.

**Comment by ARR8** [comment]
I'll leave my other bugs with Israel here, too:

By the definition of the territorial dispute CB, Arab states can declare war on Israel. When Egypt declares a war, though, it messes with a lot of events that search for a war between EGY and ISR to do with the Suez crisis, triggering most of them early, and preventing the European powers from being involved.
  For example, the UN votes whether to intervene against Israel, even though they are the defender. Several European events fire, such as the FBU, referencing the Suez crisis which never happened. The result is that America intervenes to save a sphereling, but not an ally yet, and does nothing, leaving Israel fully occupied by Egypt for years.

Minor bugs:
Releasing Gaza before the partition can break future events such as the 1948 war and possibly others. Releasing Jerusalem, also before the partition, makes it quickly turn into an independent Palestine, which is realistic considering its demography, but it never gets the West Bank and then gets annexed to Jordan.

**Comment by settintotrieste** [comment]
Thanks for the further feedback. This is more complicated a problem than I thought, I don't know how to approach this.

**Comment by ARR8** [comment]
I should say; I'm working on rewriting all of the Israel events and adding more, but it will take a couple of days. If you want, you can assign the issue to me so it looks official :). But I won't be submitting any PRs until it's done. I'll be putting the changes as they come into a branch in my fork.

**Comment by settintotrieste** [comment]
Sure and thank you very much for your help!

**Comment by ARR8** [comment]
Ha, that's great but FYI there is a Github system for assignees, tags, and version milestones in the sidebar. That last one would probably be good to use to plan the main features of the next release and future ones.

**Comment by settintotrieste** [comment]
Thanks for the heads up! Those will be very useful!
