### ISSUE TITLE
Pop promotions (craftsmen and stuff)

### ISSUE THREAD

**Issue by Mitusonator** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#774]
Are there any plans to alter pop promotions to be more engaing for the player? rn it feels like it is either 0 or 100 when it comes to craftsmen promotions, and I feel like more gradual change would be beneficial for the mod's fun factor, and if we would like to be ultra accurate majority of population should be employed in industry(+ services) in developed countries, I know the game is abstract but it always felt weird that majority of population produces raw resources.

I know that it would be quite a bit of work but it seems like the last field of vanilla mechanics that could be altered to make the mod perfect!

**Comment by settintotrieste** [comment]
I’m afraid I’ve no plans. Craftsmen promotion is the way it is now to avoid messing with the GP list and causing problems elsewhere in the economy.
