### ISSUE TITLE
Soviet Union or America falling event triggering too early

### ISSUE THREAD

**Issue by Tovarisch-the-Alive-Snake** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#776]
Multiple times, I have had the event for the fall of the US or the USSR, without them having been dismantled or even lost a war. In one, I, Yugoslavia, the Soviet Union, and all of the Soviet Allies were up against the US (who, for some reason, did not call in a single ally). Cuba had occupied most of Florida, and there had been a few battles (the Soviets were winning), but the war had not yet ended, For some reason, I then got the Fall of the United States event, giving me a bit over 1000 prestige and -20 infamy. I assume other countries got it too, as their prestiges increased by roughly the same amount. Then, I had a different game. I was playing as the Republic of China, in the 1946 start date. The USSR fell before the year 1947. The same event triggered, and kicked them out of great power status. They weren't even in a war, so I don't know why. As a result, Eastern Europe stayed free, with the exceptions of Bulgaria and Albania, who had already been puppeted, Please fix it.

**Comment by settintotrieste** [comment]
Are you using the current version on github?

**Comment by Tovarisch-the-Alive-Snake** [comment]
I am using what was the current version on github a few days ago.

**Comment by settintotrieste** [comment]
This has been fixed as of the current github version
