### ISSUE TITLE
Three different systems for independence

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#78]
I really like the new independence system in 0573bd1, especially as it gives Nationalist parties a purpose now, but there are now three different interfering systems for independence:
1. The new system based on referenda, occurring after decolonization
2. The system that releases colonies as realms and has them declare full independence after a time, mostly during decolonization.
3. The system by which cultures in provinces petition for autonomy, then independence.

The third one, now with the other two in place, seems a little redundant. I think it came from NWO, and it doesn't really work very well. Most of the strings are unlocalized, and the modifiers are confusing, and even saying no to all of the province events will, confusingly to the player, not disable the other systems and still cause independence, nor does it tie in to any of the new systems, such as realm governments or nationalism.
  The second system has a couple of bugs, but I think 1 and 2 are still much better implemented such that the third one could probably be safely removed, unless it works for some situation I didn't account for.

**Comment by settintotrieste** [comment]
2 and 3 tied heavily with each other as 3 creates the puppet from the colonial provinces and 2 allows the puppet to be released. As 2 and 3 deal only with colonial puppets, the must be one chain for non colonial puppets and that is the role 1 plays. No.3 does take into account nationalist support, militancy and colonial power minorities policy to determine frequency of of the events and is very important for the decolonisation system to work.

Please don't remove any features unless the feature is game breaking as removing features can introduce a lot of bugs and remove flavour.

**Comment by ARR8** [comment]
In that case I think there is a bug: accepting the calls to autonomy in chain 3 causes the colonial nation to get released completely independently, without going through the process of becoming a realm first. The only way to activate the realms is to completely deny any option from chain 3, which seems counter-intuitive, as there is no way to actually grant "autonomy" with those province options, only full independence, which only gets called for if you promise autonomy and then do nothing.

If the current way it works is as intended, then the localization definitely needs more changes to make sense for the player.

**Comment by settintotrieste** [comment]
I know it's kind of weird but it was how NWO did it so I didn't want to touch it too much in case of bugs. Ideally I would like to have it such that when autonomy is chosen, the colony will be released as a colonial government which will then have a referendum on whether to seek independence but this is difficult to have balance in as most of the time the country will be swamped by nationalist support which will mean independence. I think the best fix is to correct the localisation to tell the player instead of giving autonomy it is giving self-determination. This I think will make it more to the player.

**Comment by ARR8** [comment]
Currently decolonization is a mess with the ability to select whether you want to keep the empire, the swarm of province events, two different calls for independence which give you two different types of wars if you refuse and two different types of nations that you release, migration of random minorities throughout your low-pop states and German lands, and no interaction between any of these.

Eventually I think it would be good to rewrite completely, probably using the new system which works very elegantly, and the realms which are amazing flavor-wise and very fun. This probably won't be for a while, and fixing the localization is a step in the right direction, but currently the system is buggy enough that I would keep this issue alive for the future.

**Comment by settintotrieste** [comment]
I agree, it definitely can be improved and a rewrite in the decolonisation chain can be really beneficial. Perhaps as a rough idea, I will keep the province events as it seems to be the only way to identify the area to be decolonised but then apply the independence referendums to decide if the realm should leave the empire. I will see what I can do with this after 1.06.

**Comment by settintotrieste** [comment]
A hybrid system has been created, using the generic independence mechanic for dealing with full independence and the older system for dominionship.
