### ISSUE TITLE
Migrations within continents barely exist.

### ISSUE THREAD

**Issue by Sillken** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#782]
Even though in the pop files there's modifiers that encourage migrants to choose countries they share a continent with, migration within continents only seem to happen if countries share a border with each other. The only migration I've seen so far within Europe was from German and Spanish pops to France and they were in smaller numbers than those leaving for Australia, NZ, Canada and Japan (?).

**Comment by settintotrieste** [comment]
This is likely a hardcoded issue that can't be solved because nothing seems to be able to affect it, either that or the capital_scope check doesn't work in the emigration section.

**Comment by settintotrieste** [comment]
This has been fixed in a recent update
