### ISSUE TITLE
Suggestion on liferating and international metropolitan areas

### ISSUE THREAD

**Issue by domenico267** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#795]
Good Evening,

I love your game and would like to give some tips to improve the gaming experience:

- It would be nice if the liferating of the provinces were based on real life standards of livings (mercerer etc...), or influenced by overpopulation phenomena, in order to make the parameter more useful

- It would be nice to introduce the concept of an international metropolitan area, which is increasingly observed in large European metropolises. For example, once the Oresund Bridge has been created, the opportunity could be given, through events, to guarantee bonuses to both provinces of the area involved (increased immigration, greater industrial score, etc.), and perhaps with prolonged events, to make it possible to acquire the entire region, when the presence of one country in the region becomes much greater than the other, and the other province becomes a suburb of the bigger one.
This mechanic would make it much more fun to play European nations, as this phenomenon is constantly growing, and international metropolitan areas are constantly growing.

Other examples of shared metropolitan regions:
- upper Silesian metropolitan area
- Vienna Bratislava metropolitan region
- Meuse – Rhine Euroregion

There truly is a lot of them, you can find it yourself

Hi!

**Comment by settintotrieste** [comment]
Hi,

1. Life rating does nothing in the mod and I'm afraid it will remain this way. There are hardcoded limitations as to what life rating can be used for. One of them is that life rating values changed mid game cannot be checked for by scope codes. This prevents it from being used for modelling dynamic population growth, development etc. 

2.  The international metropolitan area ideas is also not feasible. Province modifiers are quite limited as to what they can do. It can't increase industrial score as that depends on the number of employed craftsmen (the scriptable aspect of this is limited to only the pop and country scope), it also cannot increase international immigration as province migration boosts for province modifiers only increase domestic migration. The scopes for provinces are also very limited as they cannot check for influence in any state.
