### ISSUE TITLE
Strange migration patterns & misc.

### ISSUE THREAD

**Issue by cecillia-liebkne** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#799]
1.) Capitalists/investors and clergymen/intellectuals have migration_target checks that check for aristocrats/executives unemployment for some reason. Is this intended behaviour? I don't see much of a reason why they would be related.

2.) Also for migration_target checks, immigration policy affecting whether pops move to overseas provinces doesn't seem to make too much sense. is_overseas checks for a land connection and whether it is the same continent as the capital, and doesn't really have much to do with immigration. I don't think closed borders should affect British pops internally migrating to the Falklands, for example.

3.) There are a few naval techs/inventions that increase carrier/modern_destroyer range, but according to [this](https://forum.paradoxplaza.com/forum/threads/1123034/) forum thread, naval combat begins at a fixed distance of 2, which is what the units initially start off with, so the range increases wouldn't actually do anything.

4.) As a suggestion, I think event 669966, the performance mode event, would work better if it also reduced global prestige along with pop size, as the rankings can get overly skewed towards starting prestige when using one of the pop reducing options. I've personally been using it by reducing prestige by 60% of the pop reduction, like below:
```
option = {
name = "No changes to the pop ratio"
set_global_flag = performance_mode_set
}

option = {
name = "Scale global population to 3/16"
set_global_flag = performance_mode_set
any_pop = { reduce_pop = 0.75 prestige_factor = -0.15 }
any_country = { limit = { exists = yes } any_pop = { reduce_pop = 0.75 } prestige_factor = -0.15 }
}

option = {
name = "Scale global population to 1/8"
set_global_flag = performance_mode_set
any_pop = { reduce_pop = 0.5 prestige_factor = -0.3 }
any_country = { limit = { exists = yes } any_pop = { reduce_pop = 0.5 } prestige_factor = -0.3 }
}

option = {
name = "Scale global population to 1/16"
set_global_flag = performance_mode_set
any_pop = { reduce_pop = 0.25 prestige_factor = -0.45 }
any_country = { limit = { exists = yes } any_pop = { reduce_pop = 0.25 } prestige_factor = -0.45 }
}
```

**Comment by settintotrieste** [comment]
1. This was done to simulate how highly skilled workers and rich bums want to go to a country with a strong economy which is measured in game by high employment.
2. The overseas was done by HPM which I just imported over. I think the reason behind the check is to help to stop random islands getting massive migration which is good to keep. Closed borders could be related to internal borders, something like the USSR and North Korea which heavily limited internal migration.
3. Fixed by halving all naval range
4. Added
