### ISSUE TITLE
Nationalist flags don't seem to be working

### ISSUE THREAD

**Issue by MarshawnBM** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#801]
They just use the realm ones I think

**Comment by settintotrieste** [comment]
What government type are you?

**Comment by settintotrieste** [comment]
Have you tried clearing your flag cache?

**Comment by MarshawnBM** [comment]
I am a nationalist dictatorship, I tested it and the problem seemed to be happening with both Spain and Germany. I deleted the flag cache and it still seems to be only realm flags for nationalist dictatorships

**Comment by MarshawnBM** [comment]
Ok I figured out what was going on, nationalist dictatorships seem to be using realm flags, while sectarian regimes use the proper nationalist flags. Not sure why though

**Comment by MarshawnBM** [comment]
ok so I've fixed it now in my game, what was happening was in common/governments the "populist_government" seems to actually be the nationalist dictatorship ingame, and the "Nationalist dictatorship" in the government file is the sectarian regime ingame, so I changed the line 	flagType = populist        into        	flagType = nationalist        for the populist_dictatorship, and it all works perfectly now 
[governments.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/6254787/governments.txt)

**Comment by settintotrieste** [comment]
It’s actually intended that Nationalist Dictatorship is populist_dictatorship and Sectarian Regime is nationalist_dictatorship. NWO originally used populist dictatorships and sectarian regime but it populist dictatorship didn’t make sense so I changed it to nationalist while keeping sectarian as a lot of code already used the terminology.

**Comment by MarshawnBM** [comment]
Ok, just seemed strange to me a nationalist Germany would not use the swastica flag, but a populist one would. I’m not sure exactly about Spanish flags so maybe that system works fine for them.
