### ISSUE TITLE
Unable to pass reforms at all

### ISSUE THREAD

**Issue by torn1147** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#804]
I downloaded the version from here 2 days ago and at some point in the game, the option to pass reforms just abruptly disappeared for me and never appeared again. I've played this mod a lot in past versions and I've never had this happen before where most of the house is willing to vote yes, and I haven't passed any reforms in years, but I'm still unable to.

I've seen this in both games I've played on this version now, playing as Iran and Turkey, the saves I've attached below. My militancy is near 10 in both, as I'm unable to pass any reforms.

https://ufile.io/f/5pxw2

**Comment by settintotrieste** [comment]
It is likely that your country had a gridlocked legislature when you are a presidential or semi-presidential republic and when your pop majority ideology does not match your ruling party ideology. What you need to do is to either change to a parliamentary republic, become a constitutional monarchy or become a dictatorship.

**Comment by torn1147** [comment]
Hmmn, seems like you're right. I was able to pass a reform by clicking the executive action decision in the turkish save, although changing to a parliamentary system didn't change the gridlocked legislature in the iranian one - not sure if that's intended.

**Comment by settintotrieste** [comment]
The event to remove gridlocked legislature fires every 12 months so it takes a while, I’ve done a tweak so the become parliamentary republic decision immediately clears the flag
