### ISSUE TITLE
CTD at Loading Database

### ISSUE THREAD

**Issue by fcwe1113** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#815]
The game keeps crashing at Loading Database, I am running on windows 10 version 21H1, vanilla and the other mods all work fine, and the logs dont have anything useful

both version 1.13 and the github zip version have this problem

**Comment by settintotrieste** [comment]
It could be due to a corrupted install folder or you put in the CWE-master file instead of the contents

**Comment by fcwe1113** [comment]
I think the version I downloaded is corrupted for some reason, when I tried to extract it with 7zip, it told me "unexpected end of data", and inside the CWE folder the folders below gfx are all missing, and i cant even open the zip with the windows file manager.

**Comment by settintotrieste** [comment]
It could be an issue on your side. I'm able to download the zip file with no errors from github
