### ISSUE TITLE
Party issues

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#837]
The pre-1982 Swedish progressive parties have bad start and end dates
Argentina has no progressive party before 2007
Canada has no progressive party before 1983
Syria and Syrian Interim Government don't have progressive parties
The Syrian Communist Party has citizenship_policy = planned_economy1

**Comment by settintotrieste** [comment]
Would it be possible if you could help me create a stop gap fix for these issues until I can get around to adding to adding the historical parties?

**Comment by Outta-my-way-burrocrat** [comment]
@settintotrieste have you had any issues since the GitHub outage?

**Comment by settintotrieste** [comment]
Thankfully no. Everything looks fine now.
