### ISSUE TITLE
Possibility of stop ai to form superstate?

### ISSUE THREAD

**Issue by Leo1836** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#840]
Is it possible to disable all ai countries to form superstate? I think the game will be more intriguing with the absence of superstates. Besides, thank you for the mod.

**Comment by settintotrieste** [comment]
It is not possible to disable superstates right now. I’ll consider adding a toggle for the player in the future.

**Comment by DoktorKure** [comment]
this can be done by going into the starting events and having an event that allows the player to choose whether or not to disable superstates via a global flag that says "superstates_disabled" and then having every starting decision chain in each superstate do a check for `NOT = { has_global_flag = superstates_disabled }`

**Comment by DoktorKure** [comment]
Actually... it's even simpler. Just have the option to disable the superstate formation set the country flag for all countries to `hide_superstate` and the option to enable superstates to clear the `hide_superstate` flag. Since AI never touches the decision to hide or unhide superstate decisions.

**Comment by DoktorKure** [comment]
[Toggle Superstates.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/8580542/Toggle.Superstates.txt)
Done, and tested to make sure it does the intended purpose. I haven't done a full playthrough but it should keep superstates disabled without affecting historical superstates like UAR, Balkan Federation, the historical EU events, etc.
