### ISSUE TITLE
Services industries leave out factory workers

### ISSUE THREAD

**Issue by olohal** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#842]
There's an issue where if the AI is left alone building factories, it tends to expand services based factories instead of the rest. Because these factories only employ clerks, workers are excluded and remain unemployed. On top of this, because the AI realises there's unemployment, it keeps expanding these factories ad infinitum. In the end, instead of building or expanding factories that employ workers in order to solve the increasing unemployment, they keep expanding on services factories to the hundreds, which begets human intervention in the economy to fix unemployment.

Am I the only one facing this issue? I haven't been able to find someone addressing this. It may have something to do with the fact that I like laissez faire policies and that's not very common among players.

**Comment by settintotrieste** [comment]
I'm afraid this is a problem that cannot be fixed without removing service factories altogether. The moddable code does not allow me to specify which types of factories the AI should expand when there is unemployment.
