### ISSUE TITLE
East Germany KPD disappearing after reunification if main tag

### ISSUE THREAD

**Issue by Haruhi-is-Waifu** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#844]
Not sure if this is working as intended since I am aware that releasing East Germany manually as the Soviets isn't exactly going along with events, but for some reason, it seems after everyone releases their occupation zones to me/I take them back, within a couple of years, the KPD transforms into a Traditionalist/Nationalist party despite being a Communist Dictatorship. I'm pretty sure it has a generic name of German Party.

**Comment by Outta-my-way-burrocrat** [comment]
Try changing the KPD's end date to 1956.8.1.

**Comment by settintotrieste** [comment]
Does this fix help with the problem?
