### ISSUE TITLE
Some countries don't have any primary culture pops

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#849]
~~Louisiana has French primary culture and French-American pops~~. Other countries like Bangabhumi, Niger, Seleka and some Caribbean countries have similar issues.

**Comment by Outta-my-way-burrocrat** [comment]
1. Many commonwealth pops are switched from English to British and vice versa in 1992.
3. Balkars and Kabardians haven't been merged with kabarday_balkar and circassians yet.

**Comment by settintotrieste** [comment]
@Outta-my-way-burrocrat Barring any unforeseen circumstances, this mod is done. The new mod will take up a lot of time so I'm afraid it not possible for me to do both.

**Comment by settintotrieste** [comment]
Mod development has stopped and so all outstanding issues will be closed.
