### ISSUE TITLE
UGR tag does not gain cores on Greece after winning civil war

### ISSUE THREAD

**Issue by dissatisfieduser** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#855]
Currently, the event that ends the Greek Civil War inherits the GRE tag but does not give UGR tag GRE's cores. UGR also stays [North Greece] for the rest of the game, the name feels non-immersive after winning the GCW.

**Comment by settintotrieste** [comment]
Fixed by tag switching UGR to GRE upon annexation of GRE by UGR
