### ISSUE TITLE
Satellite launch never succeed

### ISSUE THREAD

**Issue by caffeinian** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#858]
Played with India and satellite keeps failed even in 21st century. I entered into USA and they've also failed to launch satellite.
 When I flipped Random_list value of Space Attempts.txt then it never fail within 10 attempts. Therefore Random_list seems to be broken and I assume that function just choosing higher value instead of Random outcome.

**Comment by settintotrieste** [comment]
Okay revised space attempt system so that there is now a long stop if the player cannot get success through the space attempt decisions. A space program will now get success no matter what within 10-15 years
