### ISSUE TITLE
Provinces in Vardaria/North Macedonia is missing

### ISSUE THREAD

**Issue by AstroRangerBeans** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#859]
Hello, there!

When I'm using this mod, I have encountered one such issue that isn't resolved: Missing two North Macedonian provinces while I'm loading the 1946 bookmark that I'm encountering with one such problem that these two provinces not only went missing but blank. Would this issue can be resolved by adding or coloring two provinces?

**Comment by AstroRangerBeans** [comment]
@settintotrieste? 

Please, don't forget about the issue where NATO is activated but NATO member states isn't allied with each other.

**Comment by settintotrieste** [comment]
I have the provinces on my end, you might have done a copy and replace instead of a delete and paste

NATO nations breaking their alliances is because of the AI which I can't stop them from doing unfortunately.
