### ISSUE TITLE
1946 Republic of China Armies Empty

### ISSUE THREAD

**Issue by TomBradyLover** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#860]
I updated from 1.12 and went to play the ROC and noticed the Republic of China Army Chongqing starts with every regiment at 0/3000 strength and the Republic of China Army Fuzhou starts with 38/44 regiments at 0 strength. Is this on purpose? I don't remember it like that in the earlier versions.  It seems to be because they have no pop.

**Comment by settintotrieste** [comment]
It is not on purpose. It was probably caused by an edit to the soldier to pop ratio in 1.14. Fixing this will be quite labour intensive so I'm afraid I can't fix this until I get a pop generator.
