### ISSUE TITLE
"The Gulf of Tonkin Incident" event: not bugs, but maybe there's something weird in vietnam_war.txt code.

### ISSUE THREAD

**Issue by aurreko** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#862]
In Events/vietnam_war.txt, "The Gulf of Tonkin Incident" event(id = 12280031) there are two options both with "ai_chance = { factor = 0.9 }". I tested the event via console playing both as the USA and as another nation; the event starts but I don't know if it works with the AI because of these two options with a total likelihood greater than one. I attach two screenshots about event fired via console and the vietnam_war.txt file with the first line put in by me that explains better my concern. I'm running your 1.14 master.zip version downloaded three days ago by this site.

![The Gulf of Tonkin Incident USA Event playing as USA](https://user-images.githubusercontent.com/80220181/162417313-9e3dcaad-aeae-4d40-afc5-5dc65261c261.JPG)

![The Gulf of Tonkin Incident USA Event playing as Italy](https://user-images.githubusercontent.com/80220181/162417363-8b1c21d7-f8e7-46c0-ab85-c658a8e90331.JPG)

[vietnam_war.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/8451011/vietnam_war.txt)

**Comment by settintotrieste** [comment]
Thanks for letting me know of the bug. The second option should have an ai chance of 0.1. Having the same AI chance for an event does not break the event, it would only mean that each option has a 50-50 chance of being picked.
