### ISSUE TITLE
Not an issue but a very few UI changes to not force your eyes. Sorry but i don't know where to post these files.

### ISSUE THREAD

**Issue by aurreko** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#863]
I did for myself some little UI tweaks to not force eyes. I attach some comparison screenshots, if you are interested i upload them. Sorry to post here but i don't understand how to use the "pull request" thread.

![CWE Vanilla Example1](https://user-images.githubusercontent.com/80220181/162421191-25d7c10b-ab40-44b1-a7b0-0fd6049673f0.JPG)

![CWE Modded Example1](https://user-images.githubusercontent.com/80220181/162421265-ebb7715f-bfa9-4f84-98a8-51d61a623d42.JPG)

![CWE Vanilla Example2](https://user-images.githubusercontent.com/80220181/162421356-905d0ac8-b681-4bfa-80ba-fe8a88eb111c.JPG)

![CWE Modded Example2](https://user-images.githubusercontent.com/80220181/162421435-170af624-2022-45b2-b7df-bd9b7cb979b8.JPG)

![CWE Vanilla Example3](https://user-images.githubusercontent.com/80220181/162421487-c2c25bc8-65c1-4b02-b1bd-577d11265a7e.JPG)

![CWE Modded Example3](https://user-images.githubusercontent.com/80220181/162421526-6180c76b-e39a-4f5b-826f-796b80b964a4.JPG)

**Comment by settintotrieste** [comment]
They look good! Can you upload the files in this issue thread?

**Comment by aurreko** [comment]
Files:
[CWE-gfx-interface.zip](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/8520811/CWE-gfx-interface.zip)

These are other two little tweaks;
Screenshots:
![CWE Vanilla1](https://user-images.githubusercontent.com/80220181/164215118-a8aba563-e7c7-42c2-ba86-6f665c82bad9.JPG)

![CWE Modded1](https://user-images.githubusercontent.com/80220181/164215171-98805a7f-e1a3-4d1d-9594-4f6d6ae77e0b.JPG)


![CWE Vanilla2](https://user-images.githubusercontent.com/80220181/164215232-da2ae440-4ab1-4c17-b119-fa78ffb8ab59.JPG)

![CWE Modded2](https://user-images.githubusercontent.com/80220181/164215253-2e430323-62b8-44df-b075-f4df96396710.JPG)


Related files:
[CWE-gfx-interface(others).zip](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/8520848/CWE-gfx-interface.others.zip)
