### ISSUE TITLE
Missing Ports

### ISSUE THREAD

**Issue by DoktorKure** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#887]
Qinzhou - 2682
Zhanjiang - 2646
Huaian - 1536
Port Lianyun - 2636
Binzhou - 1570
Dandong - 2613

For some reason there's a lack of port here which in turn means you can't build a naval base in any of these territories.

**Comment by Outta-my-way-burrocrat** [comment]
@settintotrieste what do you think?

**Comment by settintotrieste** [comment]
I would have liked to fix these bugs but unfortunately v3 arrived earlier than expected.
