### ISSUE TITLE
African Cultures Accepted/Primary Mechanics

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#9]
InquisiteurArax said:

Africa in the mod is a cultural mess, which is cool and historically accurate. However, the nations of Africa can't unlock new accepted cultures for most of them. As Ethiopia for instance, my populist party was the Oromo liberation front... but there was no way to have the Oromo becoming accepted. More problematic, for Nigeria their only accepted culture and primary is Black Anglo but after loading the game for them, they had less than 1% of their population of that culture. And they have no decision to accept the other cultures.
As a result, their population is massively (90%+) nationalist, they can't field a decent army and they face constant rebellions (which they can't face for they have no decent army). That also makes than though being among the most populous countries of my play-through they are of quite low ranking with no hope of going up.
There is the same issue with South Africa, Ghana, Rhodesia (but that is historically accurate) and possibly some others. That also makes that Northern Africa (benefiting from a dominant united arabic culture) tend to fare much better than the subsaharan one and though it historically makes sense for time up to now, it is not necessarily forced for the future.

I think having, under certain circonstances, a possibility to add cultures of the African subgroup as accepted if they account for a certain part of your population or having all African nations getting African Minor as accepted and getting a bonus to assimilation from the African group to African Minor could maybe help. 

Proposed Solution:

I would probably avoid the assimilation to African minor as it would reduce the cultural diversity in Africa which is not likely to happen in reality. So best solution I think would be to have decisions to add African cultures to accepted if:
1. The country has pop with the culture and
2. If the ruling party has full citizenship policy.

Then addition to primary culture depends on:
1. If the culture is a majority
2. Government is a democracy
3. Equal Rights policy is selected

The catch is that I have to make a decision for each African culture to add it to accepted and another for primary culture. And there are A LOT of African cultures. So it's going to take a while before I can complete it.

**Comment by settintotrieste** [comment]
Decision chain template for the addition of cultures:

However there are far too many cultures for me to manually create a decision for each culture. I will therefore have to keep this on hold indifinitely.

[Add Primary Cultures.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/843382/Add.Primary.Cultures.txt)
[List of african culture.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/843381/List.of.african.culture.txt)

[Remove Accepted Cultures.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/843380/Remove.Accepted.Cultures.txt)

[Add Accepted Cultures.txt](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/files/843379/Add.Accepted.Cultures.txt)

**Comment by ARR8** [comment]
Alternatively, there could be a single decision, like the [Native Protection Act Decision in HPM](https://gist.github.com/ARR8/5e21f00e5122107ddce6f8ea31e27533) to accept all present minority cultures, something like "Abandon tribalism."
  It could add militancy and support for nationalists among the dominant culture and uneducated pops, restricted use for South Africa, nationalists, etc. Could also require policies/techs.

-----------

Another idea could be to add a global modifier to assimilation in countries with a capital in Africa, like vanilla Vic2 has for the New World, and assimilate to union cultures or colonial languages. There could be militancy events added and assimilation reduced overall for nationalist regimes to prevent things like Hutus and Tutsis assimilating.

Both options need to be tested for balance, of course.

**Comment by settintotrieste** [comment]
Thanks, those are very good ideas! I like the HPM decision it is very simple and effective, so I will use as a template to create a "Nation of equals" decision to add the African cultures. What I will do is to incorporate both the adding of accepted cultures and assimilation. With adding of cultures only avaliable to democratic nations but increasing majority pop militancy and a "forced assimilation" decision giving the assimilation boost to dictatorships but at the expense of militancy gain.

**Comment by settintotrieste** [comment]
I am also thinking of expanding this to other continents. However I must make it such that it requires a or middle game tech to prevent colonial empires from accepted all cultures as accepted.
