### ISSUE TITLE
American separatist states

### ISSUE THREAD

**Issue by ARR8** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#90]
In the event of a new American Civil War, currently the CSA, Texas, greater California, Puerto Rico, and Hawaii get released. Arguably, the Californian separatist movement is not so strong, and it is doubtful that it should include all of the other states that it does. Some movements that may be stronger could include the Dakotas and Utah. Of course, including every possible movement would probably cripple America and make a civil war unwinnable.

So, there's a question of:
1. How difficult should the civil war be? Should the AI be able to win it easily, about what % of the time, etc.?
2. What nations should have cores in America? Should they all get released?
3. Who is likely to secede in the event of such a war? Did the original Manchurian Candidate book, which inspired the event chain leading to the CW, have any scenarios like this for a probable basis?

**Comment by settintotrieste** [comment]
Perhaps just Texas, CSA and the Californian republic, I have not heard much of the Dakotas and Utah one. I am not sure how large these states should be but it must be large enough such that they can still win. You can make the call for this.

The book had a good ending where the Manchurian candidate was stopped. But the general outline was that he would create an excuse to enact emergency dictatorial powers and then be the puppet dictator of the US which would in my mind certainly have been met with intense backlash and civil war to restore democracy. 

I think a dictatorial America should not have a high chance of winning the civil war as it would be unstable and do not have a committed army to defend it. So a chance similar to the CSA in the vanilla civil war would be appropriate.

I think the nations that should be released should be the ones with many freedom prioritising people. An approximate guage would be "liberal" support in various American states today or in game. I think the one which should have cores should be the CSA as in this case it will be offering an alternate America.

**Comment by ARR8** [comment]
1. In that case, probably more distant territories should be released. I'll add Alaska in the future. Nevermind Utah and the Dakotas - their movements come more from unique identities (Mormons and Natives) than from any real desire to secede.

2. I agree with your assessment.

3. Currently, the biggest challenge in the Civil War would likely be California, as it is the most populous state and secedes with nearly the entire West Coast. If they are out of the picture, though, Texas and the CSA would probably not be much of a challenge. If New England+New York were to secede, I doubt the USA would have an overwhelming chance. However, their suppport for secession is generally weak, being the first states.

4. Interestingly, Texas and the South are considered the most right-wing areas in America. They are the most [religious](https://en.wikipedia.org/wiki/Bible_Belt) and historically the longest to preserve the status quo of [segregation of African-Americans](https://en.wikiquote.org/wiki/Lyndon_B._Johnson#Civil_Rights_Bill_Signing_Speech_.281964.29).
  However, they are probably also the most individualistic and opposed to government overreach (e.g. gun control, national registries, federal regulations), and prone to unrest during military maneuvers in their area. Consequently, they have the most active separatist movements, so I would keep them.
  I'm not sure I agree with the CSA being the one to offer an alternate America. Despite its name, it nowadays generally represents the Southern nationalists and would be unlikely to want to restore federal rule. I'm not sure who that would, though.

**Comment by settintotrieste** [comment]
I agree with with all your points. So the CSA should not have cores over America.

**Comment by ARR8** [comment]
Right - the alternative I'm thinking is to split the remaining parts America up into a bunch of different nations, all of which are trying to unite back into the USA, and leave the previous states as new nations who opted not to participate in the CW and just secede. However, I'm not sure how the "unite the nation" CB would work in such a multi-faction war. The alternative of just having two factions in the war seems arbitrary. I'll do some more thinking about this.

**Comment by arandomperson5000** [comment]
For Dakota are talking about the Republic of Lakotah, if you are I wouldn't recommend adding it into CWE as none of the Lakotah tribal governments actually support the proposal and the area it claims has a ridiculously low number of Native Americans actually living in that area for example Native Americans only comprise 1% of the total population of Nebraska a state which has a very large area claimed by the Republic of Lakotah.

**Comment by arandomperson5000** [comment]
You could be quite interested into simulla's proposal for a fall of the United States if you're looking for ways how the downfall of the U.S could occur.
https://github.com/simsulla/nwomod/issues/1026

**Comment by ARR8** [comment]
I'm not too big a fan of that as it seems a little too "New World Order"-y and a bit outside the realm of plausibility. Plus, the logic for the downfall of America coming from internationalist progressives is a bit of a stretch for me.

In fact, I would even recommend making superstates more difficult to form, since they pretty much take all the challenge out of the game and are probably better suited for the late-game, if they are realistic at all.

What I'll probably do, instead, is take the "Free States of America" present in a lot of Vic2 mods, e.g. HPM, along with some of its events for a more traditional civil war, but with extra secessionist states vying for independence like Turkestan for the Chinese CW.

Thank you for the suggestion, though! I think where this mod and NWO most diverge is how the future is treated. In this one, it is mostly a continuation of the Cold War between superpowers, while NWO is all about the transition to the "New World Order." Obviously, both are valid predictions, though I do think exploring the Cold War in a more technologically advanced society is more interesting for a game, and a theme of much of the science fiction of the time.

**Comment by arandomperson5000** [comment]
While the populist part from that proposal vying for power is accurate, I completely agree with you that the proposal is a bit of a stretch, I do honestly prefer the Divided States of America idea you're talking about as the U.S is basically a mishmash of cultural regions for example the Texans and the Deep South. I could easily see in a scenario in which American national identity has been severely damaged, the U.S could break apart into smaller nations. Also as in interesting note in the months that preceded the American Civil War individual states in the Deep South such as Georgia and Alabama seceded from the United States of America as their own separate countries at first in January 1861. It was only until early February 1861 when the Confederate States of America was created as an actual country.

**Comment by ARR8** [comment]
That's exactly right, and partly why the current implementation works is that the nations with the strongest  identities already have cores present. Of course, the question remains of whether the rest of the states, who have a more American identity, will stick with the failing union or go to war to restore democracy.
  I'm not sure how to pick which should end up in the USA or FSA. A couple of options I'm considering weighting by liberal support or just a random chance for each state.

As for populism, I'm not sure I wholly agree with that, either. Certainly populism is on the rise, and so is polarization, but populism is rising also in less polarized democracies, such as European parliaments. In my opinion that proposal is conflating cause and effect slightly.
  In this mod, the rise of populism across the board is driven by the rise in terrorism, especially in free nations, and its presence in the international media. It is possible to shift the government to the right slightly to prevent this, which is almost "polarization."

Of course, other factors can be added and this can be improved, but either way this isn't the most appropriate discussion for an issue about the breakup of America! I'd be happy to discuss this further if you'd like; #50 is probably the best place.

**Comment by ARR8** [comment]
@simsulla - Well, it's just my opinion.

**Comment by ARR8** [comment]
e73e428

**Comment by settintotrieste** [comment]
FireBlaze:

Speaking of that dismantling, maybe give California Washington state; Texas Oklahoma and New Mexico; and give Florida to the CSA at the start. Also release a New England if you're feeling really spicy.

**Comment by ARR8** [comment]
Interestingly, I was considering making California smaller. As far as I know, there's no serious proposal for Californian independence that includes even the states it currently has in-game.

CSA vis-a-vis Florida is currently handled by the event ceding more "Southern" land should they go to war.

New England I am more partial to given its existence in vanilla, but that might take away any chance the US would have of reuniting the nation.

**Comment by settintotrieste** [comment]
US secessionist states were added late 2020 and the Civil War was based off the outcome of the 2020 election
