### ISSUE TITLE
Population Natalism decision continously being fired by ai. Missing timer effect when fired

### ISSUE THREAD

**Issue by Jamernacht99** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#913]
As said in the title. Also, hovering over the selection in `Decisions` to see the effect description crashes the game

**Comment by ccfox** [comment]
I can't seem to replicate the crashes - though issues with it not having a timer can certainly be fixed.

**Comment by settintotrieste** [comment]
Tested on my end and there is no issue. You must have forgotten to copy and replace the event_modifiers.txt file that was edited along with the population_growth.txt file.
