### ISSUE TITLE
New Zealand federation with Australia?

### ISSUE THREAD

**Issue by xoxo-Joanne** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#940]
I tried dabbling with this after a long break, but I'm very rusty with coding generally and tweaking mods like this.

Since Oceania is always a fun sandbox to explore, I have given a lot of though to an Australia-New Zealand merger. The two countries are in geographic proximity to one another, culturally interwoven, and I think that they would be relatively straightforward and thematically appropriate to consolidate them into a broader nation with a decision or event.

Is it possible to create a decision for New Zealand to apply for Australian statehood (or vice versa: Australia annexing New Zealand)? I know that this is theoretically possible in the grander scheme of the Pacific Islands Federation, but there is over a century of precedence for this:

https://en.wikipedia.org/wiki/List_of_proposed_states_of_Australia#New_Zealand

https://en.wikipedia.org/wiki/Australia–New_Zealand_relations#New_Zealand_as_an_Australian_state

There is even a constitutional provision in the Federation of Australia for New Zealand to become a state of the Commonwealth. From what I have read, fears for the maintenance and promotion of civil rights for the Maori people made the New Zealand government reticent to consider joining. Perhaps the decision can account for this, making them an accepted culture in Australia?

**Comment by settintotrieste** [comment]
Sure, I think this can be added.

**Comment by settintotrieste** [comment]
Mod development has stopped and so all outstanding issues will be closed.
