### ISSUE TITLE
Please revert commit 729e948aa7f4bb0466955af39d0a3f2a9beedb18

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#948]
The private_fork2 branch wasn't ready for distribution (I originally uploaded it because I feared losing my computer and life before I could upload the changes properly) due to missing author credits (for example: most of the primary culture changes were ported from Historical Project Mod and TK3600 deserves credit for the sustainable energy inventions https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/issues/749) and unmarked reverts like the Rusyn changes. The PR which caused this issue should be reverted until these issues are fixed.

**Comment by settintotrieste** [comment]
I see, that sounds very serious, hope you're okay now.

I was aware of the problems with some of the files so I didn't merge the PR in its entirety but rather just copied the stuff which I thought would be unproblematic to transfer over. In any case, I did another check on the commit today and fixed some mistaken transfers like the yue and karachay_balkar cultures in d98889eaa19ec33f12c532f6cd016f36e11edeb9. @ccfox has also fixed the mistaken addition of rusyn so I think the transfer shouldn't cause any issues going forward.

For the credits, I'll see if I can add TK's name to yesterday's commit.

**Comment by Outta-my-way-burrocrat** [comment]
Please reconsider reverting the commit, it would be cleaner and I've got a pared-down bugfix-only commit with proper credits in development

**Comment by settintotrieste** [comment]
I’m afraid it’s not possible to revert the commit now as I’ve done too many changes to the files in the commit since then. It should be fine as I’ve ironed out all the bugs in the private fork.
