### ISSUE TITLE
soviet union collapse event happen when i already reform the USSR, that not have any sense.

### ISSUE THREAD

**Issue by Santiago2710** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#950]
I reformed the USSR, I became the Russian federation, my economy is growing and I was reforming to become a republic and since them the USSR dissolution event happens, that doesn't have a sense. Why became republic make me dissolve if there is not more USSR and the country is reforming to become democratic? the worst thing is that then of taking back my territories my army is seruisly damage and i my literacy reduce from 28 to 13
![Captura de pantalla (299)](https://user-images.githubusercontent.com/98244959/180020016-f3300e3c-7b67-4cce-ba34-a82a2535b960.png)
.

**Comment by settintotrieste** [comment]
Okay, I've edited event 1991 to avoid a breakup.

**Comment by Santiago2710** [comment]
thanks, however the event have a good thing that is the fact that my satellite state libarate and abandon communism. i think that event have to still existed but only if the break up is with satellite states in this situation of a reform russia

**Comment by settintotrieste** [comment]
Yes, I’ve made the event release all communist puppet states.
