### ISSUE TITLE
Cold war does not end even after 2000.

### ISSUE THREAD

**Issue by Leo1836** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#953]
Not sure if it is intended or not. In my recent game China became the 1st GP with USSR 2nd GP and USA 3rd GP, the cold war did not end. Since USSR did not collapse, I could not unify Germany as West Germany.

**Comment by settintotrieste** [comment]
Yes, the Cold War only ends if the ussr or USA falls below rank 4
