### ISSUE TITLE
Starving aristocrats and colonial states

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#969]
Since the changes made to the aristocrat pop didn't change the demographics of most states without factories, many aristocrats start without any money.

**Comment by Outta-my-way-burrocrat** [comment]
There are still aristocrats in colonial states

**Comment by settintotrieste** [comment]
Okay, I've edited the starting decision to automatically convert executives in colonies to some other pop.
