### ISSUE TITLE
Easily fixed ideology bugs

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#972]
The  _uh localization for populists says they support removing political reforms. The nationalist _uh is also wrong.
The communist_social ideology has two _uh entries.
Traditionalist and nationalist ideology colors weren't updated after the recent changes to their national focuses.
The progressive ideology isn't limited to green parties anymore so it's _uh shouldn't focus on green politics.

**Comment by ccfox** [comment]
I can fix the loc stuff, though not the color things.
