### ISSUE TITLE
Too many optics factories

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#986]
What is the purpose of all 94 optics-glass factories in the mod? They are always going bankrupt every game.

**Comment by ccfox** [comment]
94? I wonder if that could be...opticmized.

**Comment by settintotrieste** [comment]
It's a legacy from nwo. I think it was because optics was used for military units or some starting factories during nwo's time hence they were added.
