### ISSUE TITLE
why Mongolia is not my puppet state?

### ISSUE THREAD

**Issue by Santiago2710** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#987]
![image](https://user-images.githubusercontent.com/98244959/187830753-b8843cb9-af7e-487a-b57e-dd757f7e6ce1.png)

**Comment by settintotrieste** [comment]
Dismantles give out puppet states randomly so you probably had a bad rng roll.

**Comment by Santiago2710** [comment]
> Dismantles give out puppet states randomly so you probably had a bad rng roll.

mongolia was always free and you know, before world war 2 was a soviet puppet

**Comment by settintotrieste** [comment]
It’s made independent to simulate the battle for control over Mongolia between the USSR and PRC. There’s an event in the 50s if there’s a China Soviet split for Mongolia to choose whose puppet they want to be.
