### ISSUE TITLE
There is not any new First Secretary of the Communist Party of the Soviet Union event, it is 1973 and Nikita Khrushchev died in 1971

### ISSUE THREAD

**Issue by Santiago2710** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#988]
There is not any new First Secretary of the Communist Party of the Soviet Union event, it is 1973 and Nikita Khrushchev died in 1971
![Captura de pantalla (368)](https://user-images.githubusercontent.com/98244959/188287455-bcd0f77d-e234-4353-ae17-dfc738a3bff0.png)

![Captura de pantalla (370)](https://user-images.githubusercontent.com/98244959/188287474-1e1df7c2-d357-4c57-9732-4a8c45f51795.png)

**Comment by Santiago2710** [comment]
so, what you change?

**Comment by ccfox** [comment]
There is now a successor for Khrushchev on that event.
