### ISSUE TITLE
Levantine Federation Decision 

### ISSUE THREAD

**Issue by codingfan786** [settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE#989]
![fixpls](https://user-images.githubusercontent.com/113201068/189400977-936255c4-a7af-4cf9-aeca-a6cb205019e5.JPG)
Since the levantine culture essentially replaces all of the cultures added in levantine federation (their home countries don't even accept them) the Israeli decision to form the Levantine federation should also add levantine as a culture. 

On a related note, the triggers for the decision require Druze and Alawite as puppets despite being cores of Syria. I think the decision should be able to be taken if Syria owns them, or even better yet if Israel directly owns all cores of the required puppets.

**Comment by ccfox** [comment]
I addressed this in the server.

**Comment by codingfan786** [comment]
> I addressed this in the server.

Yes I posted this before your response.
